import {photos} from './photos.mjs';
export const areas={kochi_city:'高知市内',east:'東部',west:'西部',north_niyodo:'北部・仁淀川'};
export const categories={sightseeing:'観光',gourmet:'グルメ',cycling:'サイクリング',camp:'キャンプ',onsen:'温泉',michinoeki:'道の駅',stay:'宿泊',fishing:'釣り',surfing:'サーフィン',activity:'アクティビティ'};
export const themes=['王道','グルメ','子連れ','カップル','絶景','ドライブ','アクティブ','雨の日'];
export const filters={sightseeing:['絶景','歴史','子連れ','雨の日','デート','定番','穴場'],gourmet:['ひろめ市場','カツオ','郷土料理','居酒屋','ラーメン','ランチ','スイーツ','朝ごはん','おみやげ'],activity:['川あそび','海あそび','釣り・漁業体験','空・山','洞窟体験','動物・自然観察','文化・ものづくり体験']};
const rows=[
['ryugado','龍河洞','sightseeing','east','香美市','雨の日,子連れ,定番','地底に広がる、もうひとつの高知。'],
['nikobuchi','にこ淵','sightseeing','north_niyodo','いの町','絶景,定番','心をほどく、仁淀ブルー。'],
['iokido','伊尾木洞','sightseeing','east','安芸市','絶景,穴場','緑に包まれた、神秘の散歩道。'],
['kochi-castle','高知城','sightseeing','kochi_city','高知市','歴史,定番','城下町の時間を、ゆっくり歩く。'],
['kashiwajima','柏島','sightseeing','west','大月町','絶景,デート','透きとおる海に、会いにいく。'],
['yasui','安居渓谷','sightseeing','north_niyodo','仁淀川町','絶景,穴場','渓谷の青と、深い緑。'],
['nakatsu','中津渓谷','sightseeing','north_niyodo','仁淀川町','絶景','水の音を道しるべに。'],
['monet','北川村「モネの庭」マルモッタン','sightseeing','east','北川村','デート,子連れ','花と光をめぐる庭時間。'],
['muroto','室戸岬','sightseeing','east','室戸市','絶景','太平洋を望む岬へ。'],
['karst','四国カルスト','sightseeing','west','津野町','絶景','空に近い、ドライブへ。'],
['yusuhara','梼原','sightseeing','west','梼原町','歴史','山あいの町を訪ねて。'],
['ashizuri','足摺岬','sightseeing','west','土佐清水市','絶景','海の向こうに思いを馳せて。'],
['makino-botanical-garden','高知県立牧野植物園','sightseeing','kochi_city','高知市','歴史,子連れ,定番','牧野富太郎博士の足跡と、四季の植物に出会う。'],
['chikurinji','竹林寺','sightseeing','kochi_city','高知市','歴史,定番','五重塔と名勝庭園に、土佐の祈りを感じる。'],
['kochi-castle-history-museum','高知県立高知城歴史博物館','sightseeing','kochi_city','高知市','歴史,雨の日,子連れ,定番','高知城を望み、土佐の歴史をひもとく。'],
['sakamoto-ryoma-memorial-museum','高知県立坂本龍馬記念館','sightseeing','kochi_city','高知市','歴史,雨の日,定番','桂浜で、龍馬と幕末の時代に出会う。'],
['shioe-tenmangu','潮江天満宮','sightseeing','kochi_city','高知市','歴史,定番','天神さまとともに歩んだ、城下町の祈り。'],
['myojinmaru','明神丸 本店','gourmet','kochi_city','高知市','カツオ,郷土料理,ディナー','高知らしい一皿から、旅が始まる。'],
['yasube','屋台安兵衛','gourmet','kochi_city','高知市','居酒屋','夜の高知に寄り道。'],
['hashimoto','橋本食堂','gourmet','west','須崎市','ラーメン,ランチ','あたたかな一杯を求めて。'],
['tanaka','田中鮮魚店 漁師小屋','gourmet','west','中土佐町','カツオ,ランチ','港町で味わう、海の恵み。'],
['shirasu','安芸しらす食堂 本店','gourmet','east','安芸市','ランチ','東部の旅に、おいしいひと休み。'],
['ice','高知アイス売店 仁淀川カフェ','gourmet','north_niyodo','いの町','スイーツ','川を眺める、カフェ時間。'],
['kayak','仁淀川シーカヤック','activity','north_niyodo','確認中','川あそび','水面から出会う、仁淀川。'],
['sauna','Niyodo Adventureのテントサウナ','activity','north_niyodo','仁淀川町','川あそび','自然を感じる、特別な時間。'],
['ryugado-adventure','龍河洞 冒険コース','activity','east','香美市','洞窟体験','真っ暗な洞窟を、ガイドと進む本格冒険。'],
['sarudado-caving','猿田洞ケイビング','activity','north_niyodo','日高村','洞窟体験','這って、登って、自然のままの洞窟へ。']];
const spotInfo={
  ryugado:{address:'高知県香美市土佐山田町逆川1424',phone:'0887-53-2144',official_url:'https://ryugadou.or.jp/',parking_text:'駐車場約700台',access:'高知自動車道南国ICから車。土佐山田駅からバス。',last_verified_at:'2026-09-23'},
  nikobuchi:{address:'高知県吾川郡いの町清水上分',official_url:'https://nikobuchi.inofan.jp/site/access.html',parking_text:'指定駐車場あり。満車時は臨時駐車場等の案内を確認。',access:'伊野ICから車で約60分。JR伊野駅からバス利用後、徒歩約20〜30分。',last_verified_at:'2026-09-23'},
  iokido:{address:'高知県安芸市伊尾木117',price_text:'無料',phone:'0887-34-8344（安芸観光情報センター）',official_url:'https://kochi-tabi.jp/search_spot.html?id=544',parking_text:'無料駐車場あり',access:'ごめん・なはり線伊尾木駅から徒歩約7分。南国ICから車で約45分。',last_verified_at:'2026-09-23'},
  'kochi-castle':{address:'高知県高知市丸ノ内1丁目2番1号',opening_hours:'9:00〜17:00（最終入館16:30）',closed_days:'12月26日〜1月1日',price_text:'18歳以上500円、18歳未満無料',phone:'088-824-5701（高知城管理事務所）',official_url:'https://kochipark.jp/kochijyo/',parking_text:'高知公園駐車場65台。7:30〜18:30、有料。',access:'高知駅から路面電車・バスで約15分。',last_verified_at:'2026-09-23'},
  'makino-botanical-garden':{address:'高知県高知市五台山4200-6',opening_hours:'9:00〜17:00（最終入園16:30）',closed_days:'年末年始（12月27日〜1月1日）およびメンテナンス休園日（公式サイトで要確認）',price_text:'一般850円、高校生以下無料（団体・企画展等は公式案内を確認）',phone:'088-882-2601',official_url:'https://www.makino.or.jp/',parking_text:'無料駐車場あり',access:'高知自動車道高知ICから五台山方面へ車で約20分。JR高知駅から周遊観光バス「MY遊バス」で約30分。',last_verified_at:'2026-09-26'},
  chikurinji:{address:'高知県高知市五台山3577',opening_hours:'参拝 8:00〜17:00、名勝庭園・宝物館 8:30〜17:00（最終入館16:30）',closed_days:'無休（行事等により拝観できない場合あり）',price_text:'境内参拝無料。名勝庭園・宝物館共通 大人800円（中学生以下は大人料金の半額、未就学児無料）',phone:'088-882-3085',official_url:'http://www.chikurinji.com/',parking_text:'無料駐車場あり（普通車約100台）',access:'高知ICから車で約20分。JR高知駅からMY遊バス「竹林寺」下車、徒歩約2分。',last_verified_at:'2026-09-30'},
  'kochi-castle-history-museum':{address:'高知県高知市追手筋2-7-5',opening_hours:'月〜土 9:00〜18:00、日曜 8:00〜18:00（展示室入室は閉館30分前まで）',closed_days:'12月27日〜1月1日',price_text:'企画展開催期間中 一般800円、その他の期間 一般500円。高校生以下無料',phone:'088-871-1600',official_url:'https://www.kochi-johaku.jp/',parking_text:'一般来館者用駐車場なし（障害者用2台）。周辺有料駐車場を利用。',access:'高知ICから車で約15分。とさでん交通「高知城前」下車、徒歩約2分。',last_verified_at:'2026-09-30'},
  'sakamoto-ryoma-memorial-museum':{address:'高知県高知市浦戸城山830番地',opening_hours:'9:00〜17:00（最終入館16:30）',closed_days:'なし',price_text:'企画展開催時 一般900円、その他の期間 一般500円。高校生以下無料',phone:'088-841-0001',official_url:'https://www.ryoma-kinenkan.jp/',parking_text:'無料駐車場あり。普通車42台（うち障害者用2台）',access:'高知南ICから車で約15分。JR高知駅BTから「桂浜」行きバスで「龍馬記念館前」下車、徒歩約2分。',last_verified_at:'2026-09-30'},
  'shioe-tenmangu':{address:'高知県高知市天神町19-20',opening_hours:'参拝自由（御朱印 9:00〜17:00、ご祈願受付 9:00〜11:30・13:00〜16:00）',closed_days:'なし（祭事等により受付時間変更の場合あり）',price_text:'参拝無料（ご祈願等は別途）',phone:'088-832-2896',official_url:'https://www.ushioe-tenmangu.jp/',parking_text:'専用駐車場なし。繁忙期以外は参道両脇に無料駐車可。',access:'高知ICから車で約15分。JR高知駅から車で約10分。とさでん交通「大橋通」から徒歩約15分。',last_verified_at:'2026-09-30'},
  kashiwajima:{address:'高知県幡多郡大月町柏島',closed_days:'島全体のため設定なし',price_text:'入域料なし',official_url:'https://www.town.otsuki.kochi.jp/life/dtl.php?hdnKey=1782',parking_text:'観光案内所駐車場は7〜9月のみ案内。171台、1日500円。年間常設情報としては未確認。',access:'大月町中心部から県道43号等を経由。',last_verified_at:'2026-09-23'},
  yasui:{address:'高知県吾川郡仁淀川町大屋',price_text:'無料',phone:'0889-35-1333（仁淀川町観光協会）',official_url:'https://kochi-tabi.jp/search_spot.html?id=693',parking_text:'無料駐車場約50台',access:'伊野ICから車で約65分。県道362号は狭い山道。',last_verified_at:'2026-09-23'},
  nakatsu:{address:'高知県吾川郡仁淀川町名野川',price_text:'無料',phone:'0889-35-1083（仁淀川町産業建設課）',official_url:'https://kochi-tabi.jp/search_spot.html?id=766',parking_text:'無料駐車場、普通車約30台',access:'伊野ICから車で約1時間。',last_verified_at:'2026-09-23'},
  monet:{address:'高知県安芸郡北川村野友甲1100',opening_hours:'9:00〜17:00（最終入園16:30）',closed_days:'6〜10月の第1・第3水曜日、12〜2月（冬期休園）',price_text:'大人1,000円、小中学生500円、6歳未満無料',phone:'0887-32-1233',official_url:'https://www.kjmonet.jp/',parking_text:'無料。普通車約100台、大型バス6台。',access:'奈半利駅から北川村営バス。奈半利町から車で約5分。',last_verified_at:'2026-09-23'},
  muroto:{address:'高知県室戸市室戸岬町',official_url:'https://www.muroto-kankou.com/access/',access:'高知市から国道55号で約2時間。奈半利駅からバスで約60分。',last_verified_at:'2026-09-23'},
  karst:{official_url:'https://town.kochi-tsuno.lg.jp/tsunobura/asobu/',access:'地点により異なる。津野町側は町内から車で約35分。',last_verified_at:'2026-09-23'},
  ashizuri:{address:'高知県土佐清水市足摺岬',price_text:'無料',phone:'0880-82-3155（土佐清水市観光協会）',official_url:'https://kochi-tabi.jp/search_spot.html?ID=712',parking_text:'無料。岬先端20台、第一115台、東50台。',access:'中村駅から車で約1時間。バス停「足摺岬」下車すぐ。',last_verified_at:'2026-09-23'},
  myojinmaru:{address:'高知県高知市本町1-1-2',opening_hours:'17:00〜23:30（L.O.23:00）',closed_days:'公式の定休日案内をご確認ください。',phone:'088-820-6505',official_url:'https://shop.myojinmaru.jp/shop/honten/',parking_text:'未確認',access:'JR高知駅から徒歩約10分。とさでん交通「堀詰」電停すぐ近く。',last_verified_at:'2026-10-01',description:'本店の店舗情報は公式サイトで確認済みです。定休日や臨時の営業時間変更は来店前に公式案内をご確認ください。'},
  yasube:{address:'高知県高知市廿代町4-19',opening_hours:'19:00〜翌3:00（L.O.閉店30分前）',closed_days:'日曜日（悪天候などで臨時休業の場合あり）',price_text:'屋台餃子600円、らーめん600円ほか（公式メニュー）',phone:'088-873-2773',official_url:'https://www.mfc-group.jp/yasube/shop.html',parking_text:'専用駐車場なし',access:'高知駅から徒歩約10分。蓮池町通停留場から徒歩約3分。',last_verified_at:'2026-10-01',description:'営業時間・定休日・主なメニュー価格は公式サイトで確認済みです。臨時休業や営業時間変更は公式のお知らせをご確認ください。'},
  hashimoto:{address:'高知県須崎市横町4-19',opening_hours:'11:00〜14:00',closed_days:'火曜日・日曜日・祝日',phone:'0889-42-2201',official_url:'https://kochi-tabi.jp/search_spot.html?id=7693',parking_text:'無料駐車場14台',access:'須崎中央ICから車で約5分。JR須崎駅から徒歩約15分。バス「横町」下車徒歩約2分。',last_verified_at:'2026-10-01',description:'営業時間・定休日・アクセスは高知県観光情報Webサイト「こうち旅ネット」で確認済みです。変更の可能性があるため来店前に最新情報をご確認ください。'},
  tanaka:{address:'高知県高岡郡中土佐町久礼6382',opening_hours:'漁師小屋 10:00〜14:30（L.O.14:30）／鮮魚店 9:00〜17:00',closed_days:'毎週水曜日・1月1日（臨時休業の場合あり）',phone:'0889-52-2729',official_url:'https://www.tanakatuo.com/',access:'JR土佐久礼駅から徒歩約5分。久礼大正町市場内。',last_verified_at:'2026-10-01',description:'漁師小屋の営業時間・定休日は田中鮮魚店の公式情報で確認済みです。魚の入荷や天候により臨時休業となる場合があります。'},
  shirasu:{address:'高知県安芸市西浜3411-46',opening_hours:'11:00〜15:30（L.O.）',closed_days:'木曜日・第1火曜日・年末年始',phone:'0887-34-8810',official_url:'https://akisuisan.com/restaurant/',parking_text:'駐車場あり',access:'南国ICから車で約40分。',last_verified_at:'2026-10-01',description:'店舗情報は安芸水産の公式サイトで確認済みです。臨時休業や営業時間変更は来店前に公式情報をご確認ください。'},
  ice:{address:'高知県吾川郡いの町柳瀬上分807-1',opening_hours:'平日11:00〜17:00（L.O.16:30）、土日祝・GW・お盆10:30〜17:00（L.O.16:30）',closed_days:'第2・第4月曜日（7・8月除く）・年末年始。月曜が祝日の場合は翌火曜。',phone:'090-3787-8511',official_url:'https://www.kochi-ice.com/stores/',parking_text:'無料駐車場あり',access:'伊野ICから車で約30分。',last_verified_at:'2026-10-01',description:'営業時間・定休日は高知アイス公式サイトで確認済みです。天候不良などによる臨時休業は公式SNS等をご確認ください。'},
  sauna:{address:'高知県吾川郡仁淀川町高瀬3869',opening_hours:'予約受付 8:00〜17:00',closed_days:'毎日開催（天候・河川状況等により中止の場合あり）',price_text:'1グループ10,000円（公式予約ページ）',phone:'080-5026-3288',official_url:'https://www.niyodoadventure.com/ja/river-sauna-tent',parking_text:'未確認',access:'伊野ICから車で約45分。高知市から車で約1時間30分。',last_verified_at:'2026-10-01',description:'所在地・連絡先・料金はNiyodo Adventure公式情報で確認済みです。所要時間は公式紹介ページと予約ページで表記が異なるため、予約時に最新内容をご確認ください。'},
  'ryugado-adventure':{address:'高知県香美市土佐山田町逆川1424',opening_hours:'午前 9:00・9:30・10:00開始／午後 13:00・13:30・14:00開始（11〜1月は10:00・14:00の催行なし）',closed_days:'無休（人数制限あり・事前予約制）',price_text:'観光コース料金＋2,000円。つなぎ・長靴レンタル1,000円',phone:'0887-53-2144',official_url:'https://ryugadou.or.jp/attraction/adventure-course/',parking_text:'龍河洞の駐車場を利用',access:'高知自動車道南国ICから車。土佐山田駅からバス。',last_verified_at:'2026-10-01',description:'龍河洞の観光コース途中から約200mの未整備区間へ入り、専属ガイドとヘッドライトを頼りに狭い岩の間を這ったり、体をひねって進む約90分の冒険コースです。事前予約が必要です。'},
  'sarudado-caving':{address:'高知県高岡郡日高村沖名1619（猿田洞）',opening_hours:'予約受付 9:00〜17:00',closed_days:'年末年始（ガイド確保できれば通年催行）',price_text:'4,000円／人（税込）。1名実施は6,000円（税込）',phone:'050-3204-1996（日高村観光協会）',official_url:'https://www.hidakamura.info/activity',parking_text:'無料駐車場あり',access:'受付は村の案内所ひだか（日高村本郷1478-9）。伊野ICから車で約15分。',last_verified_at:'2026-10-01',description:'日高村の猿田洞で、ガイドと一緒に自然のままの洞内を這ったり登ったりするケイビング体験です。参加条件や予約状況は日高村観光協会の最新案内をご確認ください。'}
};
const rank={};
export const spots=rows.map(([slug,name,category,area,municipality,tags,catchphrase],i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,slug,name,category,area,municipality,tags:tags.split(','),catchphrase,initial_rank:rank[category]=(rank[category]||0)+1,recommend_count:0,is_published:true,is_demo:true,photo:photos[slug]||null,main_image_url:photos[slug]?.src||'',description:'初期掲載候補です。営業時間・料金などは、公式情報の確認後に掲載します。',created_at:`2026-09-${String(i+1).padStart(2,'0')}T00:00:00Z`,...(spotInfo[slug]||{})}));
const courseRows=[
['kochi-classic','高知市内 王道1日コース','kochi_city','王道','1日',['kochi-castle','myojinmaru','yasube']],
['niyodo-classic','仁淀ブルー 王道1日コース','north_niyodo','絶景','1日',['nikobuchi','yasui','ice','nakatsu']],
['niyodo-active','仁淀川 アクティブ満喫1日コース','north_niyodo','アクティブ','1日',['kayak','sauna','ice','nakatsu']],
['east-drive','東部絶景＆しらすグルメ1日コース','east','グルメ','1日',['shirasu','iokido','monet','muroto']],
['ocean-trip','柏島・足摺 海の1泊2日コース','west','カップル','1泊2日',['kashiwajima','ashizuri']],
['karst-drive','四国カルスト・梼原 絶景ドライブ','west','ドライブ','1日',['karst','yusuhara']],
['kochi-gourmet','高知市内 グルメ満喫1日コース','kochi_city','グルメ','1日',['myojinmaru','yasube']],
['kami-konan','龍河洞・香美香南 1日コース','east','雨の日','1日',['ryugado']],
['family','高知 子連れ1日コース','kochi_city','子連れ','1日',['kochi-castle','myojinmaru']],
['three-days','高知満喫2泊3日コース','north_niyodo','王道','2泊3日',['kochi-castle','nikobuchi','iokido']]];
export const courses=courseRows.map(([slug,name,area,theme,duration,stops],i)=>({slug,name,area,theme,duration,stops,initial_rank:i+1,transport:'車＋徒歩',season:'季節・天候に応じて',audience:theme==='子連れ'?'家族':theme==='カップル'?'カップル':'友人・ひとり旅',photo:stops.map(slug=>photos[slug]).find(Boolean)||null,image:stops.map(slug=>photos[slug]?.src).find(Boolean)||''}));
export const eventCategories=['祭り・花火','グルメ','マルシェ','自然・アウトドア','文化・展覧会','子ども向け','スポーツ','期間限定体験'];
export const events=[
  {
    slug:'kochi-castle-autumn-oct-2026',
    image:'/assets/photos/kochi-castle.jpg',
    image_alt:'紅葉の時期をイメージした高知城',
    image_note:'会場イメージ',
    name:'高知城オータムフェスティバル（10月）',
    category:'文化・展覧会',
    area:'kochi_city',
    start_date:'2026-10-24',
    end_date:'2026-10-25',
    is_demo:false,
    description:'高知城の二ノ丸・懐徳館を会場に開催される秋のイベント。10月開催に続き、11月にも開催予定です。',
    venue:'高知城 二ノ丸・懐徳館',
    time:'10:00〜19:00',
    fee:'無料（天守・懐徳館は有料）',
    phone:'088-824-5701',
    official_url:'https://kochipark.jp/kochijyo/event/%E9%AB%98%E7%9F%A5%E5%9F%8E%E3%82%AA%E3%83%BC%E3%82%BF%E3%83%A0%E3%83%95%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%90%E3%83%AB/'
  },
  {
    slug:'okawa-shanikusai-2026',
    image:'/assets/photos/event-okawa.png',
    image_alt:'炭火で肉を焼くイベントのイメージ',
    image_note:'イメージ写真',
    name:'第43回 大川村謝肉祭',
    category:'グルメ',
    area:'north_niyodo',
    start_date:'2026-11-03',
    end_date:'2026-11-03',
    is_demo:false,
    description:'大川黒牛やはちきん地鶏を楽しむ大川村の名物イベント。2026年分の一般チケット受付は終了しています。',
    venue:'大川村 山村広場',
    time:'11:00〜15:00（開場10:30）',
    fee:'大人7,500円／高校生以下5,500円',
    phone:'0887-84-2201',
    official_url:'https://okawafk.or.jp/event/4838/'
  },
  {
    slug:'kochi-castle-autumn-nov-2026',
    image:'/assets/photos/kochi-castle.jpg',
    image_alt:'秋の高知城',
    image_note:'会場イメージ',
    name:'高知城オータムフェスティバル（11月）',
    category:'文化・展覧会',
    area:'kochi_city',
    start_date:'2026-11-21',
    end_date:'2026-11-23',
    is_demo:false,
    description:'高知城の秋を楽しむオータムフェスティバル第2期。11月21日のみ夜21時まで開催予定です。',
    venue:'高知城 二ノ丸・懐徳館',
    time:'10:00〜19:00（11月21日のみ21:00まで）',
    fee:'無料（天守・懐徳館は有料）',
    phone:'088-824-5701',
    official_url:'https://kochipark.jp/kochijyo/event/%E9%AB%98%E7%9F%A5%E5%9F%8E%E3%82%AA%E3%83%BC%E3%82%BF%E3%83%A0%E3%83%95%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%90%E3%83%AB/'
  },
  {
    slug:'yosakoi-2026',
    image:'/assets/photos/event-yosakoi.png',
    image_alt:'よさこい祭りで踊る人々のイメージ',
    image_note:'イメージ写真',
    name:'第73回よさこい祭り（2026）',
    category:'祭り・花火',
    area:'kochi_city',
    start_date:'2026-08-09',
    end_date:'2026-08-12',
    is_demo:false,
    description:'高知を代表する夏の祭り。8月10日・11日の本番を中心に、前夜祭・全国大会・後夜祭まで高知市中心部がよさこい一色に包まれました。',
    venue:'高知市追手筋ほか市内各会場',
    time:'会場・日程により異なる',
    fee:'観覧無料（一部有料観覧席あり）'
  },
  {
    slug:'tshirt-art-2026',
    image:'/assets/photos/event-tshirt-art.png',
    image_alt:'砂浜に並ぶTシャツ作品のイメージ',
    image_note:'イメージ写真',
    name:'第38回 Tシャツアート展',
    category:'文化・展覧会',
    area:'west',
    start_date:'2026-05-01',
    end_date:'2026-05-06',
    is_demo:false,
    description:'黒潮町・入野の浜に全国から集まったTシャツ作品が並ぶ、砂浜美術館の代表的な風景作品です。',
    venue:'砂浜美術館（黒潮町 入野の浜）',
    time:'9:00〜17:00',
    fee:'中学生以上 協力金300円',
    phone:'0880-43-4915',
    official_url:'https://sunabi.com/news-info/38th-t-shirt-art-program/'
  },
  {
    slug:'niyodogawa-koinobori-2026',
    image:'/assets/photos/course-niyodo-sup.png',
    image_alt:'仁淀川の清流',
    image_note:'仁淀川イメージ',
    name:'第30回 仁淀川 紙のこいのぼり',
    category:'自然・アウトドア',
    area:'north_niyodo',
    start_date:'2026-05-03',
    end_date:'2026-05-05',
    is_demo:false,
    description:'仁淀川の川面を紙のこいのぼりが泳ぐ、いの町の初夏の恒例イベント。グルメや体験企画も行われました。',
    venue:'仁淀川橋下（いの町波川公園周辺）',
    time:'9:00〜16:00（一部イベントは時間別）',
    fee:'一部体験等は個別料金あり',
    official_url:'https://www.inofan.jp/information/event/n4841/'
  },
  {
    slug:'kochi-castle-hanakairou-2026',
    image:'/assets/photos/event-hanakairou.png',
    image_alt:'夜の高知城と花のライトアップのイメージ',
    image_note:'イメージ写真',
    name:'高知城 花回廊2026',
    category:'文化・展覧会',
    area:'kochi_city',
    start_date:'2026-04-03',
    end_date:'2026-04-05',
    is_demo:false,
    description:'高知城・高知公園・丸ノ内緑地を生け花と灯りで彩る春の夜間イベントです。',
    venue:'高知城・高知公園・丸ノ内緑地',
    time:'18:00〜21:00',
    fee:'無料（天守・懐徳館は有料）',
    phone:'088-823-4016',
    official_url:'https://kochipark.jp/kochijyo/event/2026%E5%B9%B4%E3%80%80%E9%AB%98%E7%9F%A5%E5%9F%8E-%E8%8A%B1%E5%9B%9E%E5%BB%8A/'
  },
  {
    slug:'tosa-okyaku-2026',
    image:'/assets/photos/event-okyaku.png',
    image_alt:'高知の宴会文化を楽しむ人々のイメージ',
    image_note:'イメージ写真',
    name:'土佐の「おきゃく」2026',
    category:'グルメ',
    area:'kochi_city',
    start_date:'2026-03-07',
    end_date:'2026-03-15',
    is_demo:false,
    description:'高知の街を大きな宴会場に見立て、食・酒・音楽・よさこいなど多彩な催しを楽しむ春の恒例イベントです。',
    venue:'高知市中心商店街ほか',
    time:'各イベントにより異なる',
    fee:'各イベントにより異なる',
    phone:'088-823-0989',
    official_url:'https://tosa-okyaku.com/'
  }
];
export const sortSpots=items=>[...items].sort((a,b)=>b.recommend_count-a.recommend_count||a.initial_rank-b.initial_rank||a.slug.localeCompare(b.slug));
