import {photos} from './photos.mjs';
export const areas={kochi_city:'高知市内',east:'東部',west:'西部',north_niyodo:'北部・仁淀川'};
export const categories={sightseeing:'歴史文化',gourmet:'グルメ',cycling:'サイクリング',camp:'キャンプ',onsen:'温泉',michinoeki:'道の駅',stay:'宿泊',fishing:'釣り',surfing:'サーフィン',activity:'アクティビティ',experience:'体験'};
export const themes=['王道','グルメ','子連れ','カップル','絶景','ドライブ','アクティブ','雨の日'];
export const filters={sightseeing:['絶景','歴史','子連れ','雨の日','デート','定番','穴場'],gourmet:['ひろめ市場','カツオ','郷土料理','居酒屋','ラーメン','ランチ','スイーツ','朝ごはん','おみやげ'],fishing:['海釣り','川釣り','手ぶら','初心者','予約制'],surfing:['サーフィン','初心者','スクール','通年'],activity:['川あそび','海あそび','空・山','動物・自然観察','乗り物','レンタサイクル','子連れ','ガイドツアー','洞窟体験'],experience:['文化・ものづくり体験','食の体験','施設見学','ガイドツアー','釣り・漁業体験','動物・自然観察','海あそび','乗り物','空・山','雨の日','子連れ']};
const rows=[
['ryugado','龍河洞','sightseeing','east','香美市','雨の日,子連れ,定番','地底に広がる、もうひとつの高知。'],
['nikobuchi','にこ淵','sightseeing','north_niyodo','いの町','絶景,定番','心をほどく、仁淀ブルー。'],
['iokido','伊尾木洞','sightseeing','east','安芸市','絶景,穴場','緑に包まれた、神秘の散歩道。'],
['kochi-castle','高知城','sightseeing','kochi_city','高知市','歴史,定番','城下町の時間を、ゆっくり歩く。'],
['kashiwajima','柏島','sightseeing','west','大月町','絶景,デート','透きとおる海に、会いにいく。'],
['yasui','安居渓谷','sightseeing','north_niyodo','仁淀川町','絶景,穴場','渓谷の青と、深い緑。'],
['nakatsu','中津渓谷','sightseeing','north_niyodo','仁淀川町','絶景','水の音を道しるべに。'],
['monet','北川村「モネの庭」マルモッタン','sightseeing','east','北川村','デート,子連れ','花と光をめぐる庭時間。'],
['muroto','室戸岬','sightseeing','east','室戸市','絶景','太平洋を望む岬へ。'],
['karst','四国カルスト','sightseeing','west','津野町','絶景','空に近い、ドライブへ。'],
['yusuhara','梼原','sightseeing','west','梼原町','歴史','山あいの町を訪ねて。'],
['ashizuri','足摺岬','sightseeing','west','土佐清水市','絶景','海の向こうに思いを馳せて。'],
['makino-botanical-garden','高知県立牧野植物園','sightseeing','kochi_city','高知市','歴史,子連れ,定番','牧野富太郎博士の足跡と、四季の植物に出会う。'],
['chikurinji','竹林寺','sightseeing','kochi_city','高知市','歴史,定番','五重塔と名勝庭園に、土佐の祈りを感じる。'],
['kochi-castle-history-museum','高知県立高知城歴史博物館','sightseeing','kochi_city','高知市','歴史,雨の日,子連れ,定番','高知城を望み、土佐の歴史をひもとく。'],
['sakamoto-ryoma-memorial-museum','高知県立坂本龍馬記念館','sightseeing','kochi_city','高知市','歴史,雨の日,定番','桂浜で、龍馬と幕末の時代に出会う。'],
['shioe-tenmangu','潮江天満宮','sightseeing','kochi_city','高知市','歴史,定番','天神さまとともに歩んだ、城下町の祈り。'],
['myojinmaru','明神丸 本店','gourmet','kochi_city','高知市','カツオ,郷土料理,ディナー','高知らしい一皿から、旅が始まる。'],
['yasube','屋台安兵衛','gourmet','kochi_city','高知市','居酒屋','夜の高知に寄り道。'],
['hashimoto','橋本食堂','gourmet','west','須崎市','ラーメン,ランチ','あたたかな一杯を求めて。'],
['tanaka','田中鮮魚店 漁師小屋','gourmet','west','中土佐町','カツオ,ランチ','港町で味わう、海の恵み。'],
['shirasu','安芸しらす食堂 本店','gourmet','east','安芸市','ランチ','東部の旅に、おいしいひと休み。'],
['ice','高知アイス売店 仁淀川カフェ','gourmet','north_niyodo','いの町','スイーツ','川を眺める、カフェ時間。'],
['kayak','仁淀川 クリスタルカヤック体験','activity','north_niyodo','仁淀川町','川あそび','透明なカヤックで、仁淀ブルーを水上散歩。'],
['sauna','Niyodo Adventureのテントサウナ','activity','north_niyodo','仁淀川町','川あそび','自然を感じる、特別な時間。'],
['ryugado-adventure','龍河洞 冒険コース','activity','east','香美市','洞窟体験','真っ暗な洞窟を、ガイドと進む本格冒険。'],
['sarudado-caving','猿田洞ケイビング','activity','north_niyodo','日高村','洞窟体験','這って、登って、自然のままの洞窟へ。'],
['ikumi-surf','生見サーフィンビーチ','surfing','east','東洋町','サーフィン,通年','一年を通して波と出会う、東洋町のサーフスポット。'],
['irino-surf','入野海岸','surfing','west','黒潮町','サーフィン,初心者','約4kmの砂浜で、海と波を楽しむ。'],
['oki-surf','大岐海岸','surfing','west','土佐清水市','サーフィン,初心者','白い砂浜と緑に囲まれた、海辺のサーフポイント。'],
['susaki-fishing','須崎・富士ヶ浜 海釣り体験','fishing','west','須崎市','海釣り,手ぶら,初心者','海のまち須崎で、気軽に海釣りへ。'],
['uguru-fishing','鵜来島 釣り体験（うぐるBOX）','fishing','west','宿毛市','海釣り,予約制','透明な海に囲まれた離島で、釣りを楽しむ。'],
['tatsukushi-fishing','竜串 船釣り体験（西本渡船）','fishing','west','土佐清水市','海釣り,手ぶら,予約制','竜串の海を船でめぐりながら、釣りを楽しむ。'],
['niyodo-fishing','仁淀川の釣り','fishing','north_niyodo','仁淀川流域','川釣り','清流・仁淀川で、川と向き合う釣り時間。'],
['kaminokae-fishery','上ノ加江漁業体験','experience','west','中土佐町','釣り・漁業体験,海あそび','漁師と一緒に、海の仕事を体験。'],
['ogata-whale','大方ホエールウォッチング','activity','west','黒潮町','海あそび,動物・自然観察','漁船で、クジラとイルカを探す海へ。'],
['noichi-zoo','高知県立のいち動物公園','activity','east','香南市','動物・自然観察,子連れ','自然の中で、いきいきと暮らす動物たちに会いに。'],
['muroto-dolphin','室戸ドルフィンセンター','activity','east','室戸市','動物・自然観察,海あそび,子連れ','イルカとふれあう、室戸の特別な時間。'],
['forest-adventure-kochi','フォレストアドベンチャー・高知','activity','west','津野町','空・山,子連れ','森の中で、全身を使って冒険しよう。'],
['niyodo-buggy','NIYODO バギー体験（NOZUアドベンチャー）','activity','north_niyodo','日高村','空・山,乗り物','仁淀川の自然を、バギーで駆け抜ける。'],
['agawa-paragliding','吾川スカイパーク パラグライダー','activity','north_niyodo','仁淀川町','空・山','仁淀ブルーを見下ろす、空中散歩へ。'],
['ino-papermaking','紙漉き体験（いの町紙の博物館）','experience','north_niyodo','いの町','文化・ものづくり体験,子連れ','土佐和紙を、自分の手ですく。'],
['yosakoi-naruko','鳴子づくり体験（高知よさこい情報交流館）','experience','kochi_city','高知市','文化・ものづくり体験,雨の日','よさこいの鳴子を、自分で仕上げる。'],
['katsuo-waraya','カツオの藁焼きタタキづくり体験（黒潮一番館）','experience','west','黒潮町','食の体験,文化・ものづくり体験','自分で焼く、豪快なカツオの藁焼き。'],
['tosa-tataki-dojo','土佐タタキ道場','experience','kochi_city','高知市','食の体験,子連れ','自分で藁焼きして、熱々のカツオを味わう。'],
['field-kochi','FIELD KOCHI 里山体験・土佐塩の道ウォーキング','experience','east','香美市','文化・ものづくり体験,食の体験,空・山','里山の暮らしと、歴史の道を体感する。'],
['ryugado-candle','龍河洞キャンドルづくり（38 phyto lab.）','experience','east','香美市','文化・ものづくり体験,雨の日','旅の思い出を、オリジナルキャンドルに。'],
['shimanto-canoe','四万十川カヌー体験（しまんとベース）','activity','west','四万十市','川あそび,子連れ','清流・四万十川で、のんびりカヌー体験。'],
['yoshinogawa-rafting','吉野川ラフティング体験（You Me Rafting）','activity','north_niyodo','大豊町','川あそび,子連れ','四国・吉野川の流れを、ラフティングで体感。'],
['kochi-horse-riding','高知ホースライディングクラブ 乗馬体験','activity','kochi_city','高知市','動物・自然観察,乗り物,子連れ','はじめてでも、馬とゆっくり仲良くなる時間。'],
['uguru-snorkel','鵜来島 シュノーケル体験（うぐるBOX）','activity','west','宿毛市','海あそび,動物・自然観察','透明な海で、鵜来島の水中世界をのぞく。'],
['sakoda-knife','刃物鍛造体験（迫田打刃物）','experience','west','須崎市','文化・ものづくり体験','職人と一緒に、一本の包丁を鍛え上げる。'],
['uchiharano-craft','陶芸・ガラス体験（内原野陶芸館）','experience','east','安芸市','文化・ものづくり体験,雨の日,子連れ','土とガラスから、自分だけの作品をつくる。'],
['tosaco-brewery','TOSACO TAP STAND・醸造所','experience','east','香美市','施設見学,食の体験','高知素材のクラフトビールが生まれる場所へ。'],
['takagi-sake','高木酒造 酒蔵見学','experience','east','香南市','施設見学,食の体験','赤岡で140年以上続く、土佐酒の蔵を訪ねる。'],
['tosa-terrace-cycle','こうち旅広場 レンタサイクル','activity','kochi_city','高知市','レンタサイクル,乗り物','高知駅から、自転車でまちへ出よう。'],
['tosappo-ryoma-walk','龍馬の生まれたまち歩き〜土佐っ歩〜','experience','kochi_city','高知市','ガイドツアー,文化・ものづくり体験','ガイドと歩く、龍馬ゆかりの城下町。'],
['muroto-aqua-farm','室戸海洋深層水アクア・ファーム','experience','east','室戸市','施設見学,雨の日','海洋深層水のしくみを、無料で見学。'],
['muroto-geo-guide','室戸世界ジオパーク ガイドツアー','experience','east','室戸市','ガイドツアー,空・山','大地の物語を、ガイドと歩いて知る。'],
['muroto-rockpool','室戸世界ジオパーク 磯遊び体験','activity','east','室戸市','海あそび,動物・自然観察,子連れ','室戸の磯で、生きものと地形を観察。'],
['muroto-cycle-tour','室戸世界ジオパーク サイクリングツアー','activity','east','室戸市','レンタサイクル,乗り物,ガイドツアー','海と大地を感じながら、室戸を自転車でめぐる。'],
['withriver-shimanto','四万十川 SUP・カヌー ガイドツアー（withRIVER）','activity','west','四万十市','川あそび,ガイドツアー,子連れ','四万十川を、SUPとカヌーでゆったり楽しむ。'],
['garbanzo-yoshino','アウトドア！ガルバンゾ 吉野川リバーアクティビティ','activity','north_niyodo','大豊町','川あそび,子連れ','SUP・カヤック・パックラフトまで、吉野川を遊び尽くす。'],
['tsuno-tea-field','津野茶 茶畑見学・お茶体験','experience','west','津野町','食の体験,ガイドツアー,文化・ものづくり体験','茶畑を歩き、利き茶とブレンドティーを楽しむ。'],
['soltive-salt','天日塩づくり体験（ソルティーブ）','experience','west','黒潮町','食の体験,文化・ものづくり体験','海水から塩になるまでを、自分の手で体験。'],
['tano-solar-salt','完全天日塩づくり体験（田野町）','experience','east','田野町','食の体験,文化・ものづくり体験,子連れ','太陽と風だけでつくる塩を、見て・作って・持ち帰る。'],
['tosacho-woodwork','土佐町 木組み・鍋敷きづくり体験','experience','north_niyodo','土佐町','文化・ものづくり体験,食の体験','釘を使わず、地元の木で鍋敷きをつくる。'],
['shimanto-traditional-fishing','四万十川 伝統漁法体験','experience','west','四万十市','釣り・漁業体験,ガイドツアー','川漁師と、柴漬け漁・投網・櫓漕ぎを体験。'],
['kuroshio-soba','そば打ち体験（であいの里 蜷川）','experience','west','黒潮町','食の体験,文化・ものづくり体験','地元のそば粉で打って、できたてを味わう。'],
['hinodeya-konnyaku','こんにゃく作り体験（燈ので家）','experience','north_niyodo','大豊町','食の体験,文化・ものづくり体験','山里の農家民宿で、手づくりこんにゃく。'],
['seiran-konnyaku','田舎こんにゃく体験（せいらんの里）','experience','west','津野町','食の体験,子連れ','地元のこんにゃく芋から、できたてを味わう。'],
['qraud-papermaking','紙漉き体験（土佐和紙工芸村「くらうど」）','experience','north_niyodo','いの町','文化・ものづくり体験,子連れ,雨の日','はがきや色紙を、自分の手で漉いてつくる。'],
['kashiwajima-diving-aquas','柏島 体験ダイビング（AQUAS）','activity','west','大月町','海あそび,動物・自然観察','透明度の高い柏島の海へ、はじめてのダイビング。'],
['tatsukushi-diving','竜串 体験ダイビング（竜串ダイビングセンター）','activity','west','土佐清水市','海あそび,動物・自然観察','サンゴと熱帯魚が暮らす竜串の海を、水中から楽しむ。'],
['sakawa-makino-park-guide','牧野公園ガイド','experience','north_niyodo','佐川町','ガイドツアー,動物・自然観察','牧野博士ゆかりの草花を、ガイドと歩いて楽しむ。'],
['sakawa-makino-sacred-walk','牧野博士の聖地を歩く（南山麓コース）','experience','north_niyodo','佐川町','ガイドツアー,文化・ものづくり体験','牧野博士の足跡をたどる、約7kmの里山ウォーク。'],
['katsurahama-guide','桂浜散策ガイド','experience','kochi_city','高知市','ガイドツアー,動物・自然観察','海辺の植物と史跡を、ガイドと一緒にめぐる。'],
['makino-guide-walk','まきのガイドウォーク','experience','kochi_city','高知市','ガイドツアー,動物・自然観察','専門スタッフの解説で、見頃の植物と園の魅力を知る。'],
['shimanto-botanical-dye','草木染め体験（四万十かわらっこ）','experience','west','四万十市','文化・ものづくり体験,子連れ','四万十の植物で、バンダナやストールをやさしい色に染める。'],
['mihara-rural-stay','農家民宿くろうさぎ 田舎暮らし体験','experience','west','三原村','食の体験,動物・自然観察,ガイドツアー','山里に泊まり、季節の農・川・里山の暮らしにふれる。'],
['susaki-warauma','わら馬作り体験（すさきまちかどギャラリー）','experience','west','須崎市','文化・ものづくり体験,雨の日','高知に伝わる七夕飾り「わら馬」を、自分の手でつくる。'],
['tosa-kokubunji-culture','土佐国分寺 日本文化・瞑想体験','experience','east','南国市','文化・ものづくり体験,ガイドツアー,雨の日','本堂見学・瞑想・抹茶で、日本文化を静かに体験。'],
['ashizuri-secret-guide','足摺秘境ガイド','experience','west','土佐清水市','ガイドツアー,動物・自然観察','海からの断崖と巨石群を、地元ガイドとめぐる。'],
['mihara-slow-cycling','三原村 スローサイクリング（今ちゃん出発）','activity','west','三原村','レンタサイクル,乗り物,ガイドツアー','朝の田園をブロンプトンでゆっくり走り、三原米の朝ごはんへ。'],
['ashizuri-ebike','足摺半島ぐるっと一周 E-bikeガイドツアー','activity','west','土佐清水市','レンタサイクル,乗り物,ガイドツアー','E-bikeで足摺半島を一周し、自然・文化・ローカルフードを楽しむ。'],
['shimanto-observatory','星空の街で天体観望会（四万十天文台）','experience','west','四万十市','ガイドツアー,動物・自然観察','反射式望遠鏡で、四万十の夜空と季節の天体を観察。'],
['tatsukushi-glassboat','竜串観光汽船 グラスボート','activity','west','土佐清水市','海あそび,乗り物,子連れ','船底のガラス越しに、サンゴと熱帯魚の海を楽しむ。'],
['tatsukushi-minokoshi-tour','見残し奇岩パークツアー＋グラスボート','experience','west','土佐清水市','ガイドツアー,海あそび,動物・自然観察','グラスボートとガイド散策で、見残し海岸を深く楽しむ。'],
['otsuki-glassboat-yubari','グラスボートゆうばり','activity','west','大月町','海あそび,乗り物,子連れ','潜らずに、柏島・周防形のサンゴと海の生きものを見る。'],
['kochi-market-fruit-basket','高知市卸売市場 果物のセリ見学＋マイフルーツバスケット作り','experience','kochi_city','高知市','食の体験,文化・ものづくり体験,施設見学','市場の朝を歩き、果物のセリと竹かご作りを一度に体験。'],
['shimanto-sada-cycling','佐田沈下橋 ガイドサイクリング','activity','west','四万十市','レンタサイクル,乗り物,ガイドツアー','赤鉄橋から佐田・三里沈下橋へ、約20kmを案内人と走る。'],
['akano-shishimai','赤野獅子舞 伝統芸能体験（大元神社）','experience','east','安芸市','文化・ものづくり体験,ガイドツアー','600年以上続く獅子舞を、地域の人との交流とともに体感。'],
['shimanto-fish-auction-lunch','四万十 公設卸売市場 模擬競り＋おさかなランチ','experience','west','四万十市','食の体験,施設見学,子連れ','魚の模擬競りに参加し、落札魚や土佐の魚料理を味わう。'],
['shimanto-yakatabune-cafe','四万十川屋形船 水上カフェ','experience','west','四万十市','食の体験,乗り物,子連れ','四万十川に浮かぶ屋形船で、ご当地コーヒーとスイーツを楽しむ。'],
['kaiyodo-nankoku-workshop','ものづくり体験（海洋堂Space Factoryなんこく）','experience','east','南国市','文化・ものづくり体験,雨の日,子連れ','フィギュア色塗りやジオラマ作りで、世界に一つの作品をつくる。'],
['obuchi-kokedama','苔玉づくり体験（おおぶち自然村）','experience','north_niyodo','土佐町','文化・ものづくり体験,動物・自然観察,子連れ','好きな苗で苔玉を作り、里山散策も楽しむ。'],
['tosa-shio-no-michi-walk','土佐塩の道ウォーク（FIELD KOCHI）','experience','east','香美市','ガイドツアー,動物・自然観察','歴史ある塩の道を歩き、竹べんとうと地域の物語を味わう。'],
['takemasa-sodabushi','伝統の節納屋見学＆宗田節体験（たけまさ商店）','experience','west','土佐清水市','食の体験,施設見学,文化・ものづくり体験','宗田節の工場を見学し、削り体験とMYだし醤油づくり。'],
['niyodogawa-seicho-paper','土佐清張紙 工房見学＋クラフト体験','experience','north_niyodo','仁淀川町','文化・ものづくり体験,施設見学,ガイドツアー','最後の一軒となった和紙工房を訪ね、伝統紙と地域の歴史にふれる。'],
['umaji-yuzu-forest-ebike','魚梁瀬森林鉄道跡とゆずロード E-bikeツアー','activity','east','馬路村','レンタサイクル,乗り物,ガイドツアー','旧森林鉄道跡とゆずロードを、E-bikeで約25km巡る。'],
['yoshino-headwaters-track-walk','吉野川源流森林軌道ウォーク','experience','north_niyodo','いの町','ガイドツアー,動物・自然観察,食の体験','森林軌道跡を歩き、地元の人と山菜ランチを楽しむ。'],
['monobe-izanagi-stay','まきの宿 いざなぎ流・古民家宿泊体験','experience','east','香美市','文化・ものづくり体験,ガイドツアー,食の体験','築80年の古民家に泊まり、御幣切りと朝散歩で物部文化にふれる。'],
['shimanto-yairocho-walk','四万十ヤイロチョウの森と森林鉄道遺構ウォーク','experience','west','四万十町','ガイドツアー,動物・自然観察','ヤイロチョウ調査員と森を歩き、森林鉄道遺構と野鳥の世界を学ぶ。'],
['aki-shirasu-fisher-tour','五感で感じる しらす漁師ツアー','experience','east','安芸市','釣り・漁業体験,食の体験,施設見学','朝の土佐湾で釣りと漁港見学を楽しみ、ちりめん丼まで味わう。'],
['ino-cosplay-photo-tour','コスプレで巡る レトロな街 いの町 フォトツアー','experience','north_niyodo','いの町','ガイドツアー,文化・ものづくり体験','古民家や神社、レトロな町並みをコスプレ姿で撮影散策。'],
['kochi-kimono-ozashiki','着物で楽しむ 料亭濱長お座敷遊び体験','experience','kochi_city','高知市','食の体験,文化・ものづくり体験,ガイドツアー','着物に着替え、土佐芸妓・舞妓やガイドとお座敷文化を楽しむ。'],
['hanpeita-harimaya-guide','半平太・はりまや橋コース','experience','kochi_city','高知市','ガイドツアー,文化・ものづくり体験','幕末史跡からはりまや橋まで歩き、路面電車とよさこい体験も楽しむ。'],
['gomen-nahari-fruit-train','ごめん・なはり線 絶景フルーツ列車','experience','east','南国市','食の体験,乗り物,子連れ','太平洋を眺めながら沿線のフルーツを味わうローカル列車旅。'],
['kure-fisher-town-fullcourse','中土佐町久礼 漁師町フルコース','experience','west','中土佐町','食の体験,施設見学,ガイドツアー','カツオ競り、天日塩、藁焼き、朝食で久礼の漁師町を丸ごと体験。'],
['bentenza-backstage-experience','弁天座 芝居小屋バックヤード見学＆体験ツアー','experience','east','香南市','施設見学,文化・ものづくり体験,雨の日','芝居小屋の舞台裏を見学し、廻り舞台とセリも体験する。'],
['uranouchi-akame-fishing','浦ノ内湾 アカメ釣り体験','experience','west','須崎市','釣り・漁業体験,動物・自然観察','手ぶらで、日本三大怪魚のアカメをインストラクターと狙う。'],
['tsuno-tea-fullcourse','津野町 茶畑ウォーキング＋茶摘み＋田舎ごはん','experience','west','津野町','食の体験,ガイドツアー,動物・自然観察','茶畑を歩き、茶摘み・茶揉み・田舎ごはんまで楽しむ。'],
['kiriyama-roasting-teacan','霧山茶園 ほうじ茶焙煎＋和紙茶缶づくり','experience','north_niyodo','日高村','食の体験,文化・ものづくり体験','和紙の茶缶を作り、自分好みにほうじ茶を手焙煎する。'],
['yusuhara-china-paint','梼原 本格絵付け体験','experience','west','梼原町','文化・ものづくり体験,雨の日','プロの指導で皿やマグカップに絵付けし、オリジナル作品を作る。'],
['tosayama-haiku','英語でHAIKU in 土佐山','experience','kochi_city','高知市','文化・ものづくり体験,ガイドツアー,食の体験','里山を歩いて季語を探し、英語俳句と季節の会席を楽しむ。'],
['ioki-morning-market-tour','朝の伊尾木洞探検＋ぢばさん市場ツアー','experience','east','安芸市','ガイドツアー,食の体験,動物・自然観察','静かな朝の伊尾木洞を歩き、安芸駅ぢばさん市場で地元の恵みを楽しむ。'],
['yodo-line-cycle-rafting','予土線＋自転車＋ラフティングで巡る四万十川','activity','west','四万十町','川あそび,レンタサイクル,乗り物,ガイドツアー','予土線の車窓、約14kmのサイクリング、ラフティングを1日で満喫。'],
['shimizu-saba-town-tour','清水さば漁港ツアー＋漁師町食べ歩き','experience','west','土佐清水市','食の体験,施設見学,ガイドツアー','清水さばの市場見学、漁師町の食べ歩き、刺身ランチを楽しむ。'],
['kuroshio-earthing-stay','黒潮町 渚のアーシング体験 1泊2日','experience','west','黒潮町','ガイドツアー,食の体験,動物・自然観察','渚の散歩とストレッチ、土鍋料理、薪ストーブサウナを楽しむ一棟貸し滞在。'],
['niyodo-water-seitai','仁淀ブルーを眺めながら水上整体','experience','north_niyodo','いの町','動物・自然観察,ガイドツアー','仁淀川の浅瀬に置いたベッドで、川景色を眺めながら整体を受ける。'],
['iwayagawa-irimochi-hike','岩屋川渓谷ハイキング＋郷土茶菓いりもち','experience','north_niyodo','仁淀川町','ガイドツアー,動物・自然観察,食の体験','巨岩の渓谷を歩き、最後に郷土茶菓いりもちとほうじ茶でひと休み。'],
['shimanto-fisher-firefly','四万十川 漁師体験＋幻想ホタル遊覧ツアー','experience','west','四万十市','釣り・漁業体験,食の体験,動物・自然観察','川漁師体験、四万十牛BBQ、夜のホタル遊覧を1泊2日で楽しむ。'],
['sakawa-black-tea-tasting','紅茶農家で国産紅茶6品種テイスティング＋スイーツ','experience','north_niyodo','佐川町','食の体験,ガイドツアー','国産紅茶6品種を飲み比べ、地元スイーツとのペアリングを楽しむ。'],
['ikegawa-afternoon-tea','仁淀ブルー絶景アフタヌーンティー','experience','north_niyodo','仁淀川町','食の体験','土居川を眺めながら、土佐茶2種と手作りスイーツ5種を味わう。'],
['motoyama-vegan-farm','Farm-to-table ビーガン和食＆農園体験','experience','north_niyodo','本山町','食の体験,動物・自然観察,ガイドツアー','棚田の農園で収穫し、精進出汁とビーガン和食ディナーを学び味わう。'],
['asemikawa-ebike','汗見川 清流E-bikeサイクリング','activity','north_niyodo','本山町','レンタサイクル,乗り物,ガイドツアー','透明な汗見川沿いをE-bikeで約25km走り、地元ランチを楽しむ。'],
['tosa-mokumen-factory','日本唯一のもくめん工場見学＋クラフト体験','experience','north_niyodo','土佐市','施設見学,文化・ものづくり体験,雨の日','高知県産木材の天然緩衝材「もくめん」の工場を見学し、クラフトも楽しむ。'],
['otsuki-squid-fishing','大月満喫ツアー イカ釣り体験','experience','west','大月町','釣り・漁業体験,海あそび','夏の夜、船で沖へ出てケンサキイカを狙う。'],
['yasea-sup-kayak','ヤ・シィパーク SUP＆カヤック体験','activity','east','香南市','海あそび,子連れ','海水浴場でSUPとカヤックを初心者向けに楽しむ。'],
['shimizu-katsuo-show','市場直送カツオ 解体ショー＋藁焼き3種食べ比べ','experience','west','土佐清水市','食の体験,施設見学','魚市場のセリから解体ショー、藁焼き、カツオ3種の食べ比べまで体験。']];
const spotInfo={
  ryugado:{address:'高知県香美市土佐山田町逆川1424',opening_hours:'2月1日〜10月31日 8:30〜17:00（最終入洞）、11月1日〜1月31日 8:30〜16:30（最終入洞）',closed_days:'年中無休',price_text:'観光コース 大人1,500円、中学生800円、小学生600円',phone:'0887-53-2144',official_url:'https://ryugadou.or.jp/',parking_text:'駐車場約700台',access:'高知自動車道南国ICから車。土佐山田駅からバス。',last_verified_at:'2026-10-03'},
  nikobuchi:{address:'高知県吾川郡いの町清水上分2976-11',price_text:'無料（協力金のお願いあり）',phone:'088-893-1211（いの町観光協会）',official_url:'https://nikobuchi.inofan.jp/site/access.html',parking_text:'無料駐車場あり（若干数）',access:'伊野ICから車で約50分。',last_verified_at:'2026-10-03',description:'神聖な場所として大切にされている仁淀ブルーの名所です。入水・飲食・喫煙は禁止。岩場は滑りやすく、雨天・増水時は危険なため注意が必要です。'},
  iokido:{address:'高知県安芸市伊尾木117',price_text:'無料',phone:'0887-34-8344（安芸観光情報センター）',official_url:'https://kochi-tabi.jp/search_spot.html?id=544',parking_text:'無料駐車場あり',access:'ごめん・なはり線伊尾木駅から徒歩約7分。南国ICから車で約45分、芸西西ICから約20分。',last_verified_at:'2026-10-03',description:'全長約40mの海食洞の先に、国の天然記念物に指定されたシダ群落が広がります。散策は滑りにくい靴を推奨し、増水時や夏場は安全に十分注意してください。'},
  'kochi-castle':{address:'高知県高知市丸ノ内1丁目2番1号',opening_hours:'9:00〜17:00（最終入館16:30。GW・よさこい祭期間等は延長の場合あり）',closed_days:'12月26日〜1月1日',price_text:'18歳以上500円、18歳未満無料',phone:'088-824-5701（高知城管理事務所）',official_url:'https://kochipark.jp/kochijyo/',parking_text:'高知公園駐車場65台。7:30〜18:30、有料。普通車は最初の1時間370円、以降30分110円。',access:'高知駅から路面電車・バスで約15分。',last_verified_at:'2026-10-03'},
  'makino-botanical-garden':{address:'高知県高知市五台山4200-6',opening_hours:'9:00〜17:00（最終入園16:30）',closed_days:'年末年始（12月27日〜1月1日）。2026年は10月26日・11月30日もメンテナンス休園',price_text:'一般850円、高校生以下無料。団体750円（20名以上）',phone:'088-882-2601',official_url:'https://www.makino.or.jp/',parking_text:'無料駐車場あり',access:'高知自動車道高知ICから五台山方面へ車で約20分。JR高知駅から周遊観光バス「MY遊バス」で約30分。',last_verified_at:'2026-10-03'},
  chikurinji:{address:'高知県高知市五台山3577',opening_hours:'参拝 8:00〜17:00、名勝庭園・宝物館 8:30〜17:00（最終入館16:30）',closed_days:'無休（行事等により拝観できない場合あり）',price_text:'境内参拝無料。名勝庭園・宝物館共通 大人800円、庭園のみ500円、宝物館のみ400円。中学生以下は半額、未就学児無料',phone:'088-882-3085',official_url:'http://www.chikurinji.com/',parking_text:'無料駐車場あり（普通車約100台）',access:'高知ICから車で約20分。JR高知駅からMY遊バス「竹林寺」下車、徒歩約2分。',last_verified_at:'2026-10-03'},
  'kochi-castle-history-museum':{address:'高知県高知市追手筋2-7-5',opening_hours:'月〜土 9:00〜18:00、日曜 8:00〜18:00（展示室入室は閉館30分前まで）',closed_days:'通常は12月27日〜1月1日。2026年は設備工事のため12月20日〜25日も臨時休館',price_text:'企画展開催期間中 一般800円、その他の期間 一般500円。高校生以下無料',phone:'088-871-1600',official_url:'https://www.kochi-johaku.jp/',parking_text:'一般来館者用駐車場なし（障害者用2台）。周辺有料駐車場を利用。',access:'高知ICから車で約15分。とさでん交通「高知城前」下車、徒歩約2分。',last_verified_at:'2026-10-03'},
  'sakamoto-ryoma-memorial-museum':{address:'高知県高知市浦戸城山830番地',opening_hours:'9:00〜17:00（最終入館16:30）',closed_days:'年中無休（展示替え等で一部展示室が休室する場合あり）',price_text:'企画展開催時 一般900円、その他の期間 一般500円。高校生以下無料',phone:'088-841-0001',official_url:'https://www.ryoma-kinenkan.jp/',parking_text:'無料駐車場あり。普通車42台（うち障害者用2台）',access:'高知南ICから車で約15分。JR高知駅BTから「桂浜」行きバスで「龍馬記念館前」下車、徒歩約2分。',last_verified_at:'2026-10-03'},
  'shioe-tenmangu':{address:'高知県高知市天神町19-20',opening_hours:'参拝自由（御朱印 9:00〜17:00、ご祈願受付 9:00〜11:30・13:00〜16:00）',closed_days:'なし（祭事等により受付時間変更の場合あり）',price_text:'参拝無料（ご祈願等は別途）',phone:'088-832-2896',official_url:'https://www.ushioe-tenmangu.jp/',parking_text:'専用駐車場なし。繁忙期以外は参道両脇に無料駐車可。12月31日〜1月3日、6月30日、7月22日、11月18〜19日は駐車不可',access:'高知ICから車で約15分。JR高知駅から車で約10分。とさでん交通「大橋通」から徒歩約15分。',last_verified_at:'2026-10-03'},
  kashiwajima:{address:'高知県幡多郡大月町柏島',closed_days:'島全体のため設定なし',price_text:'入域料なし',phone:'0880-62-8133（大月町観光協会）',official_url:'https://www.town.otsuki.kochi.jp/life/dtl.php?hdnKey=1782',parking_text:'柏島観光情報発信センター駐車場171台。通常無料、7〜9月は1日500円。',access:'四万十町中央ICから車で約2時間。宿毛和田ICから約40分。',last_verified_at:'2026-10-03'},
  yasui:{address:'高知県吾川郡仁淀川町大屋',price_text:'無料',phone:'0889-35-1333（仁淀川町観光協会）',official_url:'https://kochi-tabi.jp/search_spot.html?id=693',parking_text:'無料駐車場約50台',access:'伊野ICから車で約1時間5分。県道362号は1車線の山道が続くため運転注意。',last_verified_at:'2026-10-03'},
  nakatsu:{address:'高知県吾川郡仁淀川町名野川',price_text:'無料',phone:'0889-35-1083（仁淀川町産業建設課）',official_url:'https://kochi-tabi.jp/search_spot.html?id=766',parking_text:'無料駐車場、普通車約30台',access:'伊野ICから車で約1時間。',last_verified_at:'2026-10-03',description:'県立自然公園に指定された渓谷で、入口から石柱まで約2.3kmの遊歩道があります。紅葉の滝、雨竜の滝、龍宮淵などを巡りながら散策できます。'},
  monet:{address:'高知県安芸郡北川村野友甲1100',opening_hours:'9:00〜17:00（最終入園16:30）',closed_days:'6〜10月の第1・第3水曜日。2026年12月1日〜2027年3月12日は水の庭工事に伴う冬期休園',price_text:'一般1,000円、小中学生500円、小学生未満無料',phone:'0887-32-1233',official_url:'https://www.kjmonet.jp/',parking_text:'無料。普通車約100台、大型バス6台。',access:'奈半利駅から北川村営バス。奈半利町から車で約5分。',last_verified_at:'2026-10-03'},
  muroto:{address:'高知県室戸市室戸岬町',phone:'0887-22-0574（室戸市観光協会）',official_url:'https://www.muroto-kankou.com/access/',parking_text:'周辺に無料駐車場あり',access:'南国ICから車で約1時間40分。芸西西ICから約1時間10分。奈半利駅からバスで約1時間。',last_verified_at:'2026-10-03'},
  karst:{phone:'0889-55-2021（津野町産業課）',official_url:'https://town.kochi-tsuno.lg.jp/tsunobura/asobu/',access:'津野町役場西庁舎から天狗高原・カルストテラス方面へ車で約35分。',last_verified_at:'2026-10-03',description:'標高約1,400mの高原に石灰岩が点在する四国カルスト。津野町側のカルストテラスは9:00〜17:00、月曜休館（祝日の場合は翌平日休館）、入館無料です。'},
  yusuhara:{phone:'0889-65-1187（ゆすはら雲の上観光協会）',official_url:'https://yusuhara-kumonoue-kanko.jp/',access:'公共交通は須崎駅前から高陵交通バスの梼原方面を利用。町内散策や各スポットへの移動方法は観光協会の最新案内を確認。',last_verified_at:'2026-10-03',description:'梼原町は森林・自然、歴史文化、隈研吾建築、ガイドツアーなどを楽しめる山間の町です。観光案内は、ゆすはら雲の上観光協会の公式情報をご確認ください。'},
  ashizuri:{address:'高知県土佐清水市足摺岬',price_text:'無料',phone:'0880-82-3155（土佐清水市観光協会）',official_url:'https://kochi-tabi.jp/search_spot.html?ID=712',parking_text:'無料。足摺岬先端20台、第一駐車場115台、東側駐車場50台。',access:'四万十町中央ICから車で約1時間50分。中村駅から車で約1時間。バス停「足摺岬」下車すぐ。',last_verified_at:'2026-10-03'},
  myojinmaru:{address:'高知県高知市本町1-1-2',opening_hours:'17:00〜23:30（L.O.23:00）',closed_days:'公式の定休日案内をご確認ください。',phone:'088-820-6505',official_url:'https://shop.myojinmaru.jp/shop/honten/',access:'JR高知駅から徒歩約10分。とさでん交通「堀詰」電停すぐ近く。',last_verified_at:'2026-10-01',description:'本店の店舗情報は公式サイトで確認済みです。定休日や臨時の営業時間変更は来店前に公式案内をご確認ください。'},
  yasube:{address:'高知県高知市廿代町4-19',opening_hours:'19:00〜翌3:00（L.O.閉店30分前）',closed_days:'日曜日（悪天候などで臨時休業の場合あり）',price_text:'屋台餃子600円、らーめん600円ほか（公式メニュー）',phone:'088-873-2773',official_url:'https://www.mfc-group.jp/yasube/shop.html',parking_text:'専用駐車場なし',access:'高知駅から徒歩約10分。蓮池町通停留場から徒歩約3分。',last_verified_at:'2026-10-01',description:'営業時間・定休日・主なメニュー価格は公式サイトで確認済みです。臨時休業や営業時間変更は公式のお知らせをご確認ください。'},
  hashimoto:{address:'高知県須崎市横町4-19',opening_hours:'11:00〜14:00',closed_days:'火曜日・日曜日・祝日',phone:'0889-42-2201',official_url:'https://kochi-tabi.jp/search_spot.html?id=7693',parking_text:'無料駐車場14台',access:'須崎中央ICから車で約5分。JR須崎駅から徒歩約15分。バス「横町」下車徒歩約2分。',last_verified_at:'2026-10-01',description:'営業時間・定休日・アクセスは高知県観光情報Webサイト「こうち旅ネット」で確認済みです。変更の可能性があるため来店前に最新情報をご確認ください。'},
  tanaka:{address:'高知県高岡郡中土佐町久礼6382',opening_hours:'漁師小屋 10:00〜14:30（L.O.14:30）／鮮魚店 9:00〜17:00',closed_days:'毎週水曜日・1月1日（臨時休業の場合あり）',phone:'0889-52-2729',official_url:'https://www.tanakatuo.com/',access:'JR土佐久礼駅から徒歩約5分。久礼大正町市場内。',last_verified_at:'2026-10-01',description:'漁師小屋の営業時間・定休日は田中鮮魚店の公式情報で確認済みです。魚の入荷や天候により臨時休業となる場合があります。'},
  shirasu:{address:'高知県安芸市西浜3411-46',opening_hours:'11:00〜15:30（L.O.）',closed_days:'木曜日・第1火曜日・年末年始',phone:'0887-34-8810',official_url:'https://akisuisan.com/restaurant/',parking_text:'駐車場あり',access:'南国ICから車で約40分。',last_verified_at:'2026-10-01',description:'店舗情報は安芸水産の公式サイトで確認済みです。臨時休業や営業時間変更は来店前に公式情報をご確認ください。'},
  ice:{address:'高知県吾川郡いの町柳瀬上分807-1',opening_hours:'平日11:00〜17:00（L.O.16:30）、土日祝・GW・お盆10:30〜17:00（L.O.16:30）',closed_days:'第2・第4月曜日（7・8月除く）・年末年始。月曜が祝日の場合は翌火曜。',phone:'090-3787-8511',official_url:'https://www.kochi-ice.com/stores/',parking_text:'無料駐車場あり',access:'伊野ICから車で約30分。',last_verified_at:'2026-10-01',description:'営業時間・定休日は高知アイス公式サイトで確認済みです。天候不良などによる臨時休業は公式SNS等をご確認ください。'},
  kayak:{address:'高知県吾川郡仁淀川町長屋6',opening_hours:'予約受付 9:00〜17:00',closed_days:'不定休',price_text:'6,500円〜（プランにより異なる）',phone:'0889-20-9619（仁淀川アウトドアセンター）',official_url:'https://www.niyodo.jp/',parking_text:'駐車場あり',access:'高知自動車道・伊野ICから車で約50分。',last_verified_at:'2026-10-03',description:'仁淀川上流域で、透明なクリスタルカヤックを楽しむ体験です。陸上レクチャー後、流れの穏やかなエリアをガイド付きで水上散歩します。料金・空き状況・集合時間は予約時に最新情報をご確認ください。'},
  sauna:{address:'高知県吾川郡仁淀川町高瀬3869',opening_hours:'予約受付 8:00〜17:00',closed_days:'毎日開催（天候・河川状況等により中止の場合あり）',price_text:'1グループ10,000円（公式予約ページ）',phone:'080-5026-3288',official_url:'https://www.niyodoadventure.com/ja/river-sauna-tent',access:'伊野ICから車で約45分。高知市から車で約1時間30分。',last_verified_at:'2026-10-01',description:'所在地・連絡先・料金はNiyodo Adventure公式情報で確認済みです。所要時間は公式紹介ページと予約ページで表記が異なるため、予約時に最新内容をご確認ください。'},
  'ryugado-adventure':{address:'高知県香美市土佐山田町逆川1424',opening_hours:'午前 9:00・9:30・10:00開始／午後 13:00・13:30・14:00開始（11〜1月は10:00・14:00の催行なし）',closed_days:'無休（人数制限あり・事前予約制）',price_text:'観光コース料金＋2,000円。つなぎ・長靴レンタル1,000円',phone:'0887-53-2144',official_url:'https://ryugadou.or.jp/attraction/adventure-course/',parking_text:'龍河洞の駐車場を利用',access:'高知自動車道南国ICから車。土佐山田駅からバス。',last_verified_at:'2026-10-01',description:'龍河洞の観光コース途中から約200mの未整備区間へ入り、専属ガイドとヘッドライトを頼りに狭い岩の間を這ったり、体をひねって進む約90分の冒険コースです。事前予約が必要です。'},
  'sarudado-caving':{address:'高知県高岡郡日高村沖名1619（猿田洞）',opening_hours:'予約受付 9:00〜17:00',closed_days:'年末年始（ガイド確保できれば通年催行）',price_text:'4,000円／人（税込）。1名実施は6,000円（税込）',phone:'050-3204-1996（日高村観光協会）',official_url:'https://www.hidakamura.info/activity',parking_text:'無料駐車場あり',access:'受付は村の案内所ひだか（日高村本郷1478-9）。伊野ICから車で約15分。',last_verified_at:'2026-10-01',description:'日高村の猿田洞で、ガイドと一緒に自然のままの洞内を這ったり登ったりするケイビング体験です。参加条件や予約状況は日高村観光協会の最新案内をご確認ください。'},
  'ikumi-surf':{address:'高知県安芸郡東洋町大字生見',opening_hours:'通年',phone:'0887-29-3395（東洋町産業建設課）',official_url:'https://kochi-tabi.jp/search_spot.html?id=1249',parking_text:'有料駐車場あり。普通車140台（2か所計）',access:'南国ICから車で約2時間。芸西西ICから車で約1時間30分。',last_verified_at:'2026-10-02',description:'全長約1kmの海岸で、通年サーフィンを楽しめるスポットとして高知県観光情報で案内されています。シャワー（有料）・トイレがあります。'},
  'irino-surf':{address:'高知県幡多郡黒潮町入野',phone:'0880-43-2113（黒潮町産業推進室観光係）',official_url:'https://kochi-tabi.jp/search_spot.html?ID=740&pcflg=PC',access:'四万十町中央ICから車で約45分。土佐入野駅から徒歩約10分。',last_verified_at:'2026-10-02',description:'約4kmの白い砂浜が続く入野海岸。海水浴やサーフィンを楽しめ、初心者向けのサーフィン体験も案内されています。'},
  'oki-surf':{address:'高知県土佐清水市大岐',opening_hours:'24時間',price_text:'無料',phone:'0880-82-1212（土佐清水市 観光商工課）',official_url:'https://kochi-tabi.jp/search_spot_sightseeing.html?id=715',parking_text:'無料駐車場あり',access:'四万十町中央ICから車で約1時間30分。',last_verified_at:'2026-10-02',description:'白い砂浜と緑の林が約1.6km続く海岸。高知県観光情報でもサーフポイントとして案内されています。'},
  'susaki-fishing':{address:'高知県須崎市富士ヶ浜周辺',opening_hours:'体験受付の目安 8:30〜17:15',closed_days:'年末年始',official_url:'https://kochi-tabi.jp/search_activity_plan.html?easy_reserve=1&plan_id=53696&plan_ota=aj',parking_text:'富士ヶ浜近くに駐車スペースあり',access:'須崎市観光協会事務所から富士ヶ浜まで車で約3分、徒歩約10分。',last_verified_at:'2026-10-02',description:'須崎市観光協会で釣具一式を借り、富士ヶ浜周辺で海釣りを楽しめる体験です。詳細・料金・予約条件は最新の販売ページをご確認ください。'},
  'uguru-fishing':{address:'高知県宿毛市沖の島町鵜来島58',opening_hours:'予約受付 7:50〜21:00',closed_days:'不定休',phone:'080-4410-2441',official_url:'https://kochi-tabi.jp/search_spot.html?id=13597',access:'片島港から宿毛市営定期船で約50分〜1時間35分。',last_verified_at:'2026-10-02',description:'宿毛沖の離島・鵜来島で楽しむ釣り体験。透明度の高い海と手つかずの自然の中で過ごせます。予約条件は公式案内をご確認ください。'},
  'tatsukushi-fishing':{address:'高知県土佐清水市竜串21',opening_hours:'予約受付 8:00〜17:00',closed_days:'不定休',phone:'090-1176-5819',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=8286',access:'四万十町中央ICから車で約1時間40分。',last_verified_at:'2026-10-02',description:'竜串の海で楽しむ手ぶらの船釣り体験。実施内容や予約条件は最新の公式案内をご確認ください。'},
  'niyodo-fishing':{address:'仁淀川町〜越知町〜佐川町〜日高村〜いの町〜土佐市',phone:'0889-20-9511（仁淀ブルー観光協議会）',official_url:'https://kochi-tabi.jp/search_spot.html?ID=12167',access:'流域各地でアクセスが異なります。釣行場所・遊漁規則・解禁情報は現地の最新案内をご確認ください。',last_verified_at:'2026-10-02',description:'仁淀川では昔から釣りを含む水辺利用が親しまれています。釣種・場所・時期によって遊漁規則等が異なるため、釣行前に最新情報をご確認ください。'},
  'kaminokae-fishery':{address:'高知県高岡郡中土佐町上ノ加江2574',opening_hours:'予約営業（受付は平日のみ。観光案内では予約受付9:30〜16:30）',closed_days:'予約営業（受付は平日のみ）',price_text:'料金は申込時に問い合わせ',phone:'0889-54-0111（高知県漁協 上ノ加江支所）',official_url:'https://www.town.nakatosa.lg.jp/life/detail.php?hdnKey=166',parking_text:'施設へ事前確認',access:'高知自動車道・中土佐ICから車で約10分。',last_verified_at:'2026-10-02',description:'季節に応じて、かご漁・網漁・釣りなどを現役漁師と一緒に体験できます。内容や料金は時期・プランで変わるため、予約時に高知県漁協上ノ加江支所へご確認ください。'},
  'ogata-whale':{address:'高知県幡多郡黒潮町入野227-ロ',opening_hours:'2026年は通常9:00出航。3連休以上は8:00・13:00の2便（集合は各便30分前）',closed_days:'2026年5月2日〜10月31日の期間中無休（荒天時欠航）',price_text:'大人8,000円／小学生4,000円／幼児2,000円（税込）',phone:'0880-43-1058',official_url:'https://nitarikujira.com/',parking_text:'駐車場あり',access:'高知自動車道・四万十町中央ICから車で約50分。土佐くろしお鉄道 入野駅から徒歩約30分。',last_verified_at:'2026-10-02',description:'黒潮町の現役漁師が操る漁船で土佐湾へ出航し、カツオクジラやイルカなどを探す約4時間のウォッチング体験です。野生動物のため必ず出会えるとは限らず、天候により欠航する場合があります。'},
  'noichi-zoo':{address:'高知県香南市野市町大谷738',opening_hours:'9:30〜17:00（入園16:00まで）',closed_days:'毎週月曜日（祝日の場合は翌日）、12月29日〜1月1日',price_text:'大人470円、18歳未満・高校生以下無料',phone:'0887-56-3500',official_url:'https://noichizoo.or.jp/',parking_text:'無料。普通車約280台・バス10台',access:'南国ICから車で約20分。高知龍馬空港から車で約10分。',last_verified_at:'2026-10-02',description:'生息地に近い環境づくりを大切にした動物公園。自然に囲まれた園内で、幅広い世代が動物観察を楽しめます。'},
  'muroto-dolphin':{address:'高知県室戸市室戸岬町字鯨浜6810-162',opening_hours:'10:00〜17:00（最終入場16:30）',closed_days:'水曜日（4〜6月、10月〜翌年3月。祝日・春休み等は営業の場合あり）',price_text:'入場料：大人550円、4歳〜小学生440円、3歳以下無料。体験プログラムは別料金',phone:'0887-22-1245',official_url:'https://www.muroto-dc.net/',parking_text:'駐車場あり',access:'高知市内から国道55号で約2時間。奈半利駅からバス約50分＋徒歩約10分。',last_verified_at:'2026-10-02',description:'イルカのトレーニング見学や餌やり、ドルフィンスイムなどの体験プログラムを実施しています。天候やイルカの状態により内容変更・休園となる場合があります。'},
  'forest-adventure-kochi':{address:'高知県高岡郡津野町芳生野乙5422',opening_hours:'9:00〜14:30（予約時間）',closed_days:'不定休',phone:'080-2347-3318',official_url:'https://kochi-tabi.jp/search_spot.html?id=15818',parking_text:'無料駐車場30台',access:'高知自動車道・須崎東ICから車で約1時間。',last_verified_at:'2026-10-02',description:'森の地形を活かしたアドベンチャーコースやキャノピーコースを楽しめる体験施設です。利用条件・料金・空き状況は予約前に公式案内をご確認ください。'},
  'niyodo-buggy':{address:'高知県高岡郡日高村本村226番地1',opening_hours:'9:00〜16:00（完全予約制）',closed_days:'定休日なし。予約受付は月曜・第2・第4日曜を除く',phone:'0889-39-1857',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=16564',parking_text:'無料駐車場あり',access:'高知自動車道・伊野ICから車で約25分。',last_verified_at:'2026-10-02',description:'日高村能津地区の自然の中を、ガイド付きでバギー走行する体験です。完全予約制のため、料金・参加条件・空き状況は予約時にご確認ください。'},
  'agawa-paragliding':{address:'高知県吾川郡仁淀川町上名野川563',opening_hours:'4月〜11月。体験時間は予約時に確認',closed_days:'冬季（12月1日〜3月31日）',price_text:'半日体験5,700円、タンデム9,000円、タンデム＋半日体験14,000円、ショート4,000円',phone:'089-971-3190（ウィンドパルESD）',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=856',parking_text:'無料駐車場あり',access:'高知自動車道・伊野ICから車で約1時間30分。',last_verified_at:'2026-10-02',description:'標高約750mの吾川スカイパークで楽しむパラグライダー体験。タンデムなら初心者でも参加できます。天候条件によりフライトできない場合があります。'},
  'ino-papermaking':{address:'高知県吾川郡いの町幸町110-1',opening_hours:'紙漉き体験 9:00〜11:45・13:00〜16:00',closed_days:'月曜日（祝日の場合は翌日）。2026年11月16日〜2027年3月31日は改修工事のため臨時休館',price_text:'紙漉き体験500円（別途入館料）',phone:'088-893-0886',official_url:'https://kamihaku.com/experience',parking_text:'無料。普通車50台・大型3台',access:'伊野ICから車で約10分。JR伊野駅・とさでん交通「伊野」から徒歩約10分。',last_verified_at:'2026-10-02',description:'伝統工芸の土佐和紙を実際に漉く約1時間の体験です。開館日は毎日開催し、少人数は予約不要です。2026年11月16日〜2027年3月31日は改修工事のため臨時休館します。'},
  'yosakoi-naruko':{address:'高知県高知市はりまや町1-10-1',opening_hours:'10:00〜18:30（最終入館18:00）',closed_days:'水曜日、12月29日〜1月1日',price_text:'白木鳴子1,500円、カラー鳴子2,000円（2本1組）',phone:'088-880-4351',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=3271',parking_text:'専用駐車場なし',access:'高知ICから車で約10分。高知駅から徒歩約10分。',last_verified_at:'2026-10-02',description:'よさこい祭りに欠かせない鳴子を自分で作る体験です。高知市中心部で、雨の日にも立ち寄りやすい文化体験です。'},
  'katsuo-waraya':{address:'高知県幡多郡黒潮町佐賀374-9',opening_hours:'11:00〜15:00',closed_days:'火曜日（祝祭日の場合は営業）、11月末〜2月。水揚げ状況により変動あり',price_text:'本格体験4,000円／名、お手軽体験3,000円／名（いずれも2名〜・要事前予約）',phone:'0880-55-3680',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=1054',parking_text:'無料。普通車10台・大型5台',access:'四万十町中央ICから車で約30分。土佐佐賀駅から徒歩約20分。',last_verified_at:'2026-10-02',description:'カツオを捌くところから挑戦する本格体験と、藁で焼くところから楽しむお手軽体験があります。体験希望日の3日前までの予約が必要です。'},
  'tosa-tataki-dojo':{address:'高知県高知市仁井田201-2',opening_hours:'10:30〜15:00（カツオがなくなり次第終了）',closed_days:'無休',price_text:'体験付き藁焼きタタキ定食1,800円／体験付き藁焼きタタキ単品1,500円',phone:'088-847-3255',official_url:'https://kochi-tabi.jp/search_spot.html?ID=7777&pcflg=SP',parking_text:'無料駐車場あり（普通車100台）',access:'高知ICから車で約20分。高知南ICから車で約10分。',last_verified_at:'2026-10-02',description:'自分でカツオを藁焼きし、焼きたてを味わえる高知らしい食体験です。カツオの入荷状況により早めに終了する場合があります。'},
  'field-kochi':{address:'高知県香美市物部町',opening_hours:'9:00〜17:00',closed_days:'不定休',price_text:'体験内容により異なる（要予約）',phone:'090-7622-1112',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=16497',parking_text:'体験場所により異なる',access:'香美市物部町内。集合場所は各プログラムの予約時に確認。',last_verified_at:'2026-10-02',description:'田舎寿司づくり、茶摘み、柚子狩りなどの里山体験と、歴史ある「土佐塩の道」を歩くガイドウォーキングを提供しています。電話または公式案内から事前予約が必要です。'},
  'ryugado-candle':{address:'高知県香美市土佐山田町逆川1395-1 2F',opening_hours:'12:00〜18:00',closed_days:'木曜日。火・水曜日は予約制ワークショップのみ営業',price_text:'キャンドル体験料金は予約サイトで確認',official_url:'https://ryugadou.or.jp/shops_restaurants/67/',parking_text:'龍河洞の駐車場を利用',access:'龍河洞入口の商店街内「38 phyto lab.」2F。',last_verified_at:'2026-10-02',description:'龍河洞観光とあわせて楽しめるキャンドルづくり体験。イニシャルキャンドルなど、旅のお土産になるオリジナル作品を作れます。'},
  'shimanto-canoe':{address:'高知県四万十市西土佐津野川20-1',opening_hours:'8:30〜17:00',closed_days:'12月〜2月は冬季休業（案内により不定休表記あり）',price_text:'コース・時期により異なるため予約時に確認',phone:'0880-49-0113',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=15625',parking_text:'施設へ確認',access:'四万十町中央ICから車で約1時間10分。',last_verified_at:'2026-10-02',description:'四万十川で楽しむ半日・短時間のカヌー体験。川下りではなく一定範囲で練習・川遊びを楽しめるため、家族連れにも参加しやすいプログラムです。'},
  'yoshinogawa-rafting':{address:'高知県長岡郡大豊町永渕6-1',opening_hours:'8:00〜17:00（夏季8:00〜20:00）',closed_days:'12月〜3月は冬季休業',price_text:'体験料金は予約プランにより異なる',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=15399',parking_text:'施設へ確認',access:'高知自動車道・大豊ICから車で約20分。',last_verified_at:'2026-10-02',description:'吉野川の流れを楽しむラフティング体験。初心者向けから本格的なコースまであり、時期や水量により内容が変わるため予約時に最新情報をご確認ください。'},
  'kochi-horse-riding':{address:'高知県高知市朝倉己1152番地99',opening_hours:'受付10:00〜17:00',closed_days:'火曜日（火曜が祝日の場合は月曜日）',price_text:'体験料金・参加条件は販売サイトで確認',official_url:'https://kochi-tabi.jp/search_activity_plan.html?plan_id=8141&plan_ota=aj',parking_text:'施設へ確認',access:'高知市朝倉エリア。詳細は予約時に確認。',last_verified_at:'2026-10-02',description:'馬に触れたことがない初心者でも、スタッフがマンツーマンで接し方や乗り方を案内する乗馬体験です。'},
  'uguru-snorkel':{address:'高知県宿毛市沖の島町鵜来島58',opening_hours:'予約受付7:50〜21:00',closed_days:'不定休',price_text:'体験・レンタル料金は予約時に確認',phone:'080-4410-2441',official_url:'https://kochi-tabi.jp/search_spot.html?id=13597',parking_text:'島内施設の案内を確認',access:'片島港から宿毛市営定期船で約50分〜1時間35分。',last_verified_at:'2026-10-02',description:'鵜来島の透明度の高い海で楽しむシュノーケル体験。海況や季節により実施条件が変わるため、事前予約時に最新情報をご確認ください。'},
  'sakoda-knife':{address:'高知県須崎市神田781',opening_hours:'予約受付9:00〜17:00',closed_days:'不定休（龍馬パスポート案内では日・祝休み）',price_text:'体験料金は公式案内・予約時に確認',phone:'0889-43-1907',official_url:'https://kochi-tabi.jp/search_spot.html?id=8277',parking_text:'施設へ確認',access:'高知自動車道・須崎東ICから車で約5分。',last_verified_at:'2026-10-02',description:'職人の指導のもと、鍛造から砥ぎ仕上げまでに触れ、完成した5寸万能包丁を持ち帰れる土佐打刃物の体験です。'},
  'uchiharano-craft':{address:'高知県安芸市川北乙1607-1',opening_hours:'予約受付9:00〜17:00（体験受付15:00まで）',closed_days:'陶芸：水曜日（祝日の場合は開館）／ガラス：水・木曜日／年末年始12月29日〜1月4日',price_text:'陶芸体験3,000円〜／バーナーワーク3,000円〜／サンドブラスト1,500円〜',phone:'0887-32-0308',official_url:'https://lb2.kochi-tabi.jp/search_spot.html?id=860',parking_text:'無料駐車場あり',access:'南国ICから車で約1時間、芸西西ICから約25分。',last_verified_at:'2026-10-02',description:'手びねりや絵付けなどの陶芸体験に加え、ガラス工房ではバーナーワークやサンドブラストを体験できます。'},
  'tosaco-brewery':{address:'高知県香美市香北町橋川野584-1',opening_hours:'TAP STAND：木・金16:00〜21:00、土日祝11:00〜18:00',closed_days:'月・火・水（祝日の場合は営業。変動あり）',price_text:'工場見学・試飲は旅行商品や事前調整での実施例あり。個人利用は事前確認',phone:'0887-59-2633',official_url:'https://kochi-tabi.jp/search_spot_food.html?id=16535',parking_text:'無料駐車場あり',access:'南国ICから車で約20分。JR土佐山田駅からバス「川奈路」下車すぐ。',last_verified_at:'2026-10-02',description:'高知県産のゆずや文旦などを使ったクラフトビールの醸造所。工場見学と試飲を組み込んだ旅行商品での実施実績があります。個人での見学可否は事前に施設へご確認ください。'},
  'takagi-sake':{address:'高知県香南市赤岡町443',opening_hours:'平日8:00〜17:00',closed_days:'土日・祝祭日。酒造期は蔵見学不可',price_text:'蔵見学は予約時に確認。15名以上の団体は入館料5,000円／バス1台',phone:'0887-55-1800',official_url:'https://kochi-tabi.jp/search_spot_sightseeing.html?id=16496',parking_text:'無料。乗用車3台、北隣接多目的駐車場あり',access:'南国ICから車で約20分。ごめん・なはり線赤岡駅から徒歩約3分。',last_verified_at:'2026-10-02',description:'1884年創業の酒蔵。蔵見学は希望日の1週間前までに予約が必要で、酒造期は見学を受け付けていません。開催日・見学時間・参加費は予約時にご確認ください。'},
  'tosa-terrace-cycle':{address:'高知県高知市北本町2-10-17 こうち旅広場「とさてらす」',opening_hours:'8:30〜17:00（最終受付16:00）',closed_days:'年中無休',price_text:'シティサイクル500円／日、電動シティ・電動スポーツ1,000円／日',phone:'088-879-6400',official_url:'https://lb2.kochi-tabi.jp/tabihiroba/index.html',parking_text:'周辺駐車場を利用',access:'JR高知駅南口すぐ。',last_verified_at:'2026-10-02',description:'高知駅前から市街地観光へ出発できるレンタサイクル。シティサイクル、電動シティサイクル、電動スポーツタイプがあります。日をまたいでの利用はできません。'},
  'tosappo-ryoma-walk':{address:'高知県高知市上町2-6-33（高知市立龍馬の生まれたまち記念館）',opening_hours:'予約受付8:00〜19:00',closed_days:'通年実施（臨時休館あり。コースにより事前予約が必要）',price_text:'大人700円〜1,500円（コースにより異なる）',phone:'088-820-1115',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=8017',parking_text:'記念館・周辺駐車場の案内を確認',access:'高知ICから車で約20分。',last_verified_at:'2026-10-03',description:'坂本龍馬ゆかりの上町周辺を、ガイドと一緒に歩くまち歩きツアーです。全8コースがあり、コースにより所要時間・料金が異なります。予約が必要なコースは3日前16時までの事前申込が案内されています。'},
  'muroto-aqua-farm':{address:'高知県室戸市室戸岬町3507-1',opening_hours:'9:00〜16:00',closed_days:'日曜・祝日・年末年始（メンテナンス等で臨時休館の場合あり）',price_text:'見学無料',phone:'0887-24-2822',official_url:'https://kochi-tabi.jp/search_spot.html?id=6193',parking_text:'無料。普通車14台',access:'南国ICから車で約1時間50分。奈半利駅からバス「高岡神社前」下車、徒歩約3分。',last_verified_at:'2026-10-02',description:'水深374mから取水する室戸海洋深層水の施設。館内のパネルや模型、深層水商品のサンプルなどを自由に見学できます。'},
  'muroto-geo-guide':{address:'高知県室戸市室戸岬町1810-2',opening_hours:'予約受付9:00〜17:00',closed_days:'無休',price_text:'ガイド料金はコースにより異なるため予約時に確認',phone:'0887-23-1610',official_url:'https://kochi-tabi.jp/search_spot_sightseeing.html?id=7996',parking_text:'無料駐車場あり',access:'南国ICから車で約1時間40分。芸西西ICから約1時間10分。',last_verified_at:'2026-10-02',description:'世界ジオパークに認定された室戸の地形・地質・自然・文化を、ガイドと一緒にめぐるツアーです。事前予約や参加条件は最新案内をご確認ください。'},
  'muroto-rockpool':{address:'高知県室戸市室戸岬町1810-2',opening_hours:'予約受付9:00〜17:00',closed_days:'無休',price_text:'体験料金は予約時に確認',phone:'0887-23-1610',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=7998',parking_text:'無料駐車場あり',access:'南国ICから車で約1時間40分。芸西西ICから約1時間10分。',last_verified_at:'2026-10-02',description:'室戸世界ジオパークの海岸で楽しむ磯遊び体験。自然の岩場や生きものを観察しながら、室戸の海を学べるプログラムです。事前予約・注意事項を確認して参加してください。'},
  'muroto-cycle-tour':{address:'高知県室戸市室戸岬町1810-2',opening_hours:'予約受付9:00〜17:00',closed_days:'無休',price_text:'体験料金は予約時に確認',phone:'0887-23-1610',official_url:'https://kochi-tabi.jp/search_spot_sightseeing.html?id=7996',parking_text:'無料駐車場あり',access:'南国ICから車で約1時間40分。芸西西ICから約1時間10分。',last_verified_at:'2026-10-02',description:'室戸世界ジオパーク周辺を自転車でめぐるガイド付きサイクリング体験。海岸景観や大地の成り立ちを楽しみながら走ります。事前予約・参加条件は最新案内をご確認ください。'},
  'withriver-shimanto':{address:'高知県四万十市三里1841',opening_hours:'予約受付9:00〜18:00',closed_days:'木曜日（GW・お盆は無休）',price_text:'おてがるコース・半日コースなど、料金は予約プランにより異なる',phone:'0880-49-0119',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=13594',parking_text:'施設へ確認',access:'高知自動車道・四万十町中央ICから車で約1時間20分。',last_verified_at:'2026-10-02',description:'四万十川でSUPとカヌーを楽しむガイドツアー。短時間のおてがるコースから半日コースまで用意されており、初めての川あそびにも選びやすい体験です。'},
  'garbanzo-yoshino':{address:'高知県長岡郡大豊町西土居1-1',opening_hours:'予約受付8:00〜20:00',closed_days:'夏季無休、冬季不定休',price_text:'SUP・カヌー・カヤック・パックラフト・ラフティング等、料金は各プランで確認',phone:'090-7578-6330',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=16439',parking_text:'施設へ確認',access:'高知自動車道・大豊ICから車で約15分。',last_verified_at:'2026-10-02',description:'吉野川を拠点に、ラフティング、SUP、カヤック、パックラフト、シャワークライミングなど多彩なリバーアクティビティを提供しています。初心者や家族向けのプランもあります。'},
  'tsuno-tea-field':{address:'高知県高岡郡津野町船戸1309-1（集合：集落活動センターふなと）',opening_hours:'開催4月〜7月・10月〜11月。体験は10:00開始の約3時間',closed_days:'悪天候時は開催除外',price_text:'1人8,800円（税込）。15名以下は1人1,100円追加、トゥクトゥク利用は別途9,000円',phone:'0889-55-3755',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=77',parking_text:'集合場所・移動方法は予約時に確認',access:'高知自動車道・須崎東ICから車で約40分。',last_verified_at:'2026-10-02',description:'日本茶インストラクターの案内で津野町桂地区の茶畑を見学し、津野茶の利き茶、オリジナルブレンドティー作り、地元食材のお茶漬けビュッフェまで楽しむ体験です。申込締切は2週間前です。'},
  'soltive-salt':{address:'高知県幡多郡黒潮町灘333',opening_hours:'予約受付9:00〜17:00',closed_days:'不定休',price_text:'体験料金は予約時に確認',phone:'0880-55-3226',official_url:'https://kochi-tabi.jp/search_spot.html?id=8058',parking_text:'施設へ確認',access:'高知自動車道・四万十町中央ICから車で約30分。',last_verified_at:'2026-10-02',description:'天日塩ができるまでの説明を受けたあと、塩のかくはん、採塩、袋詰めまでを体験できます。自分で採った塩は持ち帰ることができます。'},
  'tano-solar-salt':{address:'高知県安芸郡田野町2703-6',opening_hours:'9:00〜（最終入館16:00）',closed_days:'火曜日（祝日の場合は翌平日）、年末年始',price_text:'町外：体験 大人800円・小中学生400円・幼児無料／見学 大人400円・小中学生200円・幼児無料',phone:'0887-38-2390',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=16461',parking_text:'無料。普通車5台・大型1台',access:'南国ICから車で約1時間10分。芸西西ICから約40分。',last_verified_at:'2026-10-02',description:'太陽の熱と風だけでつくる完全天日塩を見学・体験できます。自分で作った塩は持ち帰り可能で、見学・体験とも利用日の10日前までに予約が必要です。'},
  'tosacho-woodwork':{address:'高知県土佐郡土佐町西石原1228（石原コミュニティセンター）',opening_hours:'毎週日曜日（7月〜9月を除く）。9:30集合または12:00集合',closed_days:'7月〜9月、不定休あり',price_text:'1人5,000円（税込、材料・昼食・保険込み）',phone:'0887-72-9328',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=19',parking_text:'石原コミュニティセンター駐車場',access:'高知龍馬空港から車で約1時間10分。大豊ICから約35分。',last_verified_at:'2026-10-02',description:'地元材を使い、釘を使わない木組みで鍋敷きをつくる約3.5時間の体験です。昼食に地元のたけのこ寿司とうどんが付き、申込締切は1週間前です。'},
  'shimanto-traditional-fishing':{address:'高知県四万十市山路',opening_hours:'通年・約90分',closed_days:'なし',price_text:'1組4名まで25,000円。5名以上は1名追加ごとに3,000円',phone:'090-5147-4023（屋形舟さこや）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=109',parking_text:'集合場所の案内に従う',access:'中村駅から車で約10分。Googleマップで「さこやの川漁師体験」を検索。',last_verified_at:'2026-10-02',description:'四万十川の川漁師の案内で、柴漬け漁・投網の体験や実演、櫓を使った舟漕ぎを楽しめる約90分の体験です。1〜7名、1名から催行。ネット予約は開催日の3日前までです。禁漁期間中の生きものはリリースします。'},
  'kuroshio-soba':{address:'高知県幡多郡黒潮町蜷川660-1',opening_hours:'10:00〜16:00の間で約2時間30分（最終開始13:00）',closed_days:'お盆・年末年始',price_text:'料金は予約サイトで確認',official_url:'https://kochi-tabi.jp/search_activity_plan.html?plan_id=0000227166&plan_ota=ha',parking_text:'施設へ確認',access:'黒潮町蜷川地区。詳細は予約時に確認。',last_verified_at:'2026-10-02',description:'蜷川地区で栽培されたそば粉を使い、地元の方と一緒に水回し・練り・そば打ちを体験し、打ちたてのそばを食べます。所要は食事を含め約2時間30分です。'},
  'hinodeya-konnyaku':{address:'高知県長岡郡大豊町立川上名1239-13',opening_hours:'予約受付10:00〜16:00',closed_days:'不定休',price_text:'料金は予約時に確認',phone:'0887-78-0430',official_url:'https://lb1.kochi-tabi.jp/search_spot_activity.html?id=8024',parking_text:'無料駐車場あり',access:'高知自動車道・大豊ICから車で約15分。',last_verified_at:'2026-10-02',description:'吉野川支流の立川川近くにある農家民宿で楽しむこんにゃく作り体験。実施時期は3月下旬〜10月で、事前予約がおすすめです。'},
  'seiran-konnyaku':{address:'高知県高岡郡津野町船戸1321',opening_hours:'10:00〜14:00（約1時間〜1時間30分）',closed_days:'不定休',price_text:'1人1,500円。1名参加の場合は2名分3,000円',phone:'0889-43-9025',official_url:'https://kochi-tabi.jp/search_spot.html?id=8280',parking_text:'無料駐車場あり',access:'高知自動車道・須崎東ICから車で約35分。',last_verified_at:'2026-10-02',description:'地元産こんにゃく芋を使った手作りこんにゃく体験。2名から受付で、3日前までの予約が必要です。できたてを刺身こんにゃくで味わえます。'},
  'qraud-papermaking':{address:'高知県吾川郡いの町鹿敷1226 土佐和紙工芸村内',opening_hours:'予約受付9:00〜16:00',closed_days:'水曜日',price_text:'無地400円〜、草花入り600円、うちわ800円など',phone:'088-892-0127',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=1738',parking_text:'無料。普通車75台・大型5台',access:'伊野ICから車で約20分。JR伊野駅からバス「岩村」下車すぐ。',last_verified_at:'2026-10-02',description:'土佐和紙の紙漉きを体験し、オリジナルのはがきや色紙を作れます。夏はうちわ作りもあり、1名から参加できます。20名以上は予約が必要です。'},
  'kashiwajima-diving-aquas':{address:'高知県幡多郡大月町大字柏島130',opening_hours:'予約受付8:00〜20:00',closed_days:'不定休',price_text:'体験料金・参加条件は予約時に確認',phone:'0880-76-0100',official_url:'https://lb1.kochi-tabi.jp/search_spot.html?id=13939',parking_text:'施設へ確認',access:'四万十町中央ICから車で約2時間。宿毛和田ICから約40分。',last_verified_at:'2026-10-02',description:'柏島の海で楽しむ初心者向けの体験ダイビングです。事前予約が必要な場合や参加条件があるため、予約前に最新案内をご確認ください。'},
  'tatsukushi-diving':{address:'高知県土佐清水市竜串3897',opening_hours:'9:00〜12:00・13:00〜16:00',closed_days:'年中無休',price_text:'体験料金・参加年齢は販売サイトで確認',official_url:'https://kochi-tabi.jp/search_activity_plan.html?plan_id=0000229378&plan_ota=ha',parking_text:'施設へ確認',access:'土佐清水市竜串。詳細は予約時に確認。',last_verified_at:'2026-10-02',description:'竜串のサンゴ群集や熱帯魚を楽しむ体験ダイビング。オリエンテーション、準備、出港・練習・水中ツアー約60分を含め、全体の所要時間は約180分です。'},
  'sakawa-makino-park-guide':{address:'高知県高岡郡佐川町甲1474',opening_hours:'予約受付9:00〜17:00',closed_days:'年末年始',price_text:'料金は予約時に確認',phone:'0889-20-9500',official_url:'https://kochi-tabi.jp/search_ryoma_pass.html?id=16303',parking_text:'周辺駐車場を利用',access:'伊野ICから車で約30分。',last_verified_at:'2026-10-02',description:'牧野富太郎博士ゆかりの牧野公園を、見頃の草花や博士のエピソードを聞きながら散策するガイドツアーです。'},
  'sakawa-makino-sacred-walk':{address:'高知県高岡郡佐川町甲1510（名教館前集合）',opening_hours:'通年開催。開始時間は予約時に調整',closed_days:'不定休',price_text:'1〜5名11,000円／6〜10名22,000円／11〜15名33,000円（税込）',phone:'0889-20-9500',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=73',parking_text:'集合場所周辺の案内を予約時に確認',access:'伊野ICから車で約30分。JR佐川駅から徒歩約5分。',last_verified_at:'2026-10-02',description:'牧野博士の生家周辺から里山・牧野公園まで、植物・文化・地質・博士のエピソードを聞きながら歩く全行程約7km、約4.5時間のツアーです。申込締切は実施日の2週間前です。'},
  'katsurahama-guide':{address:'高知県高知市浦戸6 桂浜公園内（桂浜観光案内所集合）',opening_hours:'土日祝 10:30・13:30の無料定時ガイド。問い合わせ受付9:00〜16:00',closed_days:'12月29日〜1月3日は定時ガイド休止',price_text:'定時ガイド無料。その他の日程は要予約・有料',phone:'088-820-1165',official_url:'https://www.city.kochi.kochi.jp/site/kanko/katsurahamasansakugaido.html',parking_text:'桂浜公園駐車場 約500台',access:'桂浜公園内の桂浜観光案内所集合。',last_verified_at:'2026-10-02',description:'牧野博士ゆかりの海辺の植物や坂本龍馬像などを巡る約60分の散策コース。約90分の桂浜探検コースもあります。'},
  'makino-guide-walk':{address:'高知県高知市五台山4200-6 高知県立牧野植物園',opening_hours:'主に毎月第1日曜・第3土曜 11:00〜。当日9:30から受付',closed_days:'開催日は月ごとに異なる',price_text:'参加無料（別途入園料：一般850円、高校生以下無料）',phone:'088-882-2601',official_url:'https://www.makino.or.jp/event/detail.php?id=1139',parking_text:'無料駐車場あり',access:'高知ICから車で約20分。JR高知駅からMY遊バスで約30分。',last_verified_at:'2026-10-02',description:'園地管理の職員や研究員などが、それぞれの専門性を活かして見頃の植物や園の魅力を紹介するガイドウォーク。月2回程度、予約不要・当日先着受付で開催されます。'},
  'shimanto-botanical-dye':{address:'高知県四万十市田出ノ川24 四万十カヌーとキャンプの里かわらっこ',opening_hours:'体験10:00〜15:00／予約受付8:00〜18:00',closed_days:'10〜6月は月曜日（祝日の場合は翌日）、7〜9月は無休、年末年始休み',price_text:'料金・参加年齢は予約サイトで確認',phone:'0880-31-8400',official_url:'https://kochi-tabi.jp/search_activity_plan.html?plan_id=0000227437&plan_ota=ha',parking_text:'施設駐車場を利用',access:'四万十町中央ICから車で約1時間15分。',last_verified_at:'2026-10-02',description:'四万十川流域に自生する植物を煮出した染料を使い、バンダナやストールに模様を付けて染め上げる約60〜90分の体験です。完成した作品は持ち帰れます。'},
  'mihara-rural-stay':{address:'高知県幡多郡三原村下長谷1110-1',opening_hours:'1泊2日の宿泊体験。開始・終了時刻は予約時に確認',closed_days:'不定休',price_text:'料金・受入条件は予約サイトで確認',phone:'0880-46-2505',official_url:'https://lb1.kochi-tabi.jp/search_activity_plan.html?plan_id=0000228266&plan_ota=ha',parking_text:'宿の駐車場・集合方法は予約時に確認',access:'四万十町中央ICから車で約1時間30分。',last_verified_at:'2026-10-02',description:'自然に囲まれた農家民宿で1泊2日の田舎暮らしを体験。季節によりタケノコ・山菜収穫、川エビ獲り、ツガニ籠漁、畑仕事、星空観察、鶏やヤギの世話などを楽しめ、夕食・朝食も付きます。'},
  'susaki-warauma':{address:'高知県須崎市青木町1-16 すさきまちかどギャラリー',opening_hours:'9:00〜17:00',closed_days:'月曜日（祝日の場合は翌日）、12月29日〜1月3日',price_text:'1,000円',phone:'050-8803-8668',official_url:'https://lb2.kochi-tabi.jp/search_spot_sightseeing.html?id=16232',parking_text:'周辺駐車場を利用',access:'須崎中央ICから車で約5分。',last_verified_at:'2026-10-02',description:'須崎をはじめ高知県内に伝わる七夕飾り「わら馬」を作る通年のワークショップです。3日前までの予約が必要です。'},
  'tosa-kokubunji-culture':{address:'高知県南国市国分546 土佐国分寺',opening_hours:'通年。開始時間は予約時に調整',closed_days:'年末年始',price_text:'1人4,000円（税込）',phone:'088-802-5050（物部川DMO協議会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=112',parking_text:'土佐国分寺の駐車場を利用',access:'JR後免駅から車で約5分、徒歩約40分。',last_verified_at:'2026-10-02',description:'四国八十八ヶ所第29番札所の土佐国分寺で、本堂内部の見学、約1時間の瞑想体験、約1時間の抹茶体験を行う約2時間のプログラムです。最少催行10名、申込締切は10日前です。'},
  'ashizuri-secret-guide':{address:'高知県土佐清水市足摺岬647-1（足摺岬市営駐車場集合）',opening_hours:'8:30集合〜11:30頃（約3時間）',closed_days:'年末年始・お盆時期',price_text:'8名まで7,500円／9〜16名15,000円／17〜24名22,500円。遊覧船2,500円/人は別途',phone:'0880-87-9500（竜串ビジターセンターうみのわ）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=84',parking_text:'足摺岬市営駐車場を利用',access:'四万十市中村から車で約1時間。',last_verified_at:'2026-10-02',description:'遊覧船で足摺岬の断崖や洞窟・奇岩を海から眺め、アコウの巨木、松尾天満宮、唐人岩巨石群を地元ガイドと巡る約3時間の自然体験です。申込締切は3日前。荒天や波高により船が欠航する場合があります。'},
  'mihara-slow-cycling':{address:'高知県幡多郡三原村上長谷884-1 農家民宿 今ちゃん',opening_hours:'6:30・7:00・7:30・8:00開始（通年）',closed_days:'開催除外日なし',price_text:'大人2,500円（高校生以上）／小人1,000円（小学3年生〜中学生）',phone:'0880-31-7839',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=64',parking_text:'集合場所の案内を予約時に確認',access:'四万十町中央ICから車で約1時間30分。土佐くろしお鉄道 平田駅から車で約10分。',last_verified_at:'2026-10-02',description:'英国製折りたたみ自転車ブロンプトンで、三原村の田んぼ道や歴史スポットを巡る約6km・約1時間30分の朝サイクリング。三原米のおむすびを楽しみ、申込締切は2日前です。'},
  'ashizuri-ebike':{address:'高知県土佐清水市足摺岬（あしずり温泉郷の宿泊ホテル等に集合）',opening_hours:'10月〜6月、8:30〜15:30頃（約7時間）',closed_days:'火曜日・水曜日',price_text:'1名参加27,500円／2名以上22,000円（1人・税込）',phone:'090-1701-4738（Ta vie x Sa vie）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=83',parking_text:'集合場所・駐車方法は予約時に確認',access:'四万十町中央ICから車で約2時間。中村駅から路線バスで約1時間50分。',last_verified_at:'2026-10-02',description:'電動アシスト付きE-bikeで足摺半島を約37km走り、松尾集落、臼碆海岸・竜宮神社、大浜、市街地、鹿島神社、窪津漁港、足摺岬展望台などを巡るガイドツアー。昼食・おやつ付きで、申込締切は1週間前です。'},
  'shimanto-observatory':{address:'高知県四万十市西土佐用井1100',opening_hours:'20:00〜21:00（19:50集合）／予約受付7:00〜22:00',closed_days:'水曜日',price_text:'料金は予約サイトで確認',phone:'0880-52-2225（ホテル星羅四万十）',official_url:'https://kochi-tabi.jp/search_spot_inn.html?id=8048',parking_text:'ホテル星羅四万十の駐車場を利用',access:'四万十町中央ICから車で約1時間。ホテル星羅四万十1階フロント前集合。',last_verified_at:'2026-10-02',description:'四万十天文台の反射式望遠鏡を使い、専門員が季節の星座や天体を案内する約60分の天体観望会です。前日までの予約制です。'},
  'tatsukushi-glassboat':{address:'高知県土佐清水市竜串19-10',opening_hours:'8:00〜17:00（12〜2月は16:30まで）',closed_days:'無休',price_text:'一般2,000円／小人1,000円。15名以上は1割引',phone:'0880-85-0037',official_url:'https://kochi-tabi.jp/search_spot.html?id=53',parking_text:'無料。普通車70台・大型2台',access:'四万十町中央ICから車で約1時間40分。中村駅から車で約50分。',last_verified_at:'2026-10-02',description:'船底がガラス張りのグラスボートで、竜串のサンゴや熱帯魚を観察できます。見残し湾のシコロサンゴなど、海中景観を船上から楽しめます。'},
  'tatsukushi-minokoshi-tour':{address:'高知県土佐清水市竜串19-10',opening_hours:'9:10〜15:10（40分間隔で運航）',closed_days:'不定休',price_text:'料金は販売サイトで確認',phone:'0880-85-0037',official_url:'https://kochi-tabi.jp/search_activity_plan.html?plan_id=0000227529&plan_ota=ha',parking_text:'竜串観光汽船の駐車場を利用',access:'四万十町中央ICから車で約1時間40分。',last_verified_at:'2026-10-02',description:'グラスボートで竜串海域公園の海中を観賞し、見残し海岸に上陸してガイドと奇岩を巡る約90分のツアーです。'},
  'otsuki-glassboat-yubari':{address:'高知県幡多郡大月町周防形244-3',opening_hours:'9:00〜16:00',closed_days:'無休（天候状況等で中止の場合あり）',price_text:'体験料金は現地・予約時に確認',phone:'070-3961-9771（6〜8月）／090-8972-7033（9〜5月）',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=16350',parking_text:'施設へ確認',access:'四万十町中央ICから車で約2時間。宿毛和田ICから約40分。',last_verified_at:'2026-10-02',description:'グラスボートからサンゴ群生や海の生きものを観察します。6〜8月は柏島、9〜5月は周防形で実施されます。'}
  ,'kochi-market-fruit-basket':{address:'高知県高知市弘化台12-12 高知市卸売市場',opening_hours:'毎週土曜 7:00集合〜約4.5時間',closed_days:'市場・講師都合により実施不可日あり',price_text:'2名 27,500円／3名 21,000円／4名 17,000円（公式掲載）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=49',parking_text:'市場の案内に従う',access:'JR高知駅から車で約15分。',last_verified_at:'2026-10-02',description:'高知市卸売市場の鮮魚・塩干部を見学し、青果部で果物のセリを見学。市場朝食の後、高知特産の虎斑竹を使った竹かご作りと旬の果物を盛り付けたフルーツバスケット作りを体験します。申込締切は7日前です。'},
  'shimanto-sada-cycling':{address:'高知県四万十市駅前町8-3 四万十市観光協会',opening_hours:'通年 13:00〜16:00（約3時間）',closed_days:'なし（雨天・増水等で中止）',price_text:'1人5,500円（税込）',phone:'0880-35-4171',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=58&sType=trip',parking_text:'集合場所周辺を利用',access:'土佐くろしお鉄道 中村駅から徒歩すぐ。',last_verified_at:'2026-10-02',description:'案内人とレンタサイクルで赤鉄橋、佐田沈下橋、三里沈下橋をめぐる約20km・3時間のツアーです。対象は7歳以上で20インチの自転車に乗れる方。申込締切は1週間前です。'},
  'akano-shishimai':{address:'高知県安芸市赤野甲165 大元神社',opening_hours:'1〜5月・11〜12月の土日祝中心、約2時間',closed_days:'平日',price_text:'20〜30名 1人6,000円／31〜40名 1人5,000円（税込）',phone:'080-8631-7754',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=89',parking_text:'現地案内に従う',access:'芸西西ICから車で約10分。高知新港から車で約30分。',last_verified_at:'2026-10-02',description:'600年以上の歴史を持つ赤野獅子舞を大元神社で鑑賞し、演者の準備や休憩時間に保存会メンバーと交流する約2時間の体験です。最少催行20名、申込締切は1か月前です。雨天時は赤野地区公民館で実施されます。'},
  'shimanto-fish-auction-lunch':{address:'高知県四万十市佐岡499-1 幡多公設地方卸売市場',opening_hours:'毎月第4土曜（7・8月は第3土曜）11:00までに入場〜13:00',closed_days:'開催日以外',price_text:'1人2,200円（税込・同額クーポン付き）',phone:'0880-35-4171',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=47',parking_text:'市場の案内に従う',access:'黒潮拳ノ川ICから車で約45分。中村駅から車で約5分。',last_verified_at:'2026-10-02',description:'一般参加の魚の模擬競りに参加し、落札した魚を刺身にしたり、場内のカツオのタタキやウナギなどを購入して味わう約1.5〜2時間の市場体験です。申込締切は2週間前です。'},
  'shimanto-yakatabune-cafe':{address:'高知県四万十市田出ノ川846-1 屋形船なっとく',opening_hours:'土日祝・GW・夏休みの毎日 9:00・15:00出航',closed_days:'12月27日〜1月4日',price_text:'大人2,800円／小人1,800円（税込）',phone:'0880-38-2918',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=48',parking_text:'施設へ確認',access:'中村駅から車で約20分。',last_verified_at:'2026-10-02',description:'四万十川の屋形船で約40分遊覧しながら、四万十のご当地コーヒーまたは紅茶と季節のスイーツを楽しむ約50分の水上カフェです。最少催行2名、申込締切は2日前です。'},
  'kaiyodo-nankoku-workshop':{address:'高知県南国市大そね甲1623-3',opening_hours:'体験プログラムにより異なる。予約受付10:00〜18:00',closed_days:'火曜日（祝日の場合は翌日）',price_text:'体験ごとに異なるため公式サイトで確認',phone:'088-864-6777',official_url:'https://lb1.kochi-tabi.jp/search_spot_activity.html?id=15827',parking_text:'無料駐車場あり',access:'南国ICから車で約10分。高知龍馬空港から車で約10分。',last_verified_at:'2026-10-02',description:'フィギュア色塗り、ジオラマ作り、ジオラマ背景作りなどを楽しめるものづくり体験です。予約優先で、定員に達するまで当日受付も可能です。'},
  'obuchi-kokedama':{address:'高知県土佐郡土佐町大渕284',opening_hours:'9:00〜18:00',closed_days:'不定休',price_text:'3,000円',phone:'090-6241-1641',official_url:'https://lb2.kochi-tabi.jp/search_spot_sightseeing.html?id=16280',parking_text:'無料3台',access:'大豊ICから車で約35分。',last_verified_at:'2026-10-02',description:'好きな苗を選んでオリジナルの苔玉を作る体験です。桜・紫陽花・藤などが楽しめる里山の散策ガイドも付いています。'},
  'tosa-shio-no-michi-walk':{address:'高知県香美市物部町周辺（集合場所はコースにより異なる）',opening_hours:'9:00〜17:00受付。体験例は9:30〜14:00頃',closed_days:'不定休',price_text:'3〜5名10,000円/人、6〜10名9,000円/人',phone:'090-7622-1112',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=9',parking_text:'集合場所の案内に従う',access:'高知龍馬空港から車で約50分。JR土佐山田駅から車で約40分。',last_verified_at:'2026-10-02',description:'物部から赤岡へ塩を運んだ歴史道をガイドと歩く約6時間のプログラム。約6kmを基本に複数コースがあり、竹べんとう・お茶・保険を含みます。申込締切は7日前です。'},
  'takemasa-sodabushi':{address:'高知県土佐清水市中浜236',opening_hours:'9:00〜15:00の希望時間帯（体験約60分）',closed_days:'火曜日・水曜日',price_text:'中学生以上2,000円／小学生以下1,500円／未就学児は見学無料',phone:'0880-82-9208',official_url:'https://kochi-tabi.jp/search_spot_activity.html?id=16436',parking_text:'施設へ確認',access:'四万十町中央ICから車で約1時間40分。',last_verified_at:'2026-10-02',description:'戦前から残る節納屋で宗田節の製造を見学し、宗田節削りやMYだし醤油ボトル作りを楽しむ約60分の体験です。最少催行2名で、天候や漁獲状況により内容が変わる場合があります。'},
  'niyodogawa-seicho-paper':{address:'高知県吾川郡仁淀川町寺村・岩戸地区',opening_hours:'ガイドは通年。クラフト体験は指定日に要予約',closed_days:'開催日は予約時に確認',price_text:'1〜2名6,000円。以降1名追加ごとに3,000円',official_url:'https://doppuri.kochi-tabi.jp/guide/course_detail.html?guide_id=5&id=81',parking_text:'集合場所の案内を予約時に確認',access:'仁淀川町内。詳細な集合場所は予約時に確認。',last_verified_at:'2026-10-02',description:'花の里公園から地域と和紙の歴史を聞きながら、現在1軒となった和紙工房へ歩くガイドツアーです。ガイドは約90分、クラフト体験を含める場合は約120分。申込締切は3日前17時までです。'},
  'umaji-yuzu-forest-ebike':{address:'安田町多目的交流センターなかやま集合',opening_hours:'通年。9:30集合・10:00出発〜15:00頃解散',closed_days:'開催日は予約時に確認',price_text:'1人5,000円',official_url:'https://doppuri.kochi-tabi.jp/guide/course_detail.html?guide_id=1&id=6',parking_text:'集合場所の案内を予約時に確認',access:'安田川沿いの旧森林鉄道跡から馬路村方面を巡るコース。',last_verified_at:'2026-10-02',description:'E-bikeで安田川沿いの旧魚梁瀬森林鉄道跡、隧道や橋梁、馬路温泉、ゆずの森加工場などを巡る約25km・約5時間のガイドツアーです。通年実施、定員5名・最少催行3名、5日前までの予約制です。'},
  'yoshino-headwaters-track-walk':{address:'高知県吾川郡いの町越裏門340-8 集落活動センター「氷室の里」',opening_hours:'4月・11月 9:00〜14:00（約5時間）',closed_days:'開催月以外。雨天中止',price_text:'1人8,400円（税込）',phone:'088-893-1211（いの町観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=72',parking_text:'集合場所の案内に従う',access:'伊野ICから車で約1時間30分。',last_verified_at:'2026-10-02',description:'吉野川源流域に残る森林軌道跡を地元ガイドと歩き、散策後は「氷室の里」で地元の方と山菜の天ぷらを作って地産地消ランチを楽しむ約5時間の体験です。定員12名・最少催行7名、申込締切は10日前です。'},
  'monobe-izanagi-stay':{address:'高知県香美市物部町大栃1469-2 まきの宿',opening_hours:'通年。1日目16:00チェックイン〜2日目10:00チェックアウト',closed_days:'宿に準ずる',price_text:'基本料金 平日12,000円＋夕食代',phone:'0887-53-9480',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=10',parking_text:'宿の案内を確認',access:'南国IC・高知龍馬空港から車で約45分。JR土佐山田駅からバスと徒歩で約45分。',last_verified_at:'2026-10-02',description:'築80年の古民家「まきの宿」に泊まり、物部の民間信仰「いざなぎ流」で使う御幣切りを体験。翌朝は宿主の案内で大栃朝散歩を楽しみます。1泊2日、1〜5名で利用できます。'},
  'shimanto-yairocho-walk':{address:'高知県高岡郡四万十町大正31-1 四万十ヤイロチョウの森ネイチャーセンター',opening_hours:'7〜9月の土・日 10:00〜13:30頃（2026年分は終了）',closed_days:'2026年分は終了。次回開催日は公式情報を確認',price_text:'ガイド料33,000円＋入館料・施設使用協力金・保険料等',phone:'0880-29-6004（四万十町観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=79&sType=trip',parking_text:'ネイチャーセンター等の案内に従う',access:'四万十町中央ICから車で約30分。',last_verified_at:'2026-10-02',description:'ネイチャーセンターで四万十の自然や野鳥を学んだ後、調査員の案内で森林鉄道軌道跡を往復約4km歩き、ヤイロチョウの生態や野鳥撮影について学ぶ体験です。開催は7〜9月の土日で、2026年分は終了しています。最少催行5名、申込締切は2週間前です。'},
  'aki-shirasu-fisher-tour':{address:'高知県安芸市津久茂町2 安芸漁業協同組合駐車場集合',opening_hours:'2026年4月4日・4月11日 6:30〜11:30（2026年分は終了）',closed_days:'2026年分は終了。次回開催日は未定',price_text:'高校生以上10,000円／中学生5,000円／小学生3,000円',phone:'0887-35-1122（安芸市観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=6',parking_text:'安芸漁業協同組合駐車場を利用',access:'高知龍馬空港・南国ICから車で約1時間。',last_verified_at:'2026-10-02',description:'早朝の安芸漁港から遊漁船で土佐湾へ出て約1時間半の釣りを体験し、帰港後は漁港のせり見学、じゃこゼミナール、釜あげちりめん丼まで楽しむ約5時間のツアーです。定員16名・最少催行5名。2026年の開催は4月4日・11日で終了しており、次回日程は未発表です。'},
  'ino-cosplay-photo-tour':{address:'高知県吾川郡いの町新町 JR伊野駅集合',opening_hours:'通年 9:00〜16:50（約8時間）',closed_days:'設定なし（実施可否は予約時に確認）',price_text:'4名18,000円／5名15,000円／6名13,000円／7名11,000円／8名9,500円（1人・税込）',phone:'080-8631-7754（宮地観光サービス）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=71',parking_text:'公共交通推奨。車の場合は周辺駐車場を確認',access:'伊野ICから車で約10分。JR高知駅から列車で約25分。',last_verified_at:'2026-10-02',description:'JR伊野駅を出発し、椙本神社、琴風亭、柳瀬小学校などでコスプレ撮影を楽しむ約8時間のフォトツアーです。更衣室、専用車、軽食、ツアー管理者の同行を含み、定員8名・最少催行4名、申込締切は2か月前です。'},
  'kochi-kimono-ozashiki':{address:'高知県高知市南はりまや町1-16-5 和の文化発信基地aiiro集合',opening_hours:'通年 10:30〜14:00（約3時間30分）',closed_days:'月曜日',price_text:'23,000円/人（税込）※通訳ガイド別途15,000円',phone:'080-8631-7754（宮地観光サービス）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=39',parking_text:'周辺駐車場を利用',access:'高知ICから車で約15分。JR高知駅から車で約5分。はりまや橋観光ターミナルから徒歩約4分。',last_verified_at:'2026-10-02',description:'着物に着替えて料亭濱長へ移動し、特別ランチと飲み放題を楽しみながら、土佐芸妓・舞妓または土佐お座敷ガイドと、べく杯・箸拳・菊の花などのお座敷遊びを体験します。定員4〜10名、4日前15時締切です。'},
  'hanpeita-harimaya-guide':{address:'高知県高知市上町2-6-33 龍馬の生まれたまち記念館周辺',opening_hours:'通年・約120分',closed_days:'実施日は予約時に確認',price_text:'大人700円／中高生500円／小学生以下無料',official_url:'https://doppuri.kochi-tabi.jp/guide/course_detail.html?guide_id=6&id=21',parking_text:'集合場所周辺の駐車場を利用',access:'高知市中心部。詳細な集合場所は予約時に確認。',last_verified_at:'2026-10-02',description:'龍馬の生まれたまち記念館から坂本龍馬誕生地、武市半平太ゆかりの史跡、よさこい情報交流館、はりまや橋、ひろめ市場などを約2.7km歩くガイドコースです。路面電車に乗り、よさこい踊りも体験できます。参加希望日の3日前15時までに予約が必要です。'},
  'gomen-nahari-fruit-train':{address:'高知県南国市駅前町2丁目4 土佐くろしお鉄道 後免駅',opening_hours:'通年。後免駅10:43発〜安芸駅11:36着の例あり',closed_days:'なし',price_text:'専用車両基本料金＋1人1,700円のフルーツセット等。区間・人数で変動',phone:'088-802-5050（物部川DMO協議会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=45',parking_text:'駅周辺駐車場を確認',access:'南国ICから車で約10分。高知龍馬空港から約15分。',last_verified_at:'2026-10-02',description:'専用車両とオープンデッキ車両を楽しみながら、沿線のフルーツを味わう約1時間の列車体験です。通常ダイヤ連結は1か月前、臨時便は2か月前までの申込が必要です。'},
  'kure-fisher-town-fullcourse':{address:'高知県高岡郡中土佐町久礼8645-2 道の駅なかとさ集合',opening_hours:'4月〜11月 6:10〜10:30（約4時間20分）',closed_days:'水曜・日曜・GW・お盆・シルバーウィーク',price_text:'6,600円/人（税込）',phone:'0889-59-2006（なかとさ観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=26',parking_text:'道の駅なかとさ等を利用',access:'高知龍馬空港から車で約60分。高知ICから約45分。',last_verified_at:'2026-10-02',description:'久礼港のカツオの競り見学、小川製塩所での天日塩づくり、久礼大正町市場散策、田中鮮魚店でのカツオ藁焼きと朝食を組み合わせた約4時間20分の体験です。定員10名・最少催行4名、申込締切は5日前です。'},
  'bentenza-backstage-experience':{address:'高知県香南市赤岡町795 弁天座',opening_hours:'施設9:00〜17:00。体験実施時間は予約時に確認',closed_days:'月曜日（祝日の場合は翌日）',price_text:'予約プランにより異なるため予約サイトで確認',phone:'0887-57-3060',official_url:'https://kochi-tabi.jp/search_activity_plan.html?category=1&category=2&category=3&category=4&keyword=%E6%AD%B4%E5%8F%B2',parking_text:'無料駐車場あり',access:'香南のいちICから車で約5分。あかおか駅から徒歩約7分。',last_verified_at:'2026-10-02',description:'本格的な芝居小屋「弁天座」の舞台裏をスタッフと見学し、廻り舞台やセリなどを体験できる予約プランです。施設自体は9:00〜17:00、月曜休館（祝日の場合は翌日）です。'},
  'uranouchi-akame-fishing':{address:'高知県須崎市浦ノ内塩間49-3 深浦漁業協同組合前',opening_hours:'5月1日〜11月30日 6:45〜14:00（約7時間）',closed_days:'開催除外日なし',price_text:'2名以上25,000円/人。1名参加は別途5,000円',phone:'0889-40-0315（須崎市観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=42',parking_text:'集合場所の案内に従う',access:'高知龍馬空港から車で約45分。須崎東ICから約20分。',last_verified_at:'2026-10-02',description:'浦ノ内湾の釣筏でインストラクターのサポートを受けながらアカメを狙う約7時間の釣り体験です。渡船、釣具一式、餌、ライフジャケット等を含み、1名から参加可能。申込締切は7日前です。'},
  'tsuno-tea-fullcourse':{address:'高知県高岡郡津野町船戸1309-1 集落活動センターふなと',opening_hours:'5月〜11月 9:00〜14:00（約5時間）',closed_days:'8〜9月・悪天候時',price_text:'6,600円/人（税込）',phone:'0889-55-3755（一般社団法人奥四万十高知）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=76',parking_text:'集合場所の案内に従う',access:'須崎中央ICから車で約30分。',last_verified_at:'2026-10-02',description:'桂地区の茶畑を地域ガイドと歩き、茶摘み、茶揉み、摘んだ茶葉の実食、地元食材の田舎ごはんまで楽しむ約5時間の体験です。定員40名・最少催行10名、申込締切は2週間前です。'},
  'kiriyama-roasting-teacan':{address:'高知県高岡郡日高村柱谷382-23 霧山茶園',opening_hours:'通年 9:00〜11:30 または 13:30〜16:00',closed_days:'日曜日、12月25日〜1月12日、お盆',price_text:'5,500円/人（税込）',phone:'0889-20-9511（仁淀ブルー観光協議会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=54',parking_text:'霧山茶園の案内に従う',access:'伊野ICから車で約20分。',last_verified_at:'2026-10-02',description:'和紙で茶缶や袋を作り、茶農家から焙煎の違いを学びながら、自分好みにほうじ茶を手焙煎して持ち帰る約2時間30分の体験です。定員8名・最少催行2名、申込締切は5日前です。'},
  'yusuhara-china-paint':{address:'高知県高岡郡梼原町太郎川3799-3 チャイナペイント工房遊美庵',opening_hours:'通年・約2時間',closed_days:'講師スケジュールによる',price_text:'3,000円/人（税込）',phone:'0889-65-1187（ゆすはら雲の上観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=56',parking_text:'現地の案内に従う',access:'須崎中央ICから車で約1時間。冬期会場は梼原町川西路2260-3。',last_verified_at:'2026-10-02',description:'プロの指導で21cmプレートまたはマグカップに自由に絵付けする約2時間の体験です。通常は茅葺き古民家、11月〜3月頃は講師アトリエで実施。1週間前締切で、焼成後の完成は約2週間後です。'},
  'tosayama-haiku':{address:'高知県高知市土佐山東川661 オーベルジュ土佐山',opening_hours:'通年 9:00〜15:00頃（約6時間）',closed_days:'木曜日・年末年始',price_text:'2〜3名46,000円/人、4〜8名39,000円/人',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=102',parking_text:'高知市内宿泊施設または高知新港から往復タクシー送迎',access:'JR高知駅から車で約30分。高知空港から約60分。',last_verified_at:'2026-10-02',description:'英語俳句のレクチャー、里山での吟行、作句、季節の会席ランチまで楽しむ約6時間のプレミアム体験です。土佐和紙ノートのお土産付き。定員2〜8名、申込締切は2週間前で、日本語実施にも対応します。'},
  'ioki-morning-market-tour':{address:'高知県安芸市伊尾木177-9 伊尾木洞第一駐車場',opening_hours:'通年 8:30〜10:30（約120分）',closed_days:'年末年始',price_text:'大人2,800円（1人参加5,000円）／小学生2,400円／未就学児無料',phone:'0887-35-1122（安芸市観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=4',parking_text:'伊尾木洞第一駐車場を利用',access:'高知龍馬空港・南国ICから車で約1時間。',last_verified_at:'2026-10-02',description:'朝8:30から地元ガイドと伊尾木洞を約1時間30分散策し、その後、安芸駅ぢばさん市場でスタッフの案内を受けながら地元野菜や鮮魚を見て回る約2時間のツアーです。柚子ドリンク試飲、ヘルメット・長靴レンタル、保険を含みます。定員1〜10名、4日前締切です。'},
  'yodo-line-cycle-rafting':{address:'高知県高岡郡四万十町琴平町16 JR窪川駅集合',opening_hours:'4月〜10月 9:30〜16:30頃（約7時間）',closed_days:'11月〜3月',price_text:'41,000円/人（税込）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=46&sType=trip',parking_text:'窪川駅周辺の駐車場を確認',access:'JR高知駅から特急で約1時間。高知ICから車で約1時間。',last_verified_at:'2026-10-02',description:'窪川駅からJR予土線で土佐昭和駅へ向かい、四万十川沿いを往復約14kmサイクリング。昼食後はラフティングを楽しみ、タクシーで窪川駅へ戻る約7時間のツアーです。定員4名・最少催行2名、7日前締切。料金にはレンタサイクル、英語ガイド、ラフティング、鉄道片道運賃、保険を含みます。'},
  'shimizu-saba-town-tour':{address:'高知県土佐清水市戎町3-1 高知県漁協清水統括支所前',opening_hours:'通年 9:30〜11:30頃（約120分）',closed_days:'火・水・土曜、12月29日〜1月3日、5月2〜4日、8月13〜15日',price_text:'2〜4名6,300円/人／10〜20名6,100円/人（5〜9名は応相談）',phone:'0880-87-9500（竜串ビジターセンターうみのわ）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=30&sType=trip',parking_text:'集合場所周辺の案内に従う',access:'四万十町中央ICから車で約1時間30分。中村駅からバスで約55分。',last_verified_at:'2026-10-02',description:'土佐清水漁協の活魚水槽や市場を見学し、漁師町を約1km食べ歩き。ところてん・いももち、ペラ焼き、天ぷらなどを味わった後、さばの刺身定食を楽しむ約2時間のツアーです。最少催行2名。2〜4名は3日前、10〜20名は1週間前締切です。'},
  'kuroshio-earthing-stay':{address:'高知県幡多郡黒潮町入野1966 黒潮の家',opening_hours:'通年。16:00チェックイン〜翌11:00チェックアウト',closed_days:'年末年始、GW、お盆休み',price_text:'1名21,300円/人／2名以上15,300円/人（休前日は追加料金あり）',phone:'080-3923-0696',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=37',parking_text:'黒潮の家の案内に従う',access:'土佐入野駅から徒歩約6分。四万十町中央ICから車で約45分。',last_verified_at:'2026-10-02',description:'一棟貸しの「黒潮の家」に泊まり、朝の渚散歩とストレッチ、薪ストーブサウナ、地元食材の土鍋料理を楽しむ1泊2日の滞在型体験です。1〜10名、1名から催行、2週間前締切。雨天時は室内プログラムに変更されます。'},
  'niyodo-water-seitai':{address:'高知県吾川郡いの町鹿敷1226 QRAUD',opening_hours:'通年・約1時間30分',closed_days:'1月・2月は要相談。荒天時は変更・中止の場合あり',price_text:'1名8,500円／2名5,000円/人／3名4,000円/人／4名3,500円/人',phone:'090-2152-1341',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=21',parking_text:'QRAUD駐車場を利用',access:'伊野ICから車で約20分。高知龍馬空港から約50分。',last_verified_at:'2026-10-02',description:'QRAUD前の仁淀川の浅瀬にベッドを設置し、仁淀ブルーを眺めながらオーダーメイドの整体を受ける約90分の体験です。1組限定・最大4名、前日17時締切。施術後は限定コーヒーのドリップバッグ付きです。'},
  'iwayagawa-irimochi-hike':{address:'高知県吾川郡仁淀川町別枝 秋葉広場観光駐車場',opening_hours:'通年。10:00〜13:00の間で開始、約120分',closed_days:'荒天・降雪時は中止',price_text:'1名9,500円／2名以上5,000円/人',phone:'090-8696-7707',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=23&sType=trip',parking_text:'秋葉広場観光駐車場を利用',access:'伊野ICから車で約1時間30分。',last_verified_at:'2026-10-02',description:'岩屋川渓谷の約1kmの遊歩道を地元ガイドと歩き、吊り橋や巨岩の景観を楽しんだ後、渓谷茶屋で郷土茶菓いりもちとお茶を味わう約2時間の体験です。定員1〜8名、10日前締切です。'},
  'shimanto-fisher-firefly':{address:'高知県四万十市田出ノ川24 カヌーとキャンプの里かわらっこ',opening_hours:'2027年5月中旬〜下旬予定。1日目15:00〜20:30、2日目9:00〜10:30',closed_days:'開催日以外',price_text:'4名21,400円/人、5名20,000円/人、6名19,100円/人、7名18,600円/人、8名16,500円/人',phone:'0880-35-4171（四万十市観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=34',parking_text:'かわらっこの案内に従う',access:'四万十町中央ICから車で約1時間15分。中村駅から車で約30分。',last_verified_at:'2026-10-02',description:'川漁師と伝統漁法の仕掛け作りを体験し、四万十牛BBQの後、夜は遊覧船でホタルを観賞。翌朝は漁具を回収し、獲れた生きものの観察や投網体験などを行う2日間のプログラムです。4〜8名、2週間前締切。宿泊手配は料金に含まれません。'},
  'sakawa-black-tea-tasting':{address:'高知県高岡郡佐川町中組 龍王公園集合',opening_hours:'11月〜3月 13:15〜16:00（約2時間30分）',closed_days:'年末年始',price_text:'5,500円/人（税込）',phone:'0889-20-9511（仁淀ブルー観光協議会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=51',parking_text:'龍王公園集合。自家用車で農園へ移動',access:'伊野ICから車で約30分。',last_verified_at:'2026-10-02',description:'佐川町の紅茶農家から国産紅茶の歴史を学び、6品種を3回ずつテイスティング。気に入った紅茶と地元スイーツのペアリングを楽しむ体験です。定員6名・最少催行2名、申込締切は2週間前です。'},
  'ikegawa-afternoon-tea':{address:'高知県吾川郡仁淀川町土居甲695-4 池川茶園 工房Café',opening_hours:'10月〜6月 11:00〜15:00（毎時00分開始・約1時間）',closed_days:'年末年始・GW',price_text:'2,900円/人（税込）',phone:'0889-20-9511（仁淀ブルー観光協議会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=52',parking_text:'池川茶園 工房Caféの案内に従う',access:'伊野ICから車で約50分。',last_verified_at:'2026-10-02',description:'仁淀川支流の土居川を眺めながら、その日おすすめの土佐茶2種と土佐茶を使った手作りスイーツ5種を3段スタンドで味わう約1時間の体験です。定員8名・最少催行2名、5日前締切です。'},
  'motoyama-vegan-farm':{address:'高知県長岡郡本山町本山582-2 土佐れいほく観光協議会駐車場集合',opening_hours:'通年 13:30〜20:00頃（約6時間30分）',closed_days:'不定休',price_text:'25,000円/人（税込）',phone:'080-3608-2208（めぐみめぐる農園）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=13',parking_text:'集合後、先導車に続いて自家用車で移動',access:'高知龍馬空港から車で約50分。大豊ICから約20分。',last_verified_at:'2026-10-02',description:'棚田の農園で四季の野菜をプチ収穫し、ぽっちり堂でティータイムと精進出汁教室、その後ビーガン和食ディナーを楽しむ約6時間30分の体験です。2〜6名・最少催行2名、1か月前締切。現在はぽっちり堂宿泊者のみ対応です。'},
  'asemikawa-ebike':{address:'高知県長岡郡本山町吉野ヲモヤ152-3 吉野川クライミングセンター駐車場',opening_hours:'通年の土日祝 8:45〜12:30（約3時間45分）',closed_days:'月〜金、荒天・積雪・路面凍結時',price_text:'8,000円/人（税込）',phone:'080-1460-1827（あひるの森アウトドアツアーズ）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=14',parking_text:'吉野川クライミングセンター駐車場を利用',access:'高知龍馬空港から車で約1時間。大豊ICから約25分。',last_verified_at:'2026-10-02',description:'電動アシスト自転車で汗見川沿いを往復約25km走り、水力発電所跡、巨岩、枕状溶岩などをガイドと巡ります。終了後は地元食堂で昼食。2〜6名・最少催行2名、3日前締切。高校生以上・身長150cm以上が参加条件です。'},
  'tosa-mokumen-factory':{address:'高知駅・高知龍馬空港・高知港のいずれか集合',opening_hours:'通年の平日のみ。工場見学約1時間＋片道タクシー30〜50分',closed_days:'土曜・日曜・祝日',price_text:'16,000円〜/人（税込・2名以上。乗車場所により変動）',phone:'088-852-1237（土佐市観光有限会社）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=108',parking_text:'タクシー送迎プランのため集合場所へ直接集合',access:'高知駅・高知港から工場まで車で約30分、高知龍馬空港から約50分。',last_verified_at:'2026-10-02',description:'高知県産木材を約0.1mmに削る天然緩衝材「もくめん」の専業工場を解説付きで見学し、最後にもくめんクラフトを体験します。高知駅・空港・高知港から工場までの片道タクシー代を含み、2〜30名、5日前締切です。'},
  'otsuki-squid-fishing':{address:'高知県幡多郡大月町 町内漁港（柏島・一切のいずれか）',opening_hours:'7月中旬〜8月下旬。18:30集合（8月は18:00）〜21:00頃（2026年分は終了）',closed_days:'2026年分は終了。次回の夏季開催は公式情報を確認',price_text:'3名まで基本18,000円。4名から大人1名5,000円追加／小学生4,000円',phone:'0880-62-8133（大月町観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=110',parking_text:'集合する漁港の案内に従う',access:'高知龍馬空港・高知ICから車で約3時間。',last_verified_at:'2026-10-02',description:'大月町内の港から船で約10分の海上へ出て、疑似餌でケンサキイカを狙う夏季限定の約3時間体験です。釣ったイカは希望により船上で味わったり持ち帰ったりできます。2026年の開催期間は終了しています。1〜6名・小学生以上。予約受付は体験日の3日前から前日12時までです。'},
  'yasea-sup-kayak':{address:'高知県香南市夜須町千切537-90 ヤ・シィパーク海水浴場西側',opening_hours:'7月18日〜8月23日 9:00〜16:00（2026年分は終了）',closed_days:'2026年分は終了。次回の夏季開催は公式情報を確認',price_text:'大人3,500円／中学生以下2,000円（税込）',phone:'0887-57-1855（YASU海の駅クラブ）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=113',parking_text:'ヤ・シィパーク駐車場を利用',access:'夜須ICから車で約5分。土佐くろしお鉄道 夜須駅から徒歩すぐ。',last_verified_at:'2026-10-02',description:'ヤ・シィパークの海でSUPとカヤックを両方、またはどちらかをインストラクター付きで楽しむ約2時間の初心者向け体験です。2026年の開催期間は終了しています。定員10名・1名から催行、3日前までの事前予約制です。'},
  'shimizu-katsuo-show':{address:'高知県土佐清水市養老303 ジョン万次郎資料館集合',opening_hours:'通年 10:00開始・約3時間',closed_days:'土曜日',price_text:'10,000円/人（税込）',phone:'0880-82-3155（土佐清水市観光協会）',official_url:'https://doppuri.kochi-tabi.jp/selection.html?id=41',parking_text:'ジョン万次郎資料館駐車場を利用',access:'高知龍馬空港から車で約3時間。中村駅から車で約45分。',last_verified_at:'2026-10-02',description:'魚市場のセリを見学し、その日に仕入れたカツオの解体ショー、藁焼き体験、刺身・塩たたき・酢醤油たたきの3種食べ比べを楽しむ約3時間の体験です。定員12名・最少催行4名、5日前17時締切です。'}
};
const rank={};
export const spots=rows.map(([slug,name,category,area,municipality,tags,catchphrase],i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,slug,name,category,area,municipality,tags:tags.split(','),catchphrase,initial_rank:rank[category]=(rank[category]||0)+1,recommend_count:0,is_published:true,is_demo:false,photo:photos[slug]||null,main_image_url:photos[slug]?.src||'',description:'',created_at:`2026-09-${String(i+1).padStart(2,'0')}T00:00:00Z`,...(spotInfo[slug]||{})}));
const courseRows=[
['kochi-classic','高知市内 王道1日コース','kochi_city','王道','1日',['kochi-castle','myojinmaru','yasube']],
['niyodo-classic','空と仁淀ブルーキャンプ1日コース','north_niyodo','アクティブ','1日',['nikobuchi','yasui','ice','nakatsu']],
['niyodo-active','仁淀川 アクティブ満喫1日コース','north_niyodo','アクティブ','1日',['kayak','sauna','ice','nakatsu']],
['east-drive','東部絶景＆しらすグルメ1日コース','east','グルメ','1日',['shirasu','iokido','monet','muroto']],
['ocean-trip','柏島・足摺 海の1泊2日コース','west','カップル','1泊2日',['kashiwajima','ashizuri']],
['karst-drive','四国カルスト・梼原 絶景ドライブ','west','ドライブ','1日',['karst','yusuhara']],
['kochi-gourmet','高知市内 グルメ満喫1日コース','kochi_city','グルメ','1日',['myojinmaru','yasube']],
['kami-konan','龍河洞・香美香南 1日コース','east','雨の日','1日',['ryugado']],
['family','高知 子連れ1日コース','kochi_city','子連れ','1日',['kochi-castle','myojinmaru']],
['three-days','高知満喫2泊3日コース','north_niyodo','王道','2泊3日',['kochi-castle','nikobuchi','iokido']]];
const coursePhotoOverrides={
  'niyodo-classic':{src:'/assets/photos/course-niyodo-sky-camp.png',name:'空と仁淀ブルーキャンプ1日コース',alt:'パラグライダー、仁淀ブルー、キャンプを組み合わせたモデルコースのコラージュ',author:'ユーザー提供画像',source:'',license:'提供画像（サイト掲載用）',licenseUrl:'',width:1456,height:1020,position:'50% 50%',checkedAt:'2026-10-02'},
  'ocean-trip':{src:'/assets/photos/course-ocean-trip-collage.png',name:'柏島・足摺 海の1泊2日コース',alt:'柏島の海、海鮮、夕日をまとめたモデルコースのコラージュ',author:'ユーザー提供画像',source:'',license:'提供画像（サイト掲載用）',licenseUrl:'',width:1448,height:1086,position:'50% 50%',checkedAt:'2026-10-02'}
};
export const courses=courseRows.map(([slug,name,area,theme,duration,stops],i)=>{const photo=coursePhotoOverrides[slug]||stops.map(slug=>photos[slug]).find(Boolean)||null;return {slug,name,area,theme,duration,stops,initial_rank:i+1,transport:'車＋徒歩',season:'季節・天候に応じて',audience:theme==='子連れ'?'家族':theme==='カップル'?'カップル':'友人・ひとり旅',photo,image:photo?.src||''};});
export const eventCategories=['祭り・花火','グルメ','マルシェ','自然・アウトドア','文化・展覧会','子ども向け','スポーツ','期間限定体験'];
export const events=[
  {
    slug:'kochi-castle-autumn-oct-2026',
    image:'/assets/photos/kochi-castle-new.png',
    image_alt:'紅葉の時期をイメージした高知城',
    image_note:'会場イメージ',
    name:'高知城オータムフェスティバル（10月）',
    category:'文化・展覧会',
    area:'kochi_city',
    start_date:'2026-10-24',
    end_date:'2026-10-25',
    is_demo:false,
    description:'高知城の二ノ丸・懐徳館を会場に開催される秋のイベント。10月開催に続き、11月にも開催予定です。',
    venue:'高知城 二ノ丸・懐徳館',
    time:'10:00〜19:00',
    fee:'無料（天守・懐徳館は有料）',
    phone:'088-824-5701',
    official_url:'https://kochipark.jp/kochijyo/event/%E9%AB%98%E7%9F%A5%E5%9F%8E%E3%82%AA%E3%83%BC%E3%82%BF%E3%83%A0%E3%83%95%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%90%E3%83%AB/'
  },
  {
    slug:'okawa-shanikusai-2026',
    image:'/assets/photos/event-okawa.png',
    image_alt:'炭火で肉を焼くイベントのイメージ',
    image_note:'イメージ写真',
    name:'第43回 大川村謝肉祭',
    category:'グルメ',
    area:'north_niyodo',
    start_date:'2026-11-03',
    end_date:'2026-11-03',
    is_demo:false,
    description:'大川黒牛やはちきん地鶏を楽しむ大川村の名物イベント。2026年分の一般チケット受付は終了しています。',
    venue:'大川村 山村広場',
    time:'11:00〜15:00（開場10:30）',
    fee:'大人7,500円／高校生以下5,500円',
    phone:'0887-84-2201',
    official_url:'https://okawafk.or.jp/event/4838/'
  },
  {
    slug:'kochi-castle-autumn-nov-2026',
    image:'/assets/photos/kochi-castle-new.png',
    image_alt:'秋の高知城',
    image_note:'会場イメージ',
    name:'高知城オータムフェスティバル（11月）',
    category:'文化・展覧会',
    area:'kochi_city',
    start_date:'2026-11-21',
    end_date:'2026-11-23',
    is_demo:false,
    description:'高知城の秋を楽しむオータムフェスティバル第2期。11月21日のみ夜21時まで開催予定です。',
    venue:'高知城 二ノ丸・懐徳館',
    time:'10:00〜19:00（11月21日のみ21:00まで）',
    fee:'無料（天守・懐徳館は有料）',
    phone:'088-824-5701',
    official_url:'https://kochipark.jp/kochijyo/event/%E9%AB%98%E7%9F%A5%E5%9F%8E%E3%82%AA%E3%83%BC%E3%82%BF%E3%83%A0%E3%83%95%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%90%E3%83%AB/'
  },
  {
    slug:'yosakoi-2026',
    image:'/assets/photos/event-yosakoi.png',
    image_alt:'よさこい祭りで踊る人々のイメージ',
    image_note:'イメージ写真',
    name:'第73回よさこい祭り（2026）',
    category:'祭り・花火',
    area:'kochi_city',
    start_date:'2026-08-09',
    end_date:'2026-08-12',
    is_demo:false,
    description:'高知を代表する夏の祭り。8月10日・11日の本番を中心に、前夜祭・全国大会・後夜祭まで高知市中心部がよさこい一色に包まれました。',
    venue:'高知市追手筋ほか市内各会場',
    time:'会場・日程により異なる',
    fee:'観覧無料（一部有料観覧席あり）'
  },
  {
    slug:'tshirt-art-2026',
    image:'/assets/photos/event-tshirt-art.png',
    image_alt:'砂浜に並ぶTシャツ作品のイメージ',
    image_note:'イメージ写真',
    name:'第38回 Tシャツアート展',
    category:'文化・展覧会',
    area:'west',
    start_date:'2026-05-01',
    end_date:'2026-05-06',
    is_demo:false,
    description:'黒潮町・入野の浜に全国から集まったTシャツ作品が並ぶ、砂浜美術館の代表的な風景作品です。',
    venue:'砂浜美術館（黒潮町 入野の浜）',
    time:'9:00〜17:00',
    fee:'中学生以上 協力金300円',
    phone:'0880-43-4915',
    official_url:'https://sunabi.com/news-info/38th-t-shirt-art-program/'
  },
  {
    slug:'niyodogawa-koinobori-2026',
    image:'/assets/photos/course-niyodo-sup.png',
    image_alt:'仁淀川の清流',
    image_note:'仁淀川イメージ',
    name:'第30回 仁淀川 紙のこいのぼり',
    category:'自然・アウトドア',
    area:'north_niyodo',
    start_date:'2026-05-03',
    end_date:'2026-05-05',
    is_demo:false,
    description:'仁淀川の川面を紙のこいのぼりが泳ぐ、いの町の初夏の恒例イベント。グルメや体験企画も行われました。',
    venue:'仁淀川橋下（いの町波川公園周辺）',
    time:'9:00〜16:00（一部イベントは時間別）',
    fee:'一部体験等は個別料金あり',
    official_url:'https://www.inofan.jp/information/event/n4841/'
  },
  {
    slug:'kochi-castle-hanakairou-2026',
    image:'/assets/photos/event-hanakairou.png',
    image_alt:'夜の高知城と花のライトアップのイメージ',
    image_note:'イメージ写真',
    name:'高知城 花回廊2026',
    category:'文化・展覧会',
    area:'kochi_city',
    start_date:'2026-04-03',
    end_date:'2026-04-05',
    is_demo:false,
    description:'高知城・高知公園・丸ノ内緑地を生け花と灯りで彩る春の夜間イベントです。',
    venue:'高知城・高知公園・丸ノ内緑地',
    time:'18:00〜21:00',
    fee:'無料（天守・懐徳館は有料）',
    phone:'088-823-4016',
    official_url:'https://kochipark.jp/kochijyo/event/2026%E5%B9%B4%E3%80%80%E9%AB%98%E7%9F%A5%E5%9F%8E-%E8%8A%B1%E5%9B%9E%E5%BB%8A/'
  },
  {
    slug:'tosa-okyaku-2026',
    image:'/assets/photos/event-okyaku.png',
    image_alt:'高知の宴会文化を楽しむ人々のイメージ',
    image_note:'イメージ写真',
    name:'土佐の「おきゃく」2026',
    category:'グルメ',
    area:'kochi_city',
    start_date:'2026-03-07',
    end_date:'2026-03-15',
    is_demo:false,
    description:'高知の街を大きな宴会場に見立て、食・酒・音楽・よさこいなど多彩な催しを楽しむ春の恒例イベントです。',
    venue:'高知市中心商店街ほか',
    time:'各イベントにより異なる',
    fee:'各イベントにより異なる',
    phone:'088-823-0989',
    official_url:'https://tosa-okyaku.com/'
  }
];
export const sortSpots=items=>[...items].sort((a,b)=>b.recommend_count-a.recommend_count||a.initial_rank-b.initial_rank||a.slug.localeCompare(b.slug));
