// Individual photo licenses and provenance: PHOTOS.md. No API or database data.
export const photos={
  "ryugado": {
    "src": "/assets/photos/ryugado.jpg",
    "name": "龍河洞",
    "alt": "龍河洞の鍾乳石「奥の千本」",
    "author": "京浜にけ",
    "source": "https://commons.wikimedia.org/wiki/File:Kami_Kochi_Ryugado_Inside_4.JPG",
    "title": "Kami Kochi Ryugado Inside 4.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1280,
    "height": 853,
    "position": "45% 50%",
    "checkedAt": "2026-09-21"
  },
  "nikobuchi": {
    "src": "/assets/photos/nikobuchi.jpg",
    "name": "にこ淵",
    "alt": "にこ淵の青い滝つぼと滝",
    "author": "かるちる",
    "source": "https://commons.wikimedia.org/wiki/File:Niko_Buchi_deep_water_No.1.jpg",
    "title": "Niko Buchi deep water No.1.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "iokido": {
    "src": "/assets/photos/iokido.jpg",
    "name": "伊尾木洞",
    "alt": "伊尾木洞のシダに覆われた岩壁",
    "author": "Saigen Jiro",
    "source": "https://commons.wikimedia.org/wiki/File:Iokido_Cave-2.jpg",
    "title": "Iokido Cave-2.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 851,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "kochi-castle": {
    "src": "/assets/photos/kochi-castle.jpg",
    "name": "高知城",
    "alt": "高知城の天守と石垣",
    "author": "663highland",
    "source": "https://commons.wikimedia.org/wiki/File:Kochi_Castle04s3872.jpg",
    "title": "Kochi Castle04s3872.jpg",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "width": 1280,
    "height": 857,
    "position": "50% 38%",
    "checkedAt": "2026-09-21"
  },
  "kashiwajima": {
    "src": "/assets/photos/kashiwajima.jpg",
    "name": "柏島",
    "alt": "柏島の集落と青い海を見渡す全景",
    "author": "Saigen Jiro",
    "source": "https://commons.wikimedia.org/wiki/File:Kashiwajima_(Otsuki),_zenkei-1.jpg",
    "title": "Kashiwajima (Otsuki), zenkei-1.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 851,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "nakatsu": {
    "src": "/assets/photos/nakatsu.jpg",
    "name": "中津渓谷",
    "alt": "中津渓谷の清流と岩場",
    "author": "Koda6029",
    "source": "https://commons.wikimedia.org/wiki/File:%E4%B8%AD%E6%B4%A5%E6%B8%93%E8%B0%B7%EF%BC%92.jpg",
    "title": "中津渓谷２.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "monet": {
    "src": "/assets/photos/monet.jpg",
    "name": "北川村「モネの庭」マルモッタン",
    "alt": "北川村「モネの庭」マルモッタンの水の庭",
    "author": "Earthboud1960",
    "source": "https://commons.wikimedia.org/wiki/File:Monet-Marumottan-mizu02.jpg",
    "title": "Monet-Marumottan-mizu02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1280,
    "height": 854,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "muroto": {
    "src": "/assets/photos/muroto.jpg",
    "name": "室戸岬",
    "alt": "室戸岬の岩礁と太平洋",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "title": "Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "karst": {
    "src": "/assets/photos/karst.jpg",
    "name": "四国カルスト",
    "alt": "四国カルストの草原と石灰岩",
    "author": "Raita Futo from Tokyo, Japan",
    "source": "https://commons.wikimedia.org/wiki/File:Shikoku_Karst_(52004285742).jpg",
    "title": "Shikoku Karst (52004285742).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "yasui": {
    "src": "/assets/photos/yasui.jpg",
    "name": "安居渓谷",
    "alt": "安居渓谷・飛龍の滝",
    "author": "ball banban",
    "source": "https://commons.wikimedia.org/wiki/File:%E9%A3%9B%E9%BE%8D%E3%81%AE%E6%BB%9D_-_panoramio.jpg",
    "title": "飛龍の滝 - panoramio.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "width": 1067,
    "height": 1600,
    "position": "62% 58%",
    "checkedAt": "2026-09-23"
  },
  "yusuhara": {
    "src": "/assets/photos/yusuhara.jpg",
    "name": "梼原",
    "alt": "梼原町のゆすはら座外観",
    "author": "osami",
    "source": "https://commons.wikimedia.org/wiki/File:1yusuharaza.jpg",
    "title": "1yusuharaza.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 960,
    "position": "50% 48%",
    "checkedAt": "2026-09-23"
  },
  "ashizuri": {
    "src": "/assets/photos/ashizuri.jpg",
    "name": "足摺岬",
    "alt": "足摺岬の断崖と足摺岬灯台",
    "author": "Reggaeman",
    "source": "https://commons.wikimedia.org/wiki/File:Ashizuri_Cape_01.JPG",
    "title": "Ashizuri Cape 01.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1280,
    "height": 850,
    "position": "50% 54%",
    "checkedAt": "2026-09-23"
  },
  "makino-botanical-garden": {
    "src": "/assets/photos/makino-botanical-garden.png",
    "name": "高知県立牧野植物園",
    "alt": "高知県立牧野植物園の温室を見上げる植物と青空",
    "author": "提供画像",
    "source": "ユーザー提供",
    "title": "高知県立牧野植物園",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1536,
    "height": 1024,
    "position": "50% 50%",
    "checkedAt": "2026-09-26"
  }
};
