// Individual photo licenses and provenance: PHOTOS.md. No API or database data.
export const photos={
  "oki-surf": {
    "src": "https://upload.wikimedia.org/wikipedia/commons/a/a0/%E5%A4%A7%E5%B2%90%E6%B5%B7%E5%B2%B8_-_panoramio.jpg",
    "name": "大岐海岸",
    "alt": "土佐清水市の大岐海岸",
    "author": "Yobito KAYANUMA",
    "source": "https://commons.wikimedia.org/wiki/File:大岐海岸_-_panoramio.jpg",
    "title": "大岐海岸 - panoramio.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1600,
    "height": 902,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "ikumi-surf": {
    "src": "/assets/photos/ikumi-surf.jpg",
    "name": "生見サーフィンビーチ",
    "alt": "東洋町の生見海岸",
    "author": "Araiyasushige",
    "source": "https://commons.wikimedia.org/wiki/File:Ikumi_coast_20240514_1.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "width": 1280,
    "height": 834,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "irino-surf": {
    "src": "/assets/photos/irino-surf.jpg",
    "name": "入野海岸",
    "alt": "黒潮町の入野海岸",
    "author": "Ubuhouse",
    "source": "https://commons.wikimedia.org/wiki/File:入野海岸.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 960,
    "height": 720,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "forest-adventure-kochi": {
    "src": "/assets/photos/hero-forest-adventure.png",
    "name": "フォレストアドベンチャー・高知",
    "alt": "森の中で楽しむアドベンチャー体験のイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 1672,
    "height": 941,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "niyodo-buggy": {
    "src": "/assets/photos/hero-buggy.png",
    "name": "NIYODO バギー体験（NOZUアドベンチャー）",
    "alt": "自然の中を走るバギー体験のイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "agawa-paragliding": {
    "src": "/assets/photos/hero-paragliding.png",
    "name": "吾川スカイパーク パラグライダー",
    "alt": "山の上空を飛ぶパラグライダー体験のイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 1672,
    "height": 941,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "katsuo-waraya": {
    "src": "/assets/photos/course-katsuo-tataki.png",
    "name": "カツオの藁焼きタタキづくり体験（黒潮一番館）",
    "alt": "カツオの藁焼きタタキのイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 469,
    "height": 340,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tosa-terrace-cycle": {
    "src": "/assets/photos/course-classic-bridge.png",
    "name": "こうち旅広場 レンタサイクル",
    "alt": "高知市街を自転車でめぐるイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 511,
    "height": 342,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tosappo-ryoma-walk": {
    "src": "/assets/photos/sakamoto-ryoma-memorial-museum.png",
    "name": "龍馬の生まれたまち歩き〜土佐っ歩〜",
    "alt": "坂本龍馬ゆかりの高知を歩くイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 768,
    "height": 512,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "yoshinogawa-rafting": {
    "src": "/assets/photos/hero-rafting.png",
    "name": "吉野川ラフティング体験（You Me Rafting）",
    "alt": "吉野川ラフティング体験のイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "kochi-horse-riding": {
    "src": "/assets/photos/kochi-horse-riding.jpg",
    "name": "高知ホースライディングクラブ 乗馬体験",
    "alt": "乗馬体験のイメージ",
    "author": "MIKI Yoshihito",
    "source": "https://commons.wikimedia.org/wiki/File:SAKURAKO_tries_horse_riding._(10223022775).jpg",
    "title": "SAKURAKO tries horse riding. (10223022775).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "uguru-snorkel": {
    "src": "/assets/photos/uguru-fishing.jpg",
    "name": "鵜来島 シュノーケル体験（うぐるBOX）",
    "alt": "鵜来島の海のイメージ",
    "author": "ブルーノ・プラス",
    "source": "https://commons.wikimedia.org/wiki/File:Ugurushima_Island_01.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "sakoda-knife": {
    "src": "/assets/photos/sakoda-knife.jpg",
    "name": "刃物鍛造体験（迫田打刃物）",
    "alt": "鍛冶職人が仕上げた刃物のイメージ",
    "author": "Tim Lively",
    "source": "https://commons.wikimedia.org/wiki/File:Blacksmith_Knife_made_by_Tim_Lively.jpg",
    "title": "Blacksmith Knife made by Tim Lively.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 786,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "uchiharano-craft": {
    "src": "/assets/photos/uchiharano-pottery.jpg",
    "name": "陶芸・ガラス体験（内原野陶芸館）",
    "alt": "ろくろで陶器を作る体験のイメージ",
    "author": "Eman abdelkader12",
    "source": "https://commons.wikimedia.org/wiki/File:Hands_making_pottery.jpg",
    "title": "Hands making pottery.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tosa-tataki-dojo": {
    "src": "/assets/photos/course-katsuo-tataki.png",
    "name": "土佐タタキ道場",
    "alt": "カツオの藁焼きタタキ体験のイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 469,
    "height": 340,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "field-kochi": {
    "src": "/assets/photos/field-kochi.jpg",
    "name": "FIELD KOCHI 里山体験・土佐塩の道ウォーキング",
    "alt": "日本の里山景観のイメージ",
    "author": "Indiana jo",
    "source": "https://commons.wikimedia.org/wiki/File:Kiiji,_Haratani_village_02.jpg",
    "title": "Kiiji, Haratani village 02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "ryugado-candle": {
    "src": "/assets/photos/ryugado-candle.jpg",
    "name": "龍河洞キャンドルづくり（38 phyto lab.）",
    "alt": "キャンドルづくり作業のイメージ",
    "author": "Wellcome Library, London",
    "source": "https://commons.wikimedia.org/wiki/File:Candle_makers%27_workshop%3B_interior_view%2C_process_of_making_ca_Wellcome_V0023724.jpg",
    "title": "Candle makers' workshop; interior view, process of making ca Wellcome V0023724.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "width": 1280,
    "height": 667,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "shimanto-canoe": {
    "src": "/assets/photos/shimanto-canoe.jpg",
    "name": "四万十川カヌー体験（しまんとベース）",
    "alt": "四万十市西土佐を流れる四万十川",
    "author": "Cherrysherbet",
    "source": "https://commons.wikimedia.org/wiki/File:Nishitosa_Shimanto_river.jpg",
    "title": "Nishitosa Shimanto river.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 604,
    "height": 453,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "ino-papermaking": {
    "src": "/assets/photos/ino-papermaking.jpg",
    "name": "紙漉き体験（いの町紙の博物館）",
    "alt": "江戸時代の紙漉きを描いた版画イメージ",
    "author": "Japanese fine prints, pre-1915 / Library of Congress",
    "source": "https://commons.wikimedia.org/wiki/File:Kamisuki_LCCN2009615107.jpg",
    "title": "Kamisuki LCCN2009615107.jpg",
    "license": "Public Domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "width": 1280,
    "height": 1057,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "yosakoi-naruko": {
    "src": "/assets/photos/yosakoi-naruko.jpg",
    "name": "鳴子づくり体験（高知よさこい情報交流館）",
    "alt": "よさこい踊りで使われる鳴子",
    "author": "Mycomp",
    "source": "https://commons.wikimedia.org/wiki/File:Naruko_(bird_rattles).JPG",
    "title": "Naruko (bird rattles).JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 960,
    "height": 1280,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "noichi-zoo": {
    "src": "/assets/photos/noichi-zoo.jpg",
    "name": "高知県立のいち動物公園",
    "alt": "高知県立のいち動物公園の園内",
    "author": "Shoichi Masuhara",
    "source": "https://commons.wikimedia.org/wiki/File:Noichi_zoo2.jpg",
    "title": "Noichi zoo2.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "width": 1280,
    "height": 819,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "muroto-dolphin": {
    "src": "/assets/photos/muroto-dolphin.jpg",
    "name": "室戸ドルフィンセンター",
    "alt": "ハンドウイルカのイメージ",
    "author": "safaritravelplus",
    "source": "https://commons.wikimedia.org/wiki/File:Bottlenose_Dolphin.jpg",
    "title": "Bottlenose Dolphin.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/",
    "width": 1280,
    "height": 914,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "kaminokae-fishery": {
    "src": "/assets/photos/kaminokae-fishery.jpg",
    "name": "上ノ加江漁業体験",
    "alt": "漁師が海へカニかごを下ろす漁業体験のイメージ",
    "author": "Long (lTiga) Nguyen / Unsplash",
    "source": "https://unsplash.com/photos/fisherman-lowering-a-crab-trap-into-the-ocean-8c_h_1tFWFc",
    "title": "Fisherman lowering a crab trap into the ocean",
    "license": "Unsplash License",
    "licenseUrl": "https://unsplash.com/license",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "ogata-whale": {
    "src": "/assets/photos/irino-surf.jpg",
    "name": "大方ホエールウォッチング",
    "alt": "黒潮町・入野海岸の海辺",
    "author": "Ubuhouse",
    "source": "https://commons.wikimedia.org/wiki/File:入野海岸.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 960,
    "height": 720,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "uguru-fishing": {
    "src": "/assets/photos/uguru-fishing.jpg",
    "name": "鵜来島 釣り体験（うぐるBOX）",
    "alt": "宿毛沖に浮かぶ鵜来島の全景",
    "author": "ブルーノ・プラス",
    "source": "https://commons.wikimedia.org/wiki/File:Ugurushima_Island_01.jpg",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tatsukushi-diving": {
    "src": "/assets/photos/tatsukushi-fishing.jpg",
    "name": "竜串 体験ダイビング（竜串ダイビングセンター）",
    "alt": "土佐清水市の竜串海岸",
    "author": "Reggaeman",
    "source": "https://commons.wikimedia.org/wiki/File:Tatsukushi_05.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 850,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tatsukushi-fishing": {
    "src": "/assets/photos/tatsukushi-fishing.jpg",
    "name": "竜串 船釣り体験（西本渡船）",
    "alt": "土佐清水市の竜串海岸",
    "author": "Reggaeman",
    "source": "https://commons.wikimedia.org/wiki/File:Tatsukushi_05.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 850,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "niyodo-fishing": {
    "src": "/assets/photos/niyodo-fishing.jpg",
    "name": "仁淀川の釣り",
    "alt": "越知町を流れる仁淀川と中仁淀橋",
    "author": "谷本 一郎",
    "source": "https://commons.wikimedia.org/wiki/File:中仁淀橋―沈下橋.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "sarudado-caving": {
    "src": "/assets/photos/sarudado-caving.jpg",
    "name": "猿田洞ケイビング",
    "alt": "猿田洞の洞窟入口",
    "author": "提供画像を加工",
    "license": "提供画像（サイト掲載用）",
    "width": 1774,
    "height": 887,
    "position": "50% 50%",
    "checkedAt": "2026-10-01"
  },
  "ryugado-adventure": {
    "src": "/assets/photos/ryugado.jpg",
    "name": "龍河洞 冒険コース",
    "alt": "龍河洞の鍾乳石「奥の千本」",
    "author": "京浜にけ",
    "source": "https://commons.wikimedia.org/wiki/File:Kami_Kochi_Ryugado_Inside_4.JPG",
    "title": "Kami Kochi Ryugado Inside 4.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1280,
    "height": 853,
    "position": "45% 50%",
    "checkedAt": "2026-10-01"
  },
  "ryugado": {
    "src": "/assets/photos/ryugado-caving.png",
    "name": "龍河洞",
    "alt": "ライトアップされた龍河洞の洞内でヘルメット姿の2人が立つ様子",
    "author": "ユーザー提供画像",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1672,
    "height": 941,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "nikobuchi": {
    "src": "/assets/photos/nikobuchi.jpg",
    "name": "にこ淵",
    "alt": "にこ淵の青い滝つぼと滝",
    "author": "かるちる",
    "source": "https://commons.wikimedia.org/wiki/File:Niko_Buchi_deep_water_No.1.jpg",
    "title": "Niko Buchi deep water No.1.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "iokido": {
    "src": "/assets/photos/iokido.jpg",
    "name": "伊尾木洞",
    "alt": "伊尾木洞のシダに覆われた岩壁",
    "author": "Saigen Jiro",
    "source": "https://commons.wikimedia.org/wiki/File:Iokido_Cave-2.jpg",
    "title": "Iokido Cave-2.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 851,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "kochi-castle": {
    "src": "/assets/photos/kochi-castle-new.png",
    "name": "高知城",
    "alt": "青空の下にそびえる高知城の天守と石垣",
    "author": "提供画像を加工",
    "source": "ユーザー提供画像を加工",
    "title": "高知城",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1537,
    "height": 1023,
    "position": "50% 46%",
    "checkedAt": "2026-10-01"
  },
  "kashiwajima-diving-aquas": {
    "src": "/assets/photos/kashiwajima.jpg",
    "name": "柏島 体験ダイビング（AQUAS）",
    "alt": "柏島の集落と青い海を見渡す全景",
    "author": "Saigen Jiro",
    "source": "https://commons.wikimedia.org/wiki/File:Kashiwajima_(Otsuki),_zenkei-1.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 851,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "kashiwajima": {
    "src": "/assets/photos/kashiwajima.jpg",
    "name": "柏島",
    "alt": "柏島の集落と青い海を見渡す全景",
    "author": "Saigen Jiro",
    "source": "https://commons.wikimedia.org/wiki/File:Kashiwajima_(Otsuki),_zenkei-1.jpg",
    "title": "Kashiwajima (Otsuki), zenkei-1.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 851,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "nakatsu": {
    "src": "/assets/photos/nakatsu.jpg",
    "name": "中津渓谷",
    "alt": "中津渓谷の清流と岩場",
    "author": "Koda6029",
    "source": "https://commons.wikimedia.org/wiki/File:%E4%B8%AD%E6%B4%A5%E6%B8%93%E8%B0%B7%EF%BC%92.jpg",
    "title": "中津渓谷２.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1280,
    "height": 853,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "monet": {
    "src": "/assets/photos/monet.jpg",
    "name": "北川村「モネの庭」マルモッタン",
    "alt": "北川村「モネの庭」マルモッタンの水の庭",
    "author": "Earthboud1960",
    "source": "https://commons.wikimedia.org/wiki/File:Monet-Marumottan-mizu02.jpg",
    "title": "Monet-Marumottan-mizu02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "width": 1280,
    "height": 854,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "kuroshio-soba": {
    "src": "/assets/photos/field-kochi.jpg",
    "name": "そば打ち体験（であいの里 蜷川）",
    "alt": "山里で楽しむ食体験のイメージ",
    "author": "Indiana jo",
    "source": "https://commons.wikimedia.org/wiki/File:Kiiji,_Haratani_village_02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "hinodeya-konnyaku": {
    "src": "/assets/photos/field-kochi.jpg",
    "name": "こんにゃく作り体験（燈ので家）",
    "alt": "山あいの農家体験のイメージ",
    "author": "Indiana jo",
    "source": "https://commons.wikimedia.org/wiki/File:Kiiji,_Haratani_village_02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "seiran-konnyaku": {
    "src": "/assets/photos/field-kochi.jpg",
    "name": "田舎こんにゃく体験（せいらんの里）",
    "alt": "津野町の山里体験のイメージ",
    "author": "Indiana jo",
    "source": "https://commons.wikimedia.org/wiki/File:Kiiji,_Haratani_village_02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "qraud-papermaking": {
    "src": "/assets/photos/ino-papermaking.jpg",
    "name": "紙漉き体験（土佐和紙工芸村「くらうど」）",
    "alt": "紙漉きの工程を描いた歴史資料",
    "author": "Library of Congress",
    "source": "https://www.loc.gov/pictures/item/2008660729/",
    "license": "Public Domain",
    "licenseUrl": "",
    "width": 1280,
    "height": 1056,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "soltive-salt": {
    "src": "/assets/photos/irino-surf.jpg",
    "name": "天日塩づくり体験（ソルティーブ）",
    "alt": "黒潮町・入野海岸の海のイメージ",
    "author": "Ubuhouse",
    "source": "https://commons.wikimedia.org/wiki/File:Irino_beach_Kuroshio_Kochi.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 960,
    "height": 720,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tano-solar-salt": {
    "src": "/assets/photos/muroto.jpg",
    "name": "完全天日塩づくり体験（田野町）",
    "alt": "高知県東部の海岸風景のイメージ",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tosacho-woodwork": {
    "src": "/assets/photos/field-kochi.jpg",
    "name": "土佐町 木組み・鍋敷きづくり体験",
    "alt": "山あいの里山風景のイメージ",
    "author": "Indiana jo",
    "source": "https://commons.wikimedia.org/wiki/File:Kiiji,_Haratani_village_02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "shimanto-traditional-fishing": {
    "src": "/assets/photos/shimanto-canoe.jpg",
    "name": "四万十川 伝統漁法体験",
    "alt": "四万十市西土佐を流れる四万十川",
    "author": "Cherrysherbet",
    "source": "https://commons.wikimedia.org/wiki/File:Nishitosa_Shimanto_river.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 604,
    "height": 453,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "withriver-shimanto": {
    "src": "/assets/photos/shimanto-canoe.jpg",
    "name": "四万十川 SUP・カヌー ガイドツアー（withRIVER）",
    "alt": "四万十市西土佐を流れる四万十川",
    "author": "Cherrysherbet",
    "source": "https://commons.wikimedia.org/wiki/File:Nishitosa_Shimanto_river.jpg",
    "title": "Nishitosa Shimanto river.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 604,
    "height": 453,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "garbanzo-yoshino": {
    "src": "/assets/photos/hero-rafting.png",
    "name": "アウトドア！ガルバンゾ 吉野川リバーアクティビティ",
    "alt": "吉野川のリバーアクティビティのイメージ",
    "author": "既存サイト画像",
    "source": "",
    "license": "既存サイト資産",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "tsuno-tea-field": {
    "src": "/assets/photos/field-kochi.jpg",
    "name": "津野茶 茶畑見学・お茶体験",
    "alt": "山あいの里山風景のイメージ",
    "author": "Indiana jo",
    "source": "https://commons.wikimedia.org/wiki/File:Kiiji,_Haratani_village_02.jpg",
    "title": "Kiiji, Haratani village 02.jpg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "muroto-aqua-farm": {
    "src": "/assets/photos/muroto.jpg",
    "name": "室戸海洋深層水アクア・ファーム",
    "alt": "室戸岬の海岸風景",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "title": "Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "muroto-geo-guide": {
    "src": "/assets/photos/muroto.jpg",
    "name": "室戸世界ジオパーク ガイドツアー",
    "alt": "室戸世界ジオパークの海岸風景",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "title": "Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "muroto-rockpool": {
    "src": "/assets/photos/muroto.jpg",
    "name": "室戸世界ジオパーク 磯遊び体験",
    "alt": "室戸岬の岩礁と海",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "title": "Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "muroto-cycle-tour": {
    "src": "/assets/photos/muroto.jpg",
    "name": "室戸世界ジオパーク サイクリングツアー",
    "alt": "室戸岬の海岸沿いをめぐるイメージ",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "title": "Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "muroto": {
    "src": "/assets/photos/muroto.jpg",
    "name": "室戸岬",
    "alt": "室戸岬の岩礁と太平洋",
    "author": "Rsa",
    "source": "https://commons.wikimedia.org/wiki/File:Cape-Muroto-20100526.jpg",
    "title": "Cape-Muroto-20100526.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "width": 1280,
    "height": 960,
    "position": "50% 50%",
    "checkedAt": "2026-09-21"
  },
  "karst": {
    "src": "/assets/photos/shikoku-karst-web.jpg",
    "name": "四国カルスト",
    "alt": "風車と石灰岩が広がる四国カルストの高原風景",
    "author": "ユーザー提供画像を加工",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1536,
    "height": 1024,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "yasui": {
    "src": "/assets/photos/yasui.jpg",
    "name": "安居渓谷",
    "alt": "安居渓谷・飛龍の滝",
    "author": "ball banban",
    "source": "https://commons.wikimedia.org/wiki/File:%E9%A3%9B%E9%BE%8D%E3%81%AE%E6%BB%9D_-_panoramio.jpg",
    "title": "飛龍の滝 - panoramio.jpg",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "width": 1067,
    "height": 1600,
    "position": "62% 58%",
    "checkedAt": "2026-09-23"
  },
  "yusuhara": {
    "src": "/assets/photos/yusuhara.jpg",
    "name": "梼原",
    "alt": "梼原町のゆすはら座外観",
    "author": "osami",
    "source": "https://commons.wikimedia.org/wiki/File:1yusuharaza.jpg",
    "title": "1yusuharaza.jpg",
    "license": "CC0",
    "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "width": 1280,
    "height": 960,
    "position": "50% 48%",
    "checkedAt": "2026-09-23"
  },
  "ashizuri": {
    "src": "/assets/photos/ashizuri.jpg",
    "name": "足摺岬",
    "alt": "足摺岬の断崖と足摺岬灯台",
    "author": "Reggaeman",
    "source": "https://commons.wikimedia.org/wiki/File:Ashizuri_Cape_01.JPG",
    "title": "Ashizuri Cape 01.JPG",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "width": 1280,
    "height": 850,
    "position": "50% 54%",
    "checkedAt": "2026-09-23"
  },
  "kayak": {
    "src": "/assets/photos/sea-kayak.jpg",
    "name": "仁淀川シーカヤック",
    "alt": "透明な水面を上空から見下ろしたシーカヤック体験",
    "author": "提供画像を加工",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1200,
    "height": 800,
    "position": "50% 50%"
  },
  "sauna": {
    "src": "/assets/photos/tent-sauna-niyodo.png",
    "name": "Niyodo Adventureのテントサウナ",
    "alt": "清流沿いに設置された白いテントサウナ",
    "author": "ユーザー指定の生成・加工画像",
    "source": "",
    "license": "サイト掲載用画像",
    "licenseUrl": "",
    "width": 1536,
    "height": 1024,
    "position": "50% 50%",
    "checkedAt": "2026-10-02"
  },
  "yasube": {
    "src": "/assets/photos/yasube.png",
    "name": "屋台安兵衛",
    "alt": "赤提灯が灯る夜の屋台安兵衛",
    "author": "提供画像",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 52%"
  },
  "hashimoto": {
    "src": "/assets/photos/hashimoto.png",
    "name": "橋本食堂",
    "alt": "橋本食堂の鍋焼きラーメン",
    "author": "提供画像",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 50%"
  },
  "shirasu": {
    "src": "/assets/photos/shirasu.png",
    "name": "安芸しらす食堂 本店",
    "alt": "青空の下に建つ安芸しらす食堂 本店",
    "author": "提供画像",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 50%"
  },
  "myojinmaru": {
    "src": "/assets/photos/myojinmaru.png",
    "name": "明神丸 本店",
    "alt": "夜に明かりが灯る明神丸 本店の外観",
    "author": "提供画像を加工",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1448,
    "height": 1086,
    "position": "50% 50%"
  },
  "tanaka": {
    "src": "/assets/photos/tanaka.png",
    "name": "田中鮮魚店 漁師小屋",
    "alt": "田中鮮魚店 漁師小屋の店内で食事を楽しむ人々",
    "author": "提供画像を加工",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1536,
    "height": 1024,
    "position": "50% 50%"
  },
  "ice": {
    "src": "/assets/photos/ice.png",
    "name": "高知アイス売店 仁淀川カフェ",
    "alt": "仁淀川を望む高知アイス売店 仁淀川カフェの店内",
    "author": "提供画像を加工",
    "source": "",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1672,
    "height": 941,
    "position": "50% 50%"
  },
  "chikurinji": {
    "src": "/assets/photos/chikurinji-pagoda.png",
    "name": "竹林寺",
    "alt": "新緑に囲まれた竹林寺の五重塔と石段",
    "author": "提供画像を加工",
    "source": "ユーザー提供画像を加工",
    "title": "竹林寺",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1024,
    "height": 1536,
    "position": "50% 42%",
    "checkedAt": "2026-10-01"
  },
  "kochi-castle-history-museum": {
    "src": "/assets/photos/kochi-castle-history-museum.png",
    "name": "高知県立高知城歴史博物館",
    "alt": "青空の下に建つ高知県立高知城歴史博物館",
    "author": "提供画像",
    "source": "ユーザー提供画像（2×2分割）",
    "title": "高知県立高知城歴史博物館",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 768,
    "height": 512,
    "position": "50% 50%",
    "checkedAt": "2026-09-26"
  },
  "sakamoto-ryoma-memorial-museum": {
    "src": "/assets/photos/sakamoto-ryoma-memorial-museum.png",
    "name": "高知県立坂本龍馬記念館",
    "alt": "青空と海を望む高知県立坂本龍馬記念館",
    "author": "提供画像",
    "source": "ユーザー提供画像（2×2分割）",
    "title": "高知県立坂本龍馬記念館",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 768,
    "height": 512,
    "position": "50% 50%",
    "checkedAt": "2026-09-26"
  },
  "shioe-tenmangu": {
    "src": "/assets/photos/shioe-tenmangu.png",
    "name": "潮江天満宮",
    "alt": "緑に囲まれた潮江天満宮の参道と社殿",
    "author": "提供画像",
    "source": "ユーザー提供画像（2×2分割）",
    "title": "潮江天満宮",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 768,
    "height": 512,
    "position": "50% 50%",
    "checkedAt": "2026-09-26"
  },
  "makino-botanical-garden": {
    "src": "/assets/photos/makino-botanical-garden.png",
    "name": "高知県立牧野植物園",
    "alt": "高知県立牧野植物園の温室を見上げる植物と青空",
    "author": "提供画像",
    "source": "ユーザー提供",
    "title": "高知県立牧野植物園",
    "license": "提供画像（サイト掲載用）",
    "licenseUrl": "",
    "width": 1536,
    "height": 1024,
    "position": "50% 50%",
    "checkedAt": "2026-09-26"
  }
};
