import {photos} from './photos.mjs';
import {homeSlides} from './home-content.mjs';
import {areas,categories,themes,filters,spots,courses,events,eventCategories,sortSpots} from './data.mjs';
import {isIndexablePath} from './site.mjs';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label,cls='')=>`<a class="${cls}" href="${url}">${esc(label)}</a>`;
const options=(values,all='すべて')=>`<option value="">${all}</option>`+Object.entries(Array.isArray(values)?Object.fromEntries(values.map(x=>[x,x])):values).map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('');
const chips=(values,base,key='theme')=>`<div class="chips">${values.map(v=>link(`${base}?${key}=${encodeURIComponent(v)}`,v)).join('')}</div>`;
const section=(en,title,body,url,label='すべて見る →')=>`<section><div class="section-head"><div><div class="eyebrow">${en}</div><h2>${title}</h2></div>${url?link(url,label):''}</div>${body}</section>`;
const photoImage=(photo,name,cls='',eager=false,mobileSrc='')=>{const img=`<img class="${esc(cls)}" src="${esc(photo?.src||'/assets/photos/unset.svg')}" alt="${esc(photo?.alt||name+'：写真未設定')}" width="${photo?.width||1280}" height="${photo?.height||800}" style="object-position:${esc(photo?.position||'50% 50%')}" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;return mobileSrc?`<picture class="home-slide-picture"><source media="(max-width:390px)" srcset="${esc(mobileSrc)}">${img}</picture>`:img;};
const photoCredit=(photo,cls='')=>photo?.source?`<p class="photo-credit ${cls}">写真：<a href="${esc(photo.source)}" target="_blank" rel="noopener">${esc(photo.name)} / ${esc(photo.author)}</a> · <a href="${esc(photo.licenseUrl)}" target="_blank" rel="noopener">${esc(photo.license)}</a><span>縮小・表示トリミング${photo.license.includes('SA')?'／写真の派生物も同ライセンス':''}</span></p>`:'';
const hero=(title,sub,compact=false,photo=null)=>`<div class="hero ${compact?'compact':''}">${photo?photoImage(photo,photo.name,'',true):''}<div class="inner"><div class="eyebrow">KOCHI · A JOURNEY TO REMEMBER</div><h1>${title}</h1><p>${sub}</p>${compact?'':`<form action="/search/" class="hero-search"><input name="q" aria-label="行きたい場所を検索" placeholder="行きたい場所を見つけよう" required><button aria-label="検索する">検索</button></form>`}</div>${photoCredit(photo,'photo-note')}</div>`;
export function spotCard(s,i){return `<article class="card spot-card ${i!==undefined?'rank-card':''}"><a href="/spots/${esc(s.slug)}/">${photoImage(s.photo,s.name)}${i!==undefined?`<span class="badge ${['gold','silver','bronze','other','other'][i]||'other'}">${i+1}</span>`:''}<div class="card-body"><span class="label">${esc(areas[s.area])} · ${esc(categories[s.category])}</span><h3>${esc(s.name)}</h3><p>${esc(s.catchphrase)}</p></div></a>${photoCredit(s.photo)}<div class="card-body vote-container"><button class="vote" data-vote="${esc(s.id)}" aria-pressed="false">♡ おすすめ <span>${Number(s.recommend_count)||0}</span></button></div></article>`}
const spotGrid=(items,rank=false)=>items.length?`<div class="grid spots-grid ${rank?'rank-grid':''}">${items.map((s,i)=>spotCard(s,rank?i:undefined)).join('')}</div>`:'<div class="empty">掲載スポットを準備しています。<p>あなたのおすすめを教えてください。</p><a class="button" href="/suggest/">スポットを提案する</a></div>';
const courseCard=(c,i)=>`<article class="card course-card"><a href="/courses/${esc(c.slug)}/">${photoImage(c.photo,c.name)}${i!==undefined?`<span class="badge ${i===1?'silver':i===2?'bronze':i>2?'other':''}">${i+1}</span>`:''}<div class="card-body"><span class="label">${areas[c.area]} · ${esc(c.duration)}</span><h3>${esc(c.name)}</h3><p>${esc(c.theme)} / ${esc(c.transport)}</p></div></a>${photoCredit(c.photo)}</article>`;
const courseGrid=items=>`<div class="grid course-grid">${items.filter(Boolean).map(c=>courseCard(c)).join('')}</div>`;
let demoNotice='<div class="notice">プレビュー版：掲載候補の情報は未確認です。写真は撮影時点のもので、各写真に出典を表示しています。未設定の写真は確認でき次第掲載します。営業時間・料金はお出かけ前に公式情報をご確認ください。</div>';
const eventCard=e=>`<article class="card"><div class="card-body"><span class="label">${esc(e.category)} · ${esc(areas[e.area])}</span><h3>${link(`/events/${esc(e.slug)}/`,e.name)}</h3><p>${esc(e.start_date)} ～ ${esc(e.end_date)}</p>${e.is_demo?'<small>架空の表示サンプル・開催情報ではありません</small>':''}</div></article>`;
function homeEvents(){const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());const month=today.slice(0,7);const current=events.filter(e=>!e.is_demo&&e.start_date<=month+'-31'&&e.end_date>=today).slice(0,3);return current.length?`<div class="grid">${current.map(eventCard).join('')}</div>`:'<div class="empty">開催情報は確認中です。確認できた催しから順次掲載します。</div>';}
function homeSlider(){return `<section class="home-slider" data-carousel tabindex="0" aria-label="高知のおすすめ特集"><div class="home-slider-track">${homeSlides.map((slide,i)=>`<article class="home-slide" data-carousel-slide aria-hidden="${i?'true':'false'}">${photoImage(slide.photo,slide.title,'',i===0,i===0?'/assets/photos/hero-sup-mobile.png':'')}<div class="home-slide-shade"></div>${slide.note?`<p class="home-slide-note">${slide.note.split('\n').map(line=>`<span>${esc(line)}</span>`).join('')}</p>`:''}<div class="home-slide-content"><div class="eyebrow">${esc(slide.eyebrow||'KOCHI TRAVEL GUIDE')}</div><h1>${esc(slide.title)}</h1><p>${esc(slide.description)}</p>${link(slide.href,slide.label,'button')}</div>${photoCredit(slide.photo,'home-slide-credit')}</article>`).join('')}</div><div class="home-slider-controls"><button type="button" class="home-slider-arrow prev" data-carousel-prev aria-label="前の写真">‹</button><div class="home-slider-dots" aria-label="スライドを選択">${homeSlides.map((slide,i)=>`<button type="button" data-carousel-dot="${i}" aria-label="${i+1}枚目：${esc(slide.title)}" aria-current="${i===0?'true':'false'}"></button>`).join('')}</div><div class="home-slider-index" aria-label="スライド番号" aria-live="polite">${homeSlides.map((slide,i)=>`<span data-carousel-index="${i}" aria-current="${i===0?'true':'false'}">${String(i+1).padStart(2,'0')}</span>`).join('')}</div><button type="button" class="home-slider-arrow next" data-carousel-next aria-label="次の写真">›</button></div></section><section class="home-search-section" aria-label="旅先を検索"><form action="/search/" class="home-search"><div class="home-search-heading"><span class="home-search-icon" aria-hidden="true">⌕</span><span><small>行きたい高知が見つかる</small><strong>スポットを検索</strong></span></div><div class="home-search-fields"><input id="home-search-input" name="q" aria-label="行きたい場所を検索" placeholder="キーワードで検索（例：桂浜、カツオ、仁淀川 など）"><select aria-label="エリア"><option>エリア</option>${options(areas).replace(/^<option value="">.*?<\/option>/,'')}</select><select aria-label="カテゴリ"><option>カテゴリ</option>${options(categories).replace(/^<option value="">.*?<\/option>/,'')}</select><select aria-label="こだわり条件"><option>こだわり条件</option>${options(themes).replace(/^<option value="">.*?<\/option>/,'')}</select><button class="primary">⌕　検索する</button></div></form></section>`;}
const homeActivities=[
  ['SUP','仁淀川で水上散歩','/assets/photos/kochi-sup-hero.png','/activity/'],
  ['シーカヤック','海・川の景色を巡る','/assets/photos/nikobuchi.jpg','/activity/'],
  ['ラフティング','仲間と楽しむ爽快体験','/assets/photos/hero-rafting.png','/activity/'],
  ['サーフィン','太平洋の波を感じる','/assets/photos/kashiwajima.jpg','/activity/'],
  ['釣り','海・川・磯で釣り体験','/assets/photos/muroto.jpg','/fishing/'],
  ['サイクリング','風を感じて土佐を旅する','/assets/photos/karst.jpg','/cycling/'],
  ['キャンプ','大自然で過ごす','/assets/photos/yusuhara.jpg','/camp/'],
  ['フォレストアドベンチャー','森の冒険で遊ぶ','/assets/photos/hero-forest-adventure.png','/activity/'],
  ['パラグライダー','空から高知を一望','/assets/photos/hero-paragliding.png','/activity/'],
  ['テントサウナ','自然の中でととのう','/assets/photos/hero-camping.png','/activity/']
];
const homeScenes=[['高知城','歴史と城下町の景観','/assets/photos/kochi-castle.jpg','/spots/kochi-castle/'],['にこ淵','神秘的な青の絶景','/assets/photos/nikobuchi.jpg','/spots/nikobuchi/'],['柏島','エメラルドブルーの海','/assets/photos/kashiwajima.jpg','/spots/kashiwajima/'],['伊尾木洞','太古の自然が残る洞窟','/assets/photos/iokido.jpg','/spots/iokido/'],['四国カルスト','天空のパノラマ','/assets/photos/karst.jpg','/spots/karst/'],['桂浜','土佐の海と龍馬の像','/assets/photos/kashiwajima.jpg','/sightseeing/'],['足摺岬','太平洋の絶景','/assets/photos/ashizuri.jpg','/spots/ashizuri/'],['モネの庭','四季の花と水の庭園','/assets/photos/monet.jpg','/spots/monet/']];
function homeActivityGrid(){return `<div class="home-activity-grid">${homeActivities.map(([name,sub,src,href])=>`<a class="home-activity-card" href="${href}"><img src="${src}" alt="${name}" loading="lazy"><span class="home-activity-icon" aria-hidden="true">✦</span><strong>${name}</strong><small>${sub}</small></a>`).join('')}</div>`;}
function homeSceneStrip(){return `<div class="home-scene-strip">${homeScenes.map(([name,sub,src,href])=>`<a class="home-scene-card" href="${href}"><img src="${src}" alt="${name}" loading="lazy"><strong>${name}</strong><small>${sub}</small></a>`).join('')}</div>`;}
function homeActivityRanking(){return `<div class="home-activity-ranking">${homeActivities.slice(0,5).map(([name,sub,src,href],i)=>`<a class="home-ranking-card" href="${href}"><span class="home-ranking-number rank-${i+1}">${i+1}</span><img src="${src}" alt="${name}" loading="lazy"><strong>${name}</strong><small>${sub}</small><span class="home-card-arrow" aria-hidden="true">›</span></a>`).join('')}</div>`;}
const homeCourseFeatures=[
  {slug:'niyodo-active',title:'仁淀川SUP＋ととのう1日コース',tags:['人気','体験'],departure:'高知市発',duration:'日帰り',area:'仁淀川エリア',description:'SUP、テントサウナ、川辺のカフェまで楽しむ充実の1日。',main:['/assets/photos/course-niyodo-sup.png','仁淀川でSUPを楽しむ風景'],thumbs:[['/assets/photos/course-niyodo-sauna.png','テントサウナのあるキャンプ風景'],['/assets/photos/course-niyodo-ice.png','仁淀川アイス'],['/assets/photos/course-hirome-market.png','ひろめ市場']]},
  {slug:'karst-drive',title:'四国カルスト・森と建築を楽しむ1日コース',tags:['絶景','グルメ'],departure:'高知市発',duration:'日帰り',area:'津野・梼原エリア',description:'フォレストアドベンチャーや四国カルスト、雲の上の建築を楽しむ高原旅。',catchcopy:'雄大な高原で、\n自然と建築に出会う。',main:['/assets/photos/course-karst-panorama.png','四国カルストの青空と山並み、草原、牛、道'],thumbs:[['/assets/photos/course-cloud-library.png','雲の上の図書館の木組みと本棚'],['/assets/photos/course-katsuo-tataki.png','藁焼き鰹塩たたき'],['/assets/photos/hero-forest-adventure.png','森のフォレストアドベンチャー体験']]},
  {slug:'niyodo-classic',title:'空と仁淀ブルーを楽しむキャンプ1日コース',tags:['絶景','体験'],departure:'高知市発',duration:'日帰り',area:'仁淀川エリア',description:'空からの眺め、にこ淵、キャンプを組み合わせて楽しむ特別な1日。',main:['/assets/photos/hero-paragliding.png','空を舞うパラグライダー'],thumbs:[['/assets/photos/nikobuchi.jpg','にこ淵の滝つぼ'],['/assets/photos/hero-camping.png','焚き火のあるキャンプ'],['/assets/photos/nakatsu.jpg','中津渓谷の清流']]},
  {slug:'ocean-trip',title:'柏島・海を満喫する1泊2日コース',tags:['人気','1泊2日'],departure:'高知市発',duration:'1泊2日',area:'大月町・柏島',description:'柏島の海でのんびり過ごし、海辺の景色と西部の味覚を楽しむ旅。',main:['/assets/photos/kashiwajima.jpg','柏島の青い海と集落'],thumbs:[['/assets/photos/muroto.jpg','室戸岬の海岸風景'],['/assets/photos/ashizuri.jpg','足摺岬の灯台と海'],['/assets/photos/kashiwajima.jpg','柏島の海を見渡す景色']]}
];
function homeCourseGrid(){return `<div class="home-course-grid">${homeCourseFeatures.map(course=>`<article class="home-course-card"><a class="home-course-media" href="/courses/${esc(course.slug)}/" aria-label="${esc(course.title)}の詳細を見る"><img class="home-course-main" src="${esc(course.main[0])}" alt="${esc(course.main[1])}" loading="lazy">${course.catchcopy?`<span class="home-course-catchcopy">${course.catchcopy.split(/\n/).map(line=>esc(line)).join('<br>')}</span>`:''}<div class="home-course-thumbs">${course.thumbs.map(([src,alt])=>`<img src="${esc(src)}" alt="${esc(alt)}" loading="lazy">`).join('')}</div></a><div class="home-course-body"><div class="home-course-topline"><h3>${link(`/courses/${esc(course.slug)}/`,course.title)}</h3><div class="home-course-tags">${course.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</div></div><dl class="home-course-meta"><div><dt>出発</dt><dd>${esc(course.departure)}</dd></div><div><dt>日程</dt><dd>${esc(course.duration)}</dd></div><div><dt>エリア</dt><dd>${esc(course.area)}</dd></div></dl><div class="home-course-footer"><p>${esc(course.description)}</p>${link(`/courses/${esc(course.slug)}/`,'コース詳細を見る　→','home-course-link')}</div></div></article>`).join('')}</div>`;}
function home(){return homeSlider()+`<div class="home-content wrap">`+section('ACTIVITY','アクティビティから探す',homeActivityGrid(),'/activity/','すべてのアクティビティを見る →')+section('MODEL COURSE','おすすめモデルコース',homeCourseGrid(),'/courses/','すべてのモデルコースを見る →')+section('POPULAR RANKING','人気アクティビティランキング TOP5',homeActivityRanking(),'/activity/','すべてのランキングを見る →')+`<section class="home-scene-section"><div class="section-head"><div><div class="eyebrow">SCENIC SPOT</div><h2>景色・名所から探す</h2></div>${link('/sightseeing/','すべての景色・名所を見る →')}</div>${homeSceneStrip()}</section>`+section('CATEGORIES','高知を楽しむカテゴリー一覧',`<div class="home-category-chips">${Object.entries(categories).map(([k,v])=>link('/'+k+'/',v+' →')).join('')}</div>`)+`<section class="home-pickup-section"><div class="home-pickup-label"><div class="eyebrow">PICK UP</div><h2>今月のおすすめ</h2></div><div class="feature"><div class="eyebrow">NIYODO BLUE</div><h3>青に出会う、仁淀川の旅。</h3><p>にこ淵から渓谷、川辺のカフェへ。<br>自然をゆっくり味わうコースをご紹介。</p>${link('/courses/niyodo-classic/','コースを見る →','button')}</div></section>`+`<div class="home-bottom-grid"><section><div class="section-head"><div><div class="eyebrow">EVENT</div><h2>今週・今月のイベント</h2></div>${link('/events/','すべてのイベントを見る →')}</div>${homeEvents()}</section><section><div class="section-head"><div><div class="eyebrow">NEW SPOT</div><h2>新しく追加されたスポット</h2></div></div>${spotGrid([...spots].reverse().slice(0,3))}</section></div>`+demoNotice+'</div>'}
function ranking(category){let list=sortSpots(spots.filter(s=>s.category===category));return hero(`${categories[category]}ランキング`,'みんなの「おすすめ」で見つける、高知の楽しみ方。',true,category==='sightseeing'?photos.kashiwajima:null)+`<div class="wrap" data-ranking="${category}"><form class="filterbar" id="spot-filter"><label>エリア<select name="area">${options(areas)}</select></label><label>テーマ・条件<select name="theme">${options(filters[category]||['絶景','子連れ','雨の日','定番','穴場'])}</select></label><button class="primary">絞り込む</button></form><p class="muted">実投票数 → 同票時は初期順位。すべての掲載候補は0票から。</p>${section('TOP PICKS','総合 TOP5',`<div id="rank-results">${spotGrid(list.slice(0,5),true)}</div>`)}${section('FIND YOUR FAVORITE','テーマ・条件から探す',chips(filters[category]||['絶景','子連れ','雨の日'],`/${category}/`))}${category==='sightseeing'?section('LOCAL FAVORITES','エリア別人気スポット',Object.entries(areas).map(([k,v])=>`<h3>${v}</h3>${spotGrid(list.filter(s=>s.area===k).slice(0,2))}`).join(''))+section('TRENDING','急上昇スポット','<div class="empty">投票が集まったら、注目のスポットをご紹介します。</div>'):''}${section('MORE TO DISCOVER','みんなのおすすめ',`<div id="more-results">${spotGrid(list.slice(5))}</div>`)}${section('NEW','新着スポット',spotGrid([...list].reverse().slice(0,3)))}${section('TRAVEL NOTES','おすすめ記事・特集',`<div class="feature"><h3>スポットをつなげて、ひとつの旅に。</h3>${link('/courses/','モデルコースから探す →','button')}</div>`)}${demoNotice}</div>`}
function coursesPage(){return hero('高知をめぐる、<br>とっておきのコース。','気になるエリアとテーマから、あなたに合う旅を。',true,photos.karst)+`<div class="wrap"><form id="course-filter" class="filterbar"><label>エリア<select name="area">${options(areas)}</select></label><label>テーマ<select name="theme">${options(themes)}</select></label><label>日数<select name="duration">${options(['半日','1日','1泊2日','2泊3日'])}</select></label><button class="primary">絞り込む</button></form><p id="result-count">10件のモデルコース</p><div id="course-results">${courseGrid(courses)}</div>${demoNotice}</div>`}
function courseDetail(c){return hero(esc(c.name),'寄り道まで楽しむ、高知の旅。',true,c.photo)+`<div class="wrap"><div class="summary"><span>所要時間：${esc(c.duration)}</span><span>移動：${esc(c.transport)}</span><span>対象：${esc(c.audience)}</span><span>季節：${esc(c.season)}</span></div><button data-placeholder="保存機能は準備中です">♡ コースを保存（準備中）</button><div class="notice">旅程は提案段階です。滞在・移動時間は仮の目安で、予約枠や道路状況を確認して調整してください。</div><div class="two-col"><section><h2>旅のスケジュール</h2><div class="timeline">${c.stops.filter(slug=>spots.some(s=>s.slug===slug)).map((slug,i)=>{const s=spots.find(x=>x.slug===slug);return `<article class="stop">${photoImage(s.photo,s.name,'stop-photo')}<span class="eyebrow">STOP ${String(i+1).padStart(2,'0')}</span><h3>${link('/spots/'+slug+'/',s.name)}</h3>${photoCredit(s.photo)}<p>${esc(s.catchphrase)}</p><p class="muted">滞在目安：${s.category==='gourmet'?'60':'90'}分（仮）${i?' / 前のスポットから：経路確認が必要です':''}</p></article>`}).join('')}</div></section><aside><h2>地図でルートを見る</h2><p>各スポットの場所と移動時間を確認できます。</p>${link('https://www.google.com/maps/dir/'+c.stops.map(slug=>encodeURIComponent((spots.find(s=>s.slug===slug)?.name||slug)+' 高知')).join('/'),'Google Mapsでルートを見る ↗','button')}<h3>立ち寄りグルメ</h3>${c.stops.filter(slug=>spots.find(s=>s.slug===slug)?.category==='gourmet').map(slug=>`<p>${link('/spots/'+slug+'/',spots.find(s=>s.slug===slug).name)}</p>`).join('')||'<p>周辺の飲食店もチェック。</p>'+link('/gourmet/','グルメ一覧 →')}<h3>旅の注意点</h3><p>天候・増水・通行規制を事前に確認してください。体験は開催事業者への予約確認が必要です。自然環境と地域のルールを大切に。</p></aside></div>${demoNotice}</div>`}
function spotDetail(s){let rank=sortSpots(spots.filter(x=>x.category===s.category)).findIndex(x=>x.id===s.id)+1;return `<div class="wrap"><section><p class="muted">${link('/'+s.category+'/',categories[s.category])} / ${areas[s.area]}</p>${photoImage(s.photo,s.name,'detail-photo',true)}${photoCredit(s.photo)}<div class="eyebrow">${areas[s.area]} · ${esc(s.municipality)}</div><h1>${esc(s.name)}</h1><h2>${esc(s.catchphrase)}</h2><p>現在順位：<span id="current-rank">${rank}</span> / 初期順位：${s.initial_rank}（${categories[s.category]}）</p><div style="max-width:320px"><button class="vote" data-vote="${s.id}" aria-pressed="false">♡ おすすめ <span>0</span></button></div><div class="chips"><button data-placeholder="行ってみたい機能は準備中です">♡ 行ってみたい</button><button data-placeholder="コース追加機能は準備中です">＋ マイコースに追加</button></div><p>${esc(s.description)}</p><dl class="facts">${Object.entries({'住所':s.address,'営業時間':s.opening_hours,'定休日':s.closed_days,'料金':s.price_text,'駐車場':s.parking_text,'アクセス':s.access,'電話':s.phone,'公式サイト':s.official_url,'最終情報確認日':s.last_verified_at}).map(([k,v])=>`<dt>${k}</dt><dd>${esc(v||'未確認')}</dd>`).join('')}</dl>${link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(s.name+' 高知'),'Google Mapsで場所を確認 ↗','button')} ${link('/correction/?spot='+s.slug,'情報の修正を提案','button')}</section>${section('REVIEWS','口コミ','<div class="empty">口コミ機能は準備中です。まだ評価はありません。</div>')}${section('NEARBY','同じエリアのおすすめ',spotGrid(spots.filter(x=>x.area===s.area&&x.id!==s.id).slice(0,3)))}${section('RELATED COURSES','関連モデルコース',courseGrid(courses.filter(c=>c.stops.includes(s.slug))))}${demoNotice}</div>`}
function eventsPage(){return hero('高知の今に、会いにいく。','祭り、食、自然。旅の日程に合わせて見つけよう。',true)+`<div class="wrap"><form id="event-filter" class="filterbar"><label>日程<select name="period">${options(['今日','今週','今月','開催中','これから'])}</select></label><label>カテゴリ<select name="category">${options(eventCategories)}</select></label><button class="primary">絞り込む</button></form><label><input type="checkbox" id="show-demo" style="display:inline;width:auto"> 画面確認用の架空イベントを表示</label><section id="event-results"><div class="empty">確認済みの開催情報はまだありません。</div></section><p>常設・予約制体験は ${link('/activity/','アクティビティ一覧','subtle-link')} から。</p></div>`}
function eventDetail(e){return hero(esc(e.name),'イベント詳細',true)+`<div class="wrap"><section><div class="notice">${esc(e.description)}</div><dl class="facts"><dt>日程</dt><dd>${e.start_date} ～ ${e.end_date}</dd><dt>エリア</dt><dd>${areas[e.area]}</dd><dt>カテゴリ</dt><dd>${e.category}</dd><dt>会場・料金</dt><dd>サンプルにつき未設定</dd></dl>${link('/events/','イベント一覧へ','button')}</section></div>`}
function field(name,label,required=false,type='text'){return `<label>${label}${required?'<span class="required">必須</span>':''}<input name="${name}" type="${type}" ${required?'required':''} maxlength="${type==='url'?2000:300}"></label>`}
function formPage(kind){const suggest=kind==='suggest';return `<div class="wrap"><section><div class="eyebrow">HELP US DISCOVER KOCHI</div><h1>${suggest?'おすすめスポットを教えてください':'情報の修正を提案'}</h1><p>ご提案は運営が確認してから反映します。</p><div class="notice" id="form-mode">接続状態を確認しています。</div><form class="form" id="request-form" data-kind="${kind}">${suggest?field('name','店名・施設名',true)+`<div class="form-grid"><label>カテゴリ<span class="required">必須</span><select name="category" required>${options(categories,'選択してください')}</select></label><label>エリア<span class="required">必須</span><select name="area" required>${options(areas,'選択してください')}</select></label></div>`+field('municipality','市町村',true)+`<label>おすすめ理由<span class="required">必須</span><textarea name="reason" required maxlength="3000"></textarea></label><div class="form-grid">${[['address','住所'],['official_url','公式サイト','url'],['instagram','Instagram','url'],['x_url','X','url'],['phone','電話','tel'],['google_maps_url','Google Maps URL','url'],['menu','おすすめメニュー'],['nickname','ニックネーム'],['email','メール','email']].map(([n,l,t])=>field(n,l,false,t)).join('')}</div><label>補足<textarea name="notes" maxlength="3000"></textarea></label>`:`<label>対象スポット<span class="required">必須</span><select name="spot_id" required>${options(Object.fromEntries(spots.map(s=>[s.id,s.name])),'選択してください')}</select></label><label>修正対象<span class="required">必須</span><select name="target" required>${options(['営業時間','定休日','住所','電話','料金','駐車場','公式URL','店名/施設名','閉店/休業','写真','その他'],'選択してください')}</select></label><label>修正内容・確認元<span class="required">必須</span><textarea name="reason" maxlength="3000" required></textarea></label>${field('email','メール（任意）',false,'email')}`}<p class="footnote">入力内容は確認・連絡のために使用します。${link('/privacy/','プライバシー方針','subtle-link')}</p><button class="primary" type="submit">提案を送信する</button><p id="form-result" role="status" aria-live="polite"></p></form></section></div>`}
const legal={about:['このサイトについて','高知の旅先を、みんなのおすすめと運営が選んだモデルコースから探すサイトです。','おすすめ票は実票のみを表示し、同票の場合は運営設定の初期順位で並べます。掲載申請は運営確認後に公開します。'],contact:['お問い合わせ','高知観光ランキング運営事務局への一般のお問い合わせは、下記メールアドレスへご連絡ください。','掲載のご提案は掲載追加申請、掲載情報の修正は情報修正申請をご利用ください。ご提案・修正内容は運営が確認後に対応します。'],terms:['利用規約','本規約は、高知観光ランキング運営事務局（以下「運営」といいます。）が運営する高知観光ランキング（以下「本サイト」といいます。）の利用条件を定めるものです。','本サイトの掲載情報、営業時間、料金、予約可否その他の内容は変更される場合があります。利用・予約の前に、必ず各施設・事業者の公式情報をご確認ください。','不正投票、不正アクセス、虚偽または誤認を招く申請、他者の権利・名誉・プライバシーを侵害する行為、本サイトの運営を妨げる行為を禁止します。','掲載提案および修正申請は、運営の判断で掲載・反映しない場合があります。運営は、確認した施設情報、修正情報その他の申請内容を、必要な範囲で本サイトに反映する場合があります。','本サイトの文章、写真、画像その他のコンテンツに関する著作権その他の権利は、運営または各権利者に帰属します。写真は各表示クレジットおよびライセンス条件に従って利用されています。無断転載・再利用はご遠慮ください。','本サイトからリンクする外部サイトの内容、提供サービス、個人情報の取扱いについて、運営は責任を負いません。外部サイトの規約・方針をご確認ください。','運営は、掲載情報の正確性、完全性、有用性、特定目的への適合性、サービスの継続性を保証しません。本サイトの利用または利用不能により生じた損害について、法令上認められる範囲で責任を負いません。','運営は、必要に応じて本規約を変更できます。変更後の規約は本サイトに掲載した時点から適用します。','本規約は日本法に準拠します。'],privacy:['プライバシーポリシー','高知観光ランキング運営事務局（以下「運営」といいます。）は、本サイトで取り扱う情報を適切に管理します。','本サイトは、投票状態の識別と不正利用防止のため、ブラウザーのlocalStorageに匿名IDを保存します。匿名IDは、投票対象スポットIDおよび投票記録とともに、ランキング集計、不正利用防止、サービス運営のために必要な期間保存します。','掲載提案では、施設名、カテゴリ、エリア、市町村、おすすめ理由のほか、任意で住所、公式サイト・SNS・地図URL、電話番号、メニュー、ニックネーム、メールアドレス、補足を取得します。修正申請では、対象スポット、修正対象、修正内容・確認元、任意メールアドレスを取得します。','取得した情報は、投票管理、不正利用防止、掲載提案・修正申請の審査、必要な連絡、サイト情報の改善・掲載のために利用します。メールアドレス等の個人情報を原則として一般公開しません。施設情報や修正内容は、確認後に本サイトへ反映する場合があります。','投票記録および申請情報は、Cloudflare WorkersおよびD1を利用して保存・処理します。掲載提案、修正申請および任意メールアドレスは、対応完了後1年を目安に削除します。','本サイトは現在、Google Analytics、広告、広告トラッキングを独自に実装していません。Cloudflare等のサービス提供事業者によるアクセスログ、Cookie、国外処理その他の取扱いは、各事業者の設定・方針により異なるため、本ポリシーではコードから確認できる範囲を超えて断定しません。','情報の開示、訂正、削除等のご希望は、本人確認等の必要な確認を行ったうえで、法令および合理的な範囲で対応します。お問い合わせは下記メールアドレスへご連絡ください。','未成年の方が本サイトを通じて情報を提供する場合、必要に応じて保護者の同意を求めることがあります。','運営は、必要に応じて本ポリシーを変更します。変更後のポリシーは本サイトに掲載した時点から適用します。']};
export const getRoutes=()=>['/','/courses/',...Object.keys(categories).map(k=>`/${k}/`),'/events/',...events.map(e=>`/events/${esc(e.slug)}/`),...courses.map(c=>`/courses/${esc(c.slug)}/`),...spots.map(s=>`/spots/${s.slug}/`),...Object.keys(areas).map(k=>`/area/${k.replaceAll('_','-')}/`),'/suggest/','/correction/','/login/','/mypage/',...Object.keys(legal).map(k=>`/${k}/`),'/search/'];
export const routes=getRoutes();
export function render(path,origin='',indexing=false){let bits=path.split('/').filter(Boolean),title='高知観光ランキング',body='',status=200;if(!bits.length)body=home();else if(categories[bits[0]]&&bits.length===1){title=categories[bits[0]]+'ランキング';body=ranking(bits[0]);}else if(bits[0]==='courses'&&bits.length===1){title='モデルコース';body=coursesPage();}else if(bits[0]==='courses'&&courses.some(c=>c.slug===bits[1])){const c=courses.find(c=>c.slug===bits[1]);title=c.name;body=courseDetail(c);}else if(bits[0]==='spots'&&spots.some(s=>s.slug===bits[1])){const s=spots.find(s=>s.slug===bits[1]);title=s.name;body=spotDetail(s);}else if(bits[0]==='events'&&bits.length===1){title='イベント';body=eventsPage();}else if(bits[0]==='events'&&events.some(e=>e.slug===bits[1])){const e=events.find(e=>e.slug===bits[1]);title=e.name;body=eventDetail(e);}else if(bits[0]==='area'&&areas[bits[1]?.replaceAll('-','_')]){const area=bits[1].replaceAll('-','_');title=areas[area];body=hero(title+'を旅する','その土地ならではの景色と、おいしい時間。',true,photos[{kochi_city:'kochi-castle',east:'muroto',west:'kashiwajima',north_niyodo:'nikobuchi'}[area]])+`<div class="wrap">${section('SPOTS','おすすめスポット',spotGrid(sortSpots(spots.filter(s=>s.area===area))))}${section('COURSES','このエリアのモデルコース',courseGrid(courses.filter(c=>c.area===area)))}</div>`;}else if(['suggest','correction'].includes(bits[0])){title=bits[0]==='suggest'?'掲載追加申請':'情報修正申請';body=formPage(bits[0]);}else if(legal[bits[0]]){const [t,...p]=legal[bits[0]];title=t;const contactMail=bits[0]==='contact'||bits[0]==='privacy'?`<p>メール：${link('mailto:luidabase@gmail.com','luidabase@gmail.com','subtle-link')}</p>`:'';body=`<div class="wrap"><section><h1>${t}</h1>${p.map(x=>`<p>${x}</p>`).join('')}${contactMail}<div class="chips">${link('/suggest/','掲載追加申請')}${link('/correction/','情報修正申請')}</div></section></div>`;}else if(['login','mypage'].includes(bits[0])){title=bits[0]==='login'?'ログイン':'マイページ';body=`<div class="wrap"><section><h1>${title}</h1><div class="empty"><h2>旅の楽しみを、これからもっと。</h2><p>会員機能・お気に入り・マイコースは準備中です。<br>おすすめ投票は会員登録なしで利用できます。</p>${link('/courses/','モデルコースを探す','button')}</div></section></div>`;}else if(bits[0]==='search'){title='検索';body=`<div class="wrap"><section><h1>高知の旅を検索</h1><form class="search" id="search-form"><input name="q" aria-label="スポット・コースを検索" placeholder="スポット名・エリア・テーマ"><button class="primary">検索</button></form><div id="search-results"></div></section></div>`;}else{status=404;title='ページが見つかりません';body=`<div class="wrap"><section><h1>ページが見つかりません</h1>${link('/','トップへ戻る','button')}</section></div>`;}
const canonical=origin&&status===200?new URL(path,origin).href:'';const robots=indexing&&status===200&&isIndexablePath(path)?'index,follow':'noindex,nofollow';const nav=bits.length===0?[['/search/','スポットを探す'],['/courses/','モデルコース'],['/area/kochi-city/','エリア'],['/sightseeing/','特集'],['/events/','イベント'],['/about/','お役立ち情報']].map(([href,label])=>link(href,label)).join('')+'<span class="home-nav-divider" aria-hidden="true"></span>'+[['/search/','検索'],['/mypage/','お気に入り'],['/about/','メニュー']].map(([href,label])=>link(href,label)).join(''):[link('/courses/','モデルコース'),Object.entries(categories).filter(([k])=>k!=='cycling').map(([k,v])=>link('/'+k+'/',v)).join(''),link('/events/','イベント'),link('/search/','検索 ⌕')].join('');return {status,html:`<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}${title==='高知観光ランキング'?'':' | 高知観光ランキング'}</title><meta name="description" content="${esc(title)}。エリアとテーマから見つける、高知の観光・グルメ・モデルコース。"><meta name="robots" content="${robots}">${canonical?`<link rel="canonical" href="${esc(canonical)}"><meta property="og:url" content="${esc(canonical)}">`:''}<meta property="og:title" content="${esc(title)}"><meta property="og:description" content="高知の旅を、エリアとテーマから。"><meta property="og:site_name" content="高知観光ランキング"><meta property="og:type" content="website"><link rel="icon" href="/favicon.svg"><link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="192x192" href="/assets/icons/icon-192.png"><link rel="icon" type="image/png" sizes="512x512" href="/assets/icons/icon-512.png"><link rel="icon" type="image/png" href="/assets/icons/app-icon.png"><link rel="stylesheet" href="/styles.css"><script src="/config.js"></script><script type="module" src="/app.mjs"></script></head><body><a class="skip" href="#main">本文へスキップ</a><header><div class="topbar"><a class="brand${bits.length===0?' home-brand':''}" href="/">${bits.length===0?'<img class="home-brand-mark" src="/favicon.svg" alt="" aria-hidden="true"><span class="home-brand-copy">':''}<small>KOCHI TRAVEL GUIDE</small>高知観光ランキング${bits.length===0?'</span>':''}</a>${bits.length===0?'':link('/mypage/','♡ 保存した旅','button')}</div><nav class="nav" aria-label="メインナビ">${nav}</nav></header><main id="main" class="page-${esc(bits[0]||'home')}">${body}</main><footer><a class="brand" href="/">高知観光ランキング</a><p>次の休日は、高知へ。</p><div class="chips">${[['about','このサイトについて'],['suggest','掲載追加申請'],['correction','情報修正申請'],['contact','お問い合わせ'],['terms','利用規約'],['privacy','プライバシー'],['login','ログイン']].map(([k,v])=>link('/'+k+'/',v)).join('')}</div><small>© 高知観光ランキング</small></footer><div id="toast" class="status" role="status" hidden></div></body></html>`};}
export function setLiveMode(){demoNotice='';}
export {spotGrid,courseGrid,eventCard};
