import {chromium} from '/Users/ogasawara/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {routes} from '../render.mjs';import {spots} from '../data.mjs';
const base=process.env.KOCHI_TEST_ORIGIN||'http://127.0.0.1:4174';
const browser=await chromium.launch({headless:true,channel:"chrome"});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const route of routes){await page.goto(base+route);await page.waitForTimeout(40);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Overflow: '+route)}
await page.goto(base+'/sightseeing/');await page.locator('#rank-results .vote').first().click();assert.equal(await page.locator('#rank-results .vote').first().getAttribute('aria-pressed'),'true');await page.reload();assert.equal(await page.locator('#rank-results .vote').first().getAttribute('aria-pressed'),'true');await page.locator('#rank-results .vote').first().click();assert.equal(await page.locator('#rank-results .vote').first().getAttribute('aria-pressed'),'false');
await page.locator('#spot-filter .filter-chip[data-value=east]').click();assert.equal(await page.locator('#rank-results .card').count(),4);
await page.goto(base+'/courses/?area=north_niyodo&theme=アクティブ');assert.equal(await page.locator('#course-results .card').count(),1);
await page.goto(base+'/search/?q=にこ淵');assert.equal(await page.locator('#search-results .card').count(),1);
await page.goto(base+'/events/');assert.equal(await page.locator('#event-results .card').count(),0);await page.locator('#show-demo').check();assert.equal(await page.locator('#event-results .card').count(),1);
await page.goto(base+'/suggest/');await page.locator('[name=name]').fill('試験用施設');await page.locator('[name=category]').selectOption('camp');await page.locator('[name=area]').selectOption('east');await page.locator('[name=municipality]').fill('試験用市');await page.locator('[name=reason]').fill('動作確認');await page.locator('#request-form button').click();assert.match(await page.locator('#form-result').innerText(),/運営には送信されていません/);await page.reload();assert.equal(await page.locator('[name=name]').inputValue(),'試験用施設');
await page.goto(base+'/');await page.screenshot({path:'/private/tmp/kochi-mobile.png',fullPage:true});await page.screenshot({path:'/private/tmp/kochi-mobile-viewport.png'});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/private/tmp/kochi-desktop.png',fullPage:true});await page.screenshot({path:'/private/tmp/kochi-desktop-viewport.png'});
for(const width of [390,1440]){await page.setViewportSize({width,height:900});for(const path of ['/sightseeing/','/courses/','/courses/niyodo-classic/']){await page.goto(base+path);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width}: ${path}`);await page.screenshot({path:`/private/tmp/kochi-${width}-${path.split('/').filter(Boolean).join('-')}.png`,fullPage:false})}}
assert.deepEqual(errors,[]);console.log(`PASS ${routes.length} routes at 390px; desktop layouts; local votes, persistence, filters, search, events, drafts; no JS errors`);await browser.close();
