import {chromium} from '/Users/ogasawara/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';import {routes} from '../render.mjs';import {spots} from '../data.mjs';
const browser=await chromium.launch({headless:true,channel:"chrome"});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const route of routes){await page.goto('http://127.0.0.1:4174'+route);await page.waitForTimeout(40);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Overflow: '+route)}
await page.goto('http://127.0.0.1:4174/sightseeing/');await page.locator('#rank-results .vote').first().click();assert.equal(await page.locator('#rank-results .vote').first().getAttribute('aria-pressed'),'true');await page.reload();assert.equal(await page.locator('#rank-results .vote').first().getAttribute('aria-pressed'),'true');await page.locator('#rank-results .vote').first().click();assert.equal(await page.locator('#rank-results .vote').first().getAttribute('aria-pressed'),'false');
await page.locator('[name=area]').selectOption('east');await page.locator('#spot-filter button').click();assert.equal(await page.locator('#rank-results .card').count(),4);
await page.goto('http://127.0.0.1:4174/courses/?area=north_niyodo&theme=アクティブ');assert.equal(await page.locator('#course-results .card').count(),1);
await page.goto('http://127.0.0.1:4174/search/?q=にこ淵');assert.equal(await page.locator('#search-results .card').count(),1);
await page.goto('http://127.0.0.1:4174/events/');assert.equal(await page.locator('#event-results .card').count(),0);await page.locator('#show-demo').check();assert.equal(await page.locator('#event-results .card').count(),1);
await page.goto('http://127.0.0.1:4174/suggest/');await page.locator('[name=name]').fill('試験用施設');await page.locator('[name=category]').selectOption('camp');await page.locator('[name=area]').selectOption('east');await page.locator('[name=municipality]').fill('試験用市');await page.locator('[name=reason]').fill('動作確認');await page.locator('#request-form button').click();assert.match(await page.locator('#form-result').innerText(),/運営には送信されていません/);await page.reload();assert.equal(await page.locator('[name=name]').inputValue(),'試験用施設');
await page.goto('http://127.0.0.1:4174/');await page.screenshot({path:'/private/tmp/kochi-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/private/tmp/kochi-desktop.png',fullPage:true});await page.screenshot({path:'/private/tmp/kochi-desktop-viewport.png'});
let voted=false,submitted=null;await page.route('**/config.js',route=>route.fulfill({contentType:'text/javascript',body:'window.KOCHI_CONFIG={supabaseUrl:"https://kochi-test.invalid",supabaseAnonKey:"test",siteUrl:""}'}));await page.route('https://kochi-test.invalid/**',route=>{const path=new URL(route.request().url()).pathname;let data=[];if(path==='/auth/v1/signup')data={access_token:'test',refresh_token:'test',expires_in:3600};else if(path==='/rest/v1/spots')data=[{...spots[1],name:'<img src=x onerror=alert(1)>',is_demo:false}];else if(path.endsWith('/toggle_recommendation')){voted=!voted;data={voted,recommend_count:voted?1:0}}else if(path.endsWith('/submit_request')){submitted=route.request().postDataJSON();data='request-id'}return route.fulfill({contentType:'application/json',body:JSON.stringify(data)})});await page.goto('http://127.0.0.1:4174/sightseeing/');await page.waitForFunction(()=>document.querySelector('#rank-results h3')?.textContent.includes('<img'));assert.equal(await page.locator('#rank-results h3 img').count(),0);await page.locator('#rank-results .vote').click();await page.waitForFunction(()=>document.querySelector('#rank-results .vote').getAttribute('aria-pressed')==='true');assert.equal(await page.locator('#rank-results .vote').getAttribute('aria-pressed'),'true');await page.goto('http://127.0.0.1:4174/');await page.waitForTimeout(150);await page.goto('http://127.0.0.1:4174/suggest/');await page.waitForTimeout(150);await page.locator('[name=name]').fill('試験');await page.locator('[name=category]').selectOption('camp');await page.locator('[name=area]').selectOption('east');await page.locator('[name=municipality]').fill('試験');await page.locator('[name=reason]').fill('試験');await page.locator('#request-form button').click();await page.waitForFunction(()=>document.querySelector('#form-result').textContent.includes('受け付け'));assert.equal(submitted.kind,'suggest');assert.equal(submitted.payload.status,undefined);assert.deepEqual(errors,[]);console.log(`PASS ${routes.length} routes at 390px; votes, persistence, filters, search, events, drafts; no JS errors`);await browser.close();
