import {access,readFile} from 'node:fs/promises';import {constants} from 'node:fs';import {resolve} from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';import {render,routes} from '../render.mjs';import {isIndexablePath} from '../site.mjs';import {homeSlides} from '../home-content.mjs';import {spots,courses,events,sortSpots} from '../data.mjs';import {photos} from '../photos.mjs';import {spotCoordinates} from '../spot-coordinates.mjs';
test('all requested routes render and internal links resolve',()=>{for(const route of routes){const {html,status}=render(route);assert.equal(status,200,route);for(const [,href]of html.matchAll(/<a\b[^>]*\bhref="(\/[^"?#]*)(?:[?#][^"]*)?"/g)){assert.ok(href==='/styles.css'||href==='/favicon.svg'||href.startsWith('/assets/icons/')||routes.includes(href),`${route}: ${href}`)}assert.ok(!html.includes('undefined'),route)}});
test('real vote sorting, then initial rank; no fictitious seed counts',()=>{assert.ok(spots.every(s=>s.recommend_count===0));assert.deepEqual(sortSpots([{slug:'a',initial_rank:1,recommend_count:0},{slug:'b',initial_rank:5,recommend_count:1},{slug:'c',initial_rank:2,recommend_count:0}]).map(s=>s.slug),['b','a','c']);assert.deepEqual(sortSpots(spots.filter(s=>s.category==='sightseeing')).slice(0,3).map(s=>s.slug),['ryugado','nikobuchi','iokido']);assert.ok(courses.length>=10)});
test('course stop order matches scheduled stop order',()=>{for(const c of courses){const scheduled=(c.schedule||[]).map(x=>x.slug).filter(Boolean);assert.deepEqual(c.stops,scheduled,c.slug)}});
test('spot details show planning facts and stay estimates without inventing missing data',()=>{const stay=new Map();for(const c of courses)for(const [slug,mins] of Object.entries(c.stopMinutes||{})){if(!stay.has(slug))stay.set(slug,Number(mins));else assert.equal(stay.get(slug),Number(mins),slug+': inconsistent stay minutes')}assert.equal(stay.size,41);for(const s of spots){const html=render('/spots/'+s.slug+'/').html;assert.ok(html.includes('class="spot-plan-summary"'),s.slug);if(String(s.opening_hours||'').trim()&&!['未確認','確認中'].includes(String(s.opening_hours).trim()))assert.ok(html.includes('<strong>営業時間</strong>'),s.slug);if(String(s.price_text||'').trim()&&!['未確認','確認中'].includes(String(s.price_text).trim()))assert.ok(html.includes('<strong>料金</strong>'),s.slug);if(String(s.parking_text||'').trim()&&!['未確認','確認中'].includes(String(s.parking_text).trim()))assert.ok(html.includes('<strong>駐車場</strong>'),s.slug);if(stay.has(s.slug)){assert.ok(html.includes('<strong>滞在目安</strong><span>約'+stay.get(s.slug)+'分</span>'),s.slug)}else{assert.ok(!html.includes('<strong>滞在目安</strong>'),s.slug)}}});
test('course route corrections do not change curated representative photos',()=>{const family=courses.find(c=>c.slug==='family');assert.equal(family.photo?.src,spots.find(s=>s.slug==='makino-botanical-garden')?.photo?.src)});
test('unknown routes return 404 and SEO metadata is per-page',()=>{assert.equal(render('/no-such-route/').status,404);const html=render('/spots/nikobuchi/','https://kochi.example').html;assert.match(html,/<title>にこ淵/);assert.match(html,/rel="canonical" href="https:\/\/kochi.example\/spots\/nikobuchi\/"/);assert.match(html,/noindex,nofollow/);assert.match(render('/','https://kochi.example',true).html,/index,follow/)});
test('home slider uses seven configured slides and accessible controls',()=>{const html=render('/').html;assert.equal(homeSlides.length,7);assert.equal((html.match(/data-carousel-slide/g)||[]).length,homeSlides.length);assert.match(html,/kochi-sup-hero\.jpg/);assert.match(html,/kochi-sup-hero\.jpg[^>]*loading=\"eager\"[^>]*fetchpriority=\"high\"/);assert.equal((html.match(/loading=\"eager\"/g)||[]).length,1);assert.match(html,/loading=\"lazy\" fetchpriority=\"low\" decoding=\"async\"/);assert.doesNotMatch(html,/src=\"\/config\.js\"/);assert.match(html,/rel=\"preload\" as=\"image\" href=\"\/assets\/photos\/hero-sup-mobile\.jpg\"/);assert.match(html,/rel=\"preload\" as=\"image\" href=\"\/assets\/photos\/kochi-sup-hero\.jpg\"/);for(const src of ['hero-paragliding.jpg','hero-buggy.jpg','hero-forest-adventure.jpg','hero-camping.jpg','hero-rafting.jpg','hero-ryugado.jpg'])assert.match(html,new RegExp(src));assert.equal((html.match(/data-carousel-dot/g)||[]).length,homeSlides.length);assert.equal((html.match(/data-carousel-index/g)||[]).length,homeSlides.length);assert.match(html,/data-carousel-prev/);assert.match(html,/data-carousel-next/);assert.match(html,/class="home-search"/);assert.match(html,/aria-label="エリア"/);for(const slide of homeSlides){assert.match(html,new RegExp(slide.href.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))}});
test('home exposes the five travel style category links',()=>{const html=render('/').html;for(const path of ['/cycling/','/camp/','/onsen/','/michinoeki/','/stay/'])assert.match(html,new RegExp(`href=\"${path.replaceAll('/','\\/')}\"`))});
test('all Snow Peak Ochi display photos use the provided unified image',()=>{const src='/assets/photos/snowpeak-ochi-niyodogawa-main.avif';assert.equal(photos['snowpeak-ochi-niyodogawa']?.src,src);for(const path of ['/','/camp/','/spots/snowpeak-ochi-niyodogawa/','/courses/niyodo-camp-stay/','/area/north-niyodo/']){const html=render(path).html;assert.ok(html.includes(src),path);assert.ok(!html.includes('/assets/photos/snowpeak-ochi-niyodogawa.jpg'),path)}});
test('all Kashiwajima display photos use the provided unified image',()=>{const src='/assets/photos/kashiwajima-pickup.webp';for(const key of ['kashiwajima','kashiwajima-diving-aquas','otsuki-glassboat-yubari','kashiwajima-pickup'])assert.equal(photos[key]?.src,src,key);for(const path of ['/','/spots/kashiwajima/','/spots/kashiwajima-diving-aquas/','/spots/otsuki-glassboat-yubari/','/area/west/']){const html=render(path).html;assert.ok(html.includes(src),path);assert.ok(!html.includes('/assets/photos/kashiwajima.jpg'),path)}});
test('home editorial hierarchy keeps three curated courses and puts save before ranking on spot details',()=>{const homeHtml=render('/').html;assert.equal((homeHtml.match(/class=\"home-course-card\"/g)||[]).length,3);const detailHtml=render('/spots/kashiwajima/').html;assert.ok(detailHtml.indexOf('data-save-spot')<detailHtml.indexOf('spot-rank-summary'))});
test('course index presents five editorial trip entrances',()=>{const html=render('/courses/').html;for(const label of ['初めての高知','自然を満喫','子連れで楽しむ','雨の日も高知へ','1泊2日でめぐる'])assert.ok(html.includes(label),label);assert.equal((html.match(/class=\"course-editorial-card\"/g)||[]).length,5);for(const query of ['theme=%E7%8E%8B%E9%81%93','theme=%E3%82%A2%E3%82%AF%E3%83%86%E3%82%A3%E3%83%96','theme=%E5%AD%90%E9%80%A3%E3%82%8C','theme=%E9%9B%A8%E3%81%AE%E6%97%A5','duration=1%E6%B3%8A2%E6%97%A5'])assert.ok(html.includes(query),query)});\ntest('home PICK UP presents three editorial travel ideas',()=>{const html=render('/').html;assert.match(html,/class="home-pickup-section"/);assert.match(html,/>PICK UP</);assert.match(html,/>今、行きたい高知</);assert.equal((html.match(/class="home-pickup-card/g)||[]).length,3);for(const href of ['/area/north-niyodo/','/courses/karst-drive/','/courses/ocean-trip/'])assert.ok(html.includes(`href="${href}"`),href);for(const src of ['/assets/photos/niyodo-blue-pickup.webp','/assets/photos/shikoku-karst-web.jpg','/assets/photos/kashiwajima-pickup.webp'])assert.ok(html.includes(`src="${src}"`),src)});
test('mobile global menu exposes primary and support destinations',()=>{for(const path of ['/','/spots/kochi-castle/']){const html=render(path).html;assert.match(html,/data-mobile-menu-open/);assert.match(html,/id="mobile-site-menu"/);assert.match(html,/aria-controls="mobile-site-menu"/);assert.match(html,/class="mobile-header-actions"/);for(const href of ['/search/','/courses/','/area/','/features/','/events/','/guide/','/mypage/','/about/','/suggest/','/correction/','/contact/'])assert.ok(html.includes(`href="${href}"`),path+': '+href)}});
test('site header brand is consistent and spot rank copy is visitor-friendly',()=>{for(const path of ['/','/spots/kochi-castle/','/courses/']){const html=render(path).html;assert.match(html,/class="brand site-brand/);assert.match(html,/class="site-brand-mark home-brand-mark"/);assert.match(html,/KOCHI TRAVEL GUIDE/)}const spot=render('/spots/kochi-castle/').html;assert.match(spot,/歴史文化ランキング/);assert.ok(spot.includes('id="current-rank">4</span>位'));assert.doesNotMatch(spot,/現在順位：/);assert.doesNotMatch(spot,/初期順位：/)});
test('sitemap route selection excludes private and sample pages while indexing populated categories',()=>{assert.equal(isIndexablePath('/spots/nikobuchi/'),true);assert.equal(isIndexablePath('/gourmet/'),true);assert.equal(isIndexablePath('/fishing/'),true);assert.equal(isIndexablePath('/surfing/'),true);assert.equal(isIndexablePath('/suggest/'),true);assert.equal(isIndexablePath('/search/'),false);assert.equal(isIndexablePath('/cycling/'),true);assert.equal(isIndexablePath('/stay/'),true);assert.equal(isIndexablePath('/camp/'),true);assert.equal(isIndexablePath('/onsen/'),true);assert.equal(isIndexablePath('/michinoeki/'),true);assert.equal(isIndexablePath('/events/sample-riverside/'),false)});
test('events page defaults to upcoming verified events while keeping past records available',()=>{const html=render('/events/').html;const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo'}).format(new Date());const upcoming=events.filter(e=>!e.is_demo&&e.end_date>=today);assert.equal((html.match(/class=\"card event-card\"/g)||[]).length,upcoming.length);assert.match(html,/<option value=\"これから\" selected>/);assert.ok(events.filter(e=>!e.is_demo).length>=upcoming.length);assert.doesNotMatch(html,/確認済みの開催情報はまだありません/)});
test('experience listing shows twelve recommendations before a more button',()=>{const total=spots.filter(s=>s.category==='experience'&&s.is_published!==false).length;const html=render('/experience/').html;assert.match(html,/>おすすめ体験</);assert.match(html,/id="experience-more-extra" hidden/);assert.match(html,new RegExp('data-remaining="'+Math.max(0,total-17)+'"'));assert.match(html,/data-experience-more-toggle/)});
test('ranking pages explain the vote and tie-break rules',()=>{for(const path of ['/experience/','/activity/','/gourmet/','/sightseeing/','/camp/']){const html=render(path).html;assert.match(html,/class="ranking-guide"/,path);assert.match(html,/ランキングの仕組み/,path);assert.match(html,/おすすめ投票数を優先/,path);assert.match(html,/同票なら初期順位/,path);assert.match(html,/各スポットに1票まで/,path);assert.match(html,/掲載時は0票から/,path)}});
test('fishing and surfing rankings have published spots',()=>{const fishing=spots.filter(s=>s.category==='fishing'&&s.is_published!==false);const surfing=spots.filter(s=>s.category==='surfing'&&s.is_published!==false);assert.equal(fishing.length,4);assert.equal(surfing.length,3);assert.match(render('/fishing/').html,/須崎・富士ヶ浜 海釣り体験/);assert.match(render('/surfing/').html,/生見サーフィンビーチ/)});
test('published spots do not expose demo or verification placeholder copy',()=>{assert.ok(spots.every(s=>s.is_demo===false));assert.ok(spots.every(s=>!String(s.description||'').includes('初期掲載候補')));const html=render('/spots/kashiwajima/').html;assert.doesNotMatch(html,/未確認|確認中|初期掲載候補/)});
test('every published spot has a configured photo and local photo files exist',async()=>{for(const s of spots.filter(s=>s.is_published!==false)){assert.ok(s.photo?.src,`${s.slug}: photo missing`);if(s.photo.src.startsWith('/assets/'))await access(resolve('assets',s.photo.src.replace('/assets/','')),constants.F_OK);else assert.match(s.photo.src,/^https:\/\//,`${s.slug}: invalid photo URL`)}});
test('saved trips page exposes route planner controls',()=>{const html=render('/mypage/').html;assert.match(html,/id="saved-route-tools"/);assert.match(html,/id="saved-route-count"/);assert.match(html,/id="saved-route-map"/);assert.match(html,/保存したスポットで旅程をつくる/);assert.match(html,/Google Mapsでルートを見る/)});
test('every spot has a plausible Kochi map coordinate',()=>{assert.equal(Object.keys(spotCoordinates).length,spots.length);for(const s of spots){const c=spotCoordinates[s.slug];assert.ok(c,s.slug+': coordinate missing');assert.ok(Number.isFinite(c.lat)&&c.lat>=32&&c.lat<=34.5,s.slug+': latitude out of range');assert.ok(Number.isFinite(c.lng)&&c.lng>=132&&c.lng<=135,s.slug+': longitude out of range')}});
test('search and area detail pages expose lazy list-map switching',()=>{const search=render('/search/').html,area=render('/area/east/').html,home=render('/').html;for(const html of [search,area]){assert.match(html,/data-spot-view="list"/);assert.match(html,/data-spot-view="map"/);assert.match(html,/data-spot-map/);assert.ok(html.includes('/assets/vendor/leaflet/leaflet.css'));assert.ok(html.includes('/assets/vendor/leaflet/leaflet.js'))}assert.ok(!home.includes('/assets/vendor/leaflet/leaflet'))});
test('legal, privacy, and contact pages use the approved public details',()=>{const terms=render('/terms/').html,privacy=render('/privacy/').html,contact=render('/contact/').html;assert.match(terms,/<h1>利用規約<\/h1>/);assert.doesNotMatch(terms,/公開前草案/);assert.match(privacy,/localStorage/);assert.match(privacy,/OpenStreetMap/);assert.doesNotMatch(privacy,/公開前草案/);assert.match(contact,/mailto:luidabase@gmail\.com/);assert.match(contact,/掲載追加申請/);assert.match(contact,/情報修正申請/)});
test('every rendered CC BY or CC BY-SA photo has nearby attribution',()=>{const bySrc=new Map(Object.values(photos).filter(p=>p?.src&&/^CC BY(?:-SA)?\b/i.test(String(p.license||''))).map(p=>[p.src,p]));for(const route of routes){const html=render(route).html;for(const match of html.matchAll(/<img\b[^>]*\bsrc="([^"]+)"[^>]*>/g)){const photo=bySrc.get(match[1]);if(!photo)continue;const nearby=html.slice(match.index,Math.min(html.length,match.index+5000));assert.ok(nearby.includes(String(photo.author||'')),`${route}: missing author for ${match[1]}`);assert.ok(nearby.includes(String(photo.license||'')),`${route}: missing license for ${match[1]}`)}}});

const meta=(html,key)=>html.match(new RegExp(`<meta (?:name|property)="${key}" content="([^"]*)"`))?.[1];
const structured=html=>[...html.matchAll(/<script type="application\/ld\+json">(.*?)<\/script>/gs)].map(match=>JSON.parse(match[1]));
const seoOrigin='https://seo.kochi.example';
test('every page has absolute OGP and matching Twitter metadata; details use their own photos',()=>{
  const unavailable=new Set(['/assets/photos/ashizuri.jpg','/assets/photos/chikurinji.png','/assets/photos/course-karst-panorama.png','/assets/photos/course-niyodo-sauna.png','/assets/photos/event-okawa.png','/assets/photos/event-okyaku.png','/assets/photos/karst.jpg','/assets/photos/kashiwajima.jpg','/assets/photos/kochi-castle.jpg','/assets/photos/ryugado.jpg','/assets/photos/yasui.jpg','/assets/photos/yusuhara.jpg']);
  const safeImage=path=>{const safe=unavailable.has(path)?homeSlides[0].photo.src:path;return safe?.endsWith('.avif')?safe.slice(0,-5)+'.jpg':safe;};
  const expected=new Map([['/',safeImage(homeSlides[0].photo.src)],...spots.map(s=>[`/spots/${s.slug}/`,safeImage(s.photo?.src)]),...courses.map(c=>[`/courses/${c.slug}/`,safeImage(c.photo?.src)]),...events.map(e=>[`/events/${e.slug}/`,safeImage(e.image)])]);
  for(const path of routes){
    const html=render(path,seoOrigin).html;
    assert.equal(meta(html,'og:image'),new URL(expected.get(path)||safeImage(homeSlides[0].photo.src),seoOrigin).href,path);
    assert.equal(meta(html,'twitter:image'),meta(html,'og:image'));
    assert.equal(meta(html,'twitter:card'),'summary_large_image');
    assert.equal(meta(html,'twitter:title'),html.match(/<title>(.*?)<\/title>/s)[1]);
    assert.equal(meta(html,'twitter:description'),meta(html,'description'));
  }
});
test('generated OGP image files exist in the deployable asset directory',async()=>{
  for(const path of routes){
    const image=new URL(meta(render(path,seoOrigin).html,'og:image'));
    if(image.origin===seoOrigin)await access(resolve(import.meta.dirname,'..','dist','.'+image.pathname),constants.R_OK);
    else assert.equal(image.protocol,'https:');
  }
});
test('home has one H1 and six H2 slide titles without changing slide copy',()=>{
  const html=render('/').html;
  assert.equal([...html.matchAll(/<h1(?:\s[^>]*)?>/g)].length,1);
  assert.equal([...html.matchAll(/<h2 class="home-slide-title">/g)].length,6);
  assert.ok(html.includes(`<h1 class="home-slide-title">${homeSlides[0].title}</h1>`));
});
test('major listing pages have distinct relevant titles and descriptions',()=>{
  const titles=new Set(),descriptions=new Set();
  for(const [route,keyword] of Object.entries({sightseeing:'観光',gourmet:'グルメ',activity:'アクティビティ',fishing:'釣り',surfing:'サーフィン',courses:'モデルコース',events:'イベント',area:'エリア',features:'特集',guide:'お役立ち情報'})){
    const html=render(`/${route}/`).html,title=html.match(/<title>(.*?)<\/title>/s)[1],description=meta(html,'description');
    assert.ok(title.includes('高知')&&title.includes(keyword),route);
    assert.ok(description.includes('高知'),route);
    assert.ok(!titles.has(title)&&!descriptions.has(description),route);
    titles.add(title);descriptions.add(description);
  }
  for(const key of ['og:title','description'])assert.ok(meta(render('/activity/').html,key).includes('体験'));
});
test('Organization and breadcrumbs are valid JSON-LD with consistent names and URLs',()=>{
  const [org,website]=structured(render('/',seoOrigin).html);
  assert.equal(website['@type'],'WebSite');assert.equal(website.name,'高知観光ランキング');assert.equal(website.url,seoOrigin);
  assert.equal(org['@type'],'Organization');assert.equal(org.name,'高知観光ランキング運営事務局');assert.equal(org.url,seoOrigin);assert.equal(org.email,'luidabase@gmail.com');
  for(const path of routes){
    const html=render(path,seoOrigin,true).html,data=structured(html);
    assert.ok(data.every(item=>item['@type']!=='Event'));
    if(path==='/'||!isIndexablePath(path))continue;
    assert.equal(data[0]['@context'],'https://schema.org');assert.equal(data[0]['@type'],'BreadcrumbList');
    const crumbs=data[0].itemListElement;
    assert.equal(crumbs[0].name,'高知観光ランキング');assert.equal(crumbs.at(-1).item,new URL(path,seoOrigin).href);
    for(const [i,crumb] of crumbs.entries()){assert.equal(crumb.position,i+1);assert.ok(routes.includes(new URL(crumb.item).pathname));assert.ok(html.includes(crumb.name),`${path}: ${crumb.name}`);}
  }
  assert.equal(structured(render('/missing/',seoOrigin).html).length,0);
});
test('build emits browser cache rules for static assets',async()=>{const source=await readFile(resolve('scripts/build.mjs'),'utf8');assert.match(source,/assets\/photos\/\*/);assert.match(source,/max-age=86400/);assert.match(source,/app\.mjs/);assert.match(source,/max-age=3600/)});
test('canonical, verification and robots remain correct for every route in both indexing modes',()=>{
  for(const path of routes)for(const enabled of [false,true]){
    const html=render(path,seoOrigin,enabled).html;
    assert.ok(html.includes(`<link rel="canonical" href="${new URL(path,seoOrigin).href}">`),path);
    assert.equal(meta(html,'og:url'),new URL(path,seoOrigin).href);
    assert.equal(meta(html,'robots'),enabled&&isIndexablePath(path)?'index,follow':'noindex,nofollow',path);
    assert.equal(meta(html,'google-site-verification'),'j0jdY1lGkbx4WJENSEIsxvwWHxyX5CEY5NcRc6riXx4');
  }
  for(const path of ['/search/','/mypage/','/login/','/missing/'])assert.equal(meta(render(path,seoOrigin,true).html,'robots'),'noindex,nofollow');
  assert.doesNotMatch(render('/missing/',seoOrigin,true).html,/rel="canonical"/);
});
